### ISSUE TITLE
Option for using gtk-theme buttons 

### ISSUE THREAD

**Issue by RockOnHero** [hardpixel/unite-shell#10]
First of all, your extension is genius and really needed for the GNOME-Desktop in my opinion. My issue or better enhancement would be, enable the user to **use his gtk-theme buttons** for the close, min and max buttons. Additionally i would give the option to replace the activity button with window-controls and get the activity button back if no window is maximized. This way **the window-title would not move** if a window get maximized. All of this adds consistency and would be really awesome.

Please take this with a grain of salt, because i have no experience with GNOME-Shell-extensions and don't really know, if this enhancement is possible. Anyway, thank you for the effort.

**Comment by jonian** [comment]
Hi @RockOnHero, thank you for your input.
Window button themes and hiding activity button are in our roadmap. We will also add settings to make them configurable.

**Comment by RockOnHero** [comment]
@jonian maybe the roadmap could go in the readme for reference?

**Comment by jonian** [comment]
@RockOnHero there is no roadmap with dates. Issues marked as `enhancement` or `feature` will be implemented.

**Comment by franglais125** [comment]
@jonian In case you might find it useful, I have implemented something similar in my extension (a fork of Pixel Saver). it might serve as guidance or save some time:

https://github.com/franglais125/no-title-bar/commit/1f2c4581cd807d24fd1415f6d05c61c9d3d7892f

**Comment by jonian** [comment]
@franglais125 thank you! I have already started implementing this, but I have been busy with work.

https://github.com/hardpixel/unite-shell/blob/master/unite%40hardpixel.eu/settings.ui#L310
https://github.com/hardpixel/unite-shell/blob/master/unite%40hardpixel.eu/schemas/org.gnome.shell.extensions.unite.gschema.xml#L2
https://github.com/hardpixel/unite-shell/blob/master/unite%40hardpixel.eu/prefs.js#L58

**Comment by jonian** [comment]
Window button themes are now available in master branch. Included themes:

- Default Dark
- Default Light
- Ambiance
- Radiance
- Arc Dark
- Arc Light
- United Dark
- United Light

More themes will be added in the future.

**Comment by tumb1er** [comment]
@jonian on Ubuntu-18.04 at current master no window button icons appear at all, empty space that works like buttons.
