### ISSUE TITLE
Disable Title Bars For Legacy Applications Only

### ISSUE THREAD

**Issue by velitasali** [hardpixel/unite-shell#101]
Hello everyone, 

Great work.

I have a suggestion that I thought I achieved by editing some scripts and I wanted to ask if it could be possible for you to add another option to completely disable manipulating visibility of  the window buttons.

What I mean is that, when the configuration is like this;
![Screenshot from 2019-03-30 23-18-39](https://user-images.githubusercontent.com/10258162/55281209-2da13f80-5342-11e9-9ff6-b8879f2ebd94.png)

I want to have buttons for the apps the GTK apps. Adding an option to make it happen would be awesome
![Screenshot from 2019-03-30 23-22-18](https://user-images.githubusercontent.com/10258162/55281255-d8b1f900-5342-11e9-8eef-c2045e7f2ea0.png)

Also commenting the line below didn't help much.
![Screenshot from 2019-03-30 23-26-56](https://user-images.githubusercontent.com/10258162/55281304-68f03e00-5343-11e9-8234-c7e75f3814dc.png)

**Comment by velitasali** [comment]
No longer required. Created my own extension.Thanks anyway!

**Comment by dobroweb** [comment]
How did you do that? Can you add this as an option in Unite?
