### ISSUE TITLE
Frameless electron windows freeze gnome-shell when maximized with this extension

### ISSUE THREAD

**Issue by omeryagmurlu** [hardpixel/unite-shell#102]
gnome-shell: 3.32
unite: 27

Frameless windows (as in windows with no titlebar or controls etc.) freeze gnome-shell when maximized if this extension is enabled. Before updating to 3.32 I was using the `no-title-bar` extension and it didn't have this problem (it is not updated to 3.32 yet). 

To reproduce:

1. download the [sample app AppImage](https://drive.google.com/open?id=1waXgJMNOo8S1jvvx6uJixgxilSfuxdOW) (it is 76MB, you can also build it from the source, link is below)
2. make sure `unite-shell` extension is enabled
3. open app
4. click maximize
5. observe gnome-shell freeze

References: 
[Electron Frameless Window](https://electronjs.org/docs/api/frameless-window)
[no-title-bar](https://github.com/franglais125/no-title-bar)
[Source Code for sample app](https://github.com/hokein/electron-sample-apps/tree/master/frameless-window)

**Comment by jonian** [comment]
Hi @omeryagmurlu, thanks for the report. Can you try with master branch? I think the issue is fixed and may be related to #93.

**Comment by omeryagmurlu** [comment]
Yes, the issue isn't present with the master branch. Thank you for your time writing this extension, it is very helpful.
