### ISSUE TITLE
Opening chrome on gnome 3.32 freezes the whole shell

### ISSUE THREAD

**Issue by TN3rd** [hardpixel/unite-shell#104]
When unite is activated and google chrome is opened, chrome just seems to crash imidately, the shell becomes laggy and then completely freezes.

**Comment by jonian** [comment]
Try the master branch, the issue may be similar to #102 and #93.
Alternatively enable `System titlebars and borders` in google chrome.

**Comment by TN3rd** [comment]
The last update seems to have corected the issue, since I tried master before submitting the issue. Now master works flawlessly. Thank you for fast response!

**Comment by TN3rd** [comment]
And sorry to bother but I just found out that the action of changing titlebar to system still exibits the same behaviour. Just the action of changing it though, which is great improvement.

**Comment by jonian** [comment]
Thanks for reporting back!
