### ISSUE TITLE
High CPU usage in gnome-shell 3.32

### ISSUE THREAD

**Issue by luispabon** [hardpixel/unite-shell#107]
I've noticed Unite causes gnome shell to have a fair amount of CPU usage (~70% of a single core, constant) whenever the top panel is visible. Usage drops as soon as something goes full screen over it (for instance, full screen terminator) or I disable unite (which I absolutely don't want to do). This is in Pop 19.04. Is there anything I can do to help diagnose the problem?

**Comment by luispabon** [comment]
https://youtu.be/1Pwm9431US4

**Comment by Soulike** [comment]
The same problem. Gnome-shell constantly occupies 1 core of cpu if I turn Unite on.

**Comment by Soulike** [comment]
I think the problem is the same to #53  and #96 . Just turn off "show system tray in top bar" can solve it.

**Comment by luispabon** [comment]
Yeah, it seems to be that. Turning off tray icons straight away brings cpu usage down to zero.

**Comment by luispabon** [comment]
Yeah, it seems to be that. Turning off tray icons straight away brings cpu usage down to zero.

**Comment by luispabon** [comment]
Looks like the issue is being looked at by the gnome bods. Ubuntu's extension seems to work fine.
