### ISSUE TITLE
When "Restrict functionalities to the primary screen" is false, window buttons are always displayed in main monitor

### ISSUE THREAD

**Issue by raelgc** [hardpixel/unite-shell#113]
Configuration: 
- 2 displays
- multi monitors extension enabled
- unite configured to hide title when maximized
- united configured to show window buttons in top bar when window is maximized.

**Steps to reproduce:**
1. Open an application in secondary display and maximize it.

**Expected behavior**: window buttons are display in **current** display top bar.

**Current behavior**: window buttons are always displayed in **main** display top bar.

**Comment by jonian** [comment]
Multi monitors extension is not supported. Feature requested in #19
