### ISSUE TITLE
[Feature Request] Option to show appMenu icon

### ISSUE THREAD

**Issue by hugoroy** [hardpixel/unite-shell#114]
This looks related to #43 but not sure this is the same thing.

I notice that by default appMenu icons are hidden (see https://github.com/hardpixel/unite-shell/commit/746f0d0c78622c0985278cff4babf38d8cabf89a)

I think it would be nice to have it as an option to reenable such icons. I personally modify the code each time I update this extension just to get it back.

**Comment by murat-cileli** [comment]
Same here.

**Comment by Amathadius** [comment]
Same.
