### ISSUE TITLE
Unite crashes after locking screen

### ISSUE THREAD

**Issue by jeroenpraat** [hardpixel/unite-shell#115]
When I lock the screen (with Super+L) and come back, Unite is crashed. Here is the syslog output:

`May 16 18:14:42 mydesktop gnome-shell[16974]: JS ERROR: TypeError: widget is null#012_removePanelArrows@/home/jeroen/.local/share/gnome-shell/extensions/unite@hardpixel.eu/modules/themeMods.js:99:38#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_addToPanelBox@resource:///org/gnome/shell/ui/panel.js:1144:9#012addToStatusArea@resource:///org/gnome/shell/ui/panel.js:1171:9#012enable@/home/jeroen/.local/share/gnome-shell/extensions/openweather-extension@jenslody.de/extension.js:1672:5#012enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:131:9#012enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:338:13#012enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:337:9#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:365:9#012_emit@resource:///org/gnome/gjs/modules/signals.js:128:27#012_sync@resource:///org/gnome/shell/ui/sessionMode.js:204:9#012popMode@resource:///org/gnome/shell/ui/sessionMode.js:173:9#012_continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:1202:13#012deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:1188:41#012finish@resource:///org/gnome/shell/gdm/authPrompt.js:493:13#012finish@resource:///org/gnome/shell/ui/unlockDialog.js:129:9#012deactivate@resource:///org/gnome/shell/ui/screenShield.js:1188:13#012ScreenShield</</<@resource:///org/gnome/shell/ui/screenShield.js:538:54#012_emit@resource:///org/gnome/gjs/modules/signals.js:128:27#012_convertToNativeSignal@resource:///org/gnome/gjs/modules/overrides/Gio.js:117:5`

Unite v30, running Gnome in 3.32 on Ubuntu 19.04.

**Comment by jonian** [comment]
Hi @jeroenpraat, thanks for the report. Can you try the master branch? The issue should be fixed.

**Comment by jeroenpraat** [comment]
@jonian It works! Thank you for fixing this.
