### ISSUE TITLE
Size of dock no longer scaling with other fonts

### ISSUE THREAD

**Issue by fmanin** [hardpixel/unite-shell#116]
Since I have a high-resolution laptop screen, I run it with large fonts and icon sizes (1.8x normal), using the Scaling Factor setting in Gnome Tweaks.  The Unite dock used to also have a larger font, but as of the last update it's looking tiny.  (It would be nice to scale the icon sizes as well, if possible.)
![Screenshot from 2019-05-18 15-23-16](https://user-images.githubusercontent.com/5482670/57974108-e9fda600-7980-11e9-9a95-59b9504dcb2f.png)

**Comment by jonian** [comment]
Hi @fmanin, thanks for the report. Can you try with the setting "Apply system fonts to shell theme" turned off? I think it will fix your issue.

**Comment by fmanin** [comment]
Yes, that works!  Thanks!

**Comment by jonian** [comment]
Hi again @fmanin. Can you try the master branch with  "Apply system fonts to shell theme" enabled? Commit [59d89d2](https://github.com/hardpixel/unite-shell/commit/59d89d2f5f4e3f116ab0976cc789fe35d791fbcc) should fix the issue.

**Comment by lydell** [comment]
@jonian The fix works well with "Apply system fonts to shell theme" enabled! Thank you!
