### ISSUE TITLE
When 'Show window title in app menu' is not set to 'Never', no window menu is shown

### ISSUE THREAD

**Issue by aquatix** [hardpixel/unite-shell#118]
For example, when set to 'Maximized', just the drag handle is shown. The menu does not show up either by left or right clicking.

Using Ubuntu 19.04 with gnome-shell 3.32.1

Please let me know what other information I can provide.

Thanks for this great extension!

**Comment by jonian** [comment]
Fixed in https://github.com/hardpixel/unite-shell/commit/1f1bd8150657e830fc9b5222a17f6349897de850
