### ISSUE TITLE
Don't Hide CSD Window Buttons

### ISSUE THREAD

**Issue by murat-cileli** [hardpixel/unite-shell#119]
![image](https://user-images.githubusercontent.com/6532000/59525533-45b74280-8edf-11e9-859a-ea049ed30d57.png)

Example extension: https://extensions.gnome.org/extension/1732/gtk-title-bar/

**Comment by vali20** [comment]
This is debatable, it could be a setting as well: if one chooses to show window buttons on the top bar when window is maximized, they presumably don't want maximized header bar apps to still show their window controls. The current functionality is good for some use cases, including mine.

**Comment by jonian** [comment]
@vali20 If this gets implemented, it will definitely be a setting. My use case is the same as yours.
