### ISSUE TITLE
Wrong render on window maximize on edges

### ISSUE THREAD

**Issue by jgabriel98** [hardpixel/unite-shell#120]
When the window is maximized, and "unmaximize" it (click maximize button again) the window curved edges (top left and top right) aren't properly rendered. Resizing the window makes it come back to normal:

![Captura de tela de 2019-06-18 13-19-40](https://user-images.githubusercontent.com/37881981/59701452-0da84c00-91cc-11e9-8f26-85476c58da9c.png)

![simplescreenrecorder-2019-06-18(1)](https://user-images.githubusercontent.com/37881981/59702982-5ad9ed00-91cf-11e9-8a6d-58ee35d49f6b.gif)

note: please open the image and gif at full size, to see the bug more easily.

this is on ubuntu 19.04 disco dingo

**Comment by huylenguyen806** [comment]
This doesn't happen when using arc-theme

**Comment by ceiphr** [comment]
Same issue. Yaru theme. Ubuntu 20.04 LTS.

**Comment by gcvl** [comment]
An easy workaround is to install the "Rounded Window Corners" extension from the GNOME repository: this apparently "fixes" it.
