### ISSUE TITLE
[Feaute Request] Hide window titlebar for all windows

### ISSUE THREAD

**Issue by akvadrako** [hardpixel/unite-shell#122]
I would like to hide the title bar for all windows, including those that aren't tiled. So with a new entry "Always" to "Hide Window Titlebars". Is this possible?

**Comment by jonian** [comment]
Yes, it is possible with "Hide Window Titlebars" set to "Always".
You can also disable "Restrict functionalities to the primary screen", to remove the title-bars from windows on all screens.

**Comment by akvadrako** [comment]
I am not asking about "Both", but "Always" - including for normal windows.

**Comment by jonian** [comment]
@akvadrako I misread the question. There is no "Always" option on "Hide Window Titlebars".
