### ISSUE TITLE
Black tray icon and spurious additional pseudo window

### ISSUE THREAD

**Issue by Vampire** [hardpixel/unite-shell#123]
I started jEdit in a freshly installed Ubuntu VM and wondered where my tray icon is.  
I found out they are not shown anymore and after some fiddling found this extension.  

The problem is, as soon as I got your extension installed, the tray icon is there and functional.  
But unfortunately most of the time it is all black: ![grafik](https://user-images.githubusercontent.com/325196/63170126-e1c50d80-c038-11e9-8d81-9f074507ea68.png)

And additionally a second pseudo window that cannot be focused or closed appears in the dock:  
![grafik](https://user-images.githubusercontent.com/325196/63170171-00c39f80-c039-11e9-91d6-dc507659d286.png)

TopIcons Redux has the same problems.
But there is a difference.
While jEdit was running when I disabled TopIcons Redux and installed Unite, the tray icon was shown correctly and no pseudo window present.
But as soon as I accidentally disabled the feature and re-enabled it, it had the same problem.
If I restart the Gnome Shell it works a bit better again, now the pseudo window is gone, but the icon is only shown as grey square.
And if I quit and restart jEdit, we are back to pseudo window and black square.

You can also try with JDownloader 2, it shows the exact same behavior, with the exception that there the icon is also not workable (no clicks are considered), but that might be a problem of JDownloader maybe, not of your extension.

You can even try from a `jshell` by executing `java.awt.SystemTray.getSystemTray().add(new java.awt.TrayIcon(java.awt.Toolkit.getDefaultToolkit().createImage("/home/vampire/jEdit/org/gjt/sp/jedit/icons/themes/tango/32x32/apps/jedit.png")))` with any PNG which will show the same behavior.

But as I have seen the tray icon properly once, I have high hopes that this can somehow get fixed.

**Comment by Vampire** [comment]
You can even try from a `jshell` by executing `java.awt.SystemTray.getSystemTray().add(new java.awt.TrayIcon(java.awt.Toolkit.getDefaultToolkit().createImage("/home/vampire/jEdit/org/gjt/sp/jedit/icons/themes/tango/32x32/apps/jedit.png")))` with any PNG which will show the same behavior.

**Comment by Vampire** [comment]
Actually after the Gnome Shell restart where the icon is painted as grey rectangle, it does not anymore respond to mouse events.

**Comment by jonian** [comment]
Hi @Vampire, sorry for the late response. There is no way to fix this from this extension.

Report this issue on https://gitlab.gnome.org/GNOME/gnome-shell for system-tray.
And on https://github.com/ubuntu/gnome-shell-extension-appindicator for app-indicators.
