### ISSUE TITLE
Unite extension on Ubuntu 19.04 doesn't work correctly

### ISSUE THREAD

**Issue by GIBA-BDV** [hardpixel/unite-shell#125]
### Environment
- Lollypop version: 1.1.4.15
- Operating system: Ubuntu 19.04 (with Gnome interface)
### Request
- I'm using Unite extension on Ubuntu 19.04. In Lollypop, music player, it doesn't work correctly.
### Nautilus Working
![Captura de Tela_selecionar área_20190909220022](https://user-images.githubusercontent.com/55117808/64576128-8cd19a00-d34d-11e9-8871-55d8f5164a77.png)
### Lollypop doesn't work
![Captura de Tela_selecionar área_20190909215948](https://user-images.githubusercontent.com/55117808/64576139-96f39880-d34d-11e9-98ad-68fc796737f4.png)
I already submit this problem to Lollypop issues page: [https://gitlab.gnome.org/World/lollypop/issues/1991](url)

**Comment by shibotto** [comment]
Is by any chance Lollypop installed via snap or flatpak?

**Comment by GIBA-BDV** [comment]
I couldn't installed via snap, I don't know why ...
I already installed the PPA and the snap version (folowing a blog post sequence) but I can't find it on my applications tray.
The screen prints are from the flatpak version.
I'm a simple user trying to contribut to the comunit. I don't know anything about software programing or software integration.

**Comment by jonian** [comment]
Closing. The extension does not support applications installed with snap/flatpak.
