### ISSUE TITLE
Bug (?) dropdown arrow not removed

### ISSUE THREAD

**Issue by keunes** [hardpixel/unite-shell#128]
On the extension's description it says that dropdown buttons should get removed. However, I still see the dropdown next to the battery icon (part of system icons block). Activating https://extensions.gnome.org/extension/800/remove-dropdown-arrows/ does remove the dropdown error.

I'm using Ubuntu 18.04.3 LTS

**Comment by jonian** [comment]
Hi @keunes, the aggregate menu arrow is not removed intentionally.
A setting, to remove it, is available in the master branch.

**Comment by keunes** [comment]
Thanks @jonian.

>  A setting, to remove it, is available in the master branch.

Does this mean it will arrive to my system in due time?

**Comment by jonian** [comment]
The latest version in gnome-extensions includes this feature.

**Comment by keunes** [comment]
Appears I already had it - just had to switch over the setting. Thanks! :D
