### ISSUE TITLE
[Feature Request] Allow zero width appindicator icons 

### ISSUE THREAD

**Issue by Bernmeister** [hardpixel/unite-shell#129]
I use a couple of appindicators, for example https://github.com/fossfreedom/indicator-sysmonitor, which uses the label to write various text messages (cpu/ram) but has no need for an icon.

To get around this, they use a 1 pixel width SVG icon (and Unity happily shows a very thin icon which looks like no icon).  However on GNOME Shell the width of the icon is ignored and so a blank space where a full sized icon would normally appear now shows.  

Is this something you can compensate for: either handle 1 pixel (or zero) width icons, or even handle no specified icon?  Or are you aware of a workaround fix for this (outside of this extension)?

**Comment by jonian** [comment]
This extension does not handle app-indicators. Use this https://github.com/ubuntu/gnome-shell-extension-appindicator (preinstalled on ubuntu).
