### ISSUE TITLE
Extend the close button hitbox to the top left corner

### ISSUE THREAD

**Issue by shiba89** [hardpixel/unite-shell#13]
Requirements:
* activities button needs to be hidden (default for now as of 11c3abf2fb7133ce5c577cce80561e67a75875f0);
* window buttons need to be on the left.

When I wanted to close a maximized window in Unity, I used to mindlessly jam the mouse in the top left corner and click. It was very convenient and I would love to have this in unite-shell.

**Comment by abrandemuehl** [comment]
One quick and dirty way I've been able to do this is to change `height: 20px;` to `height: 28px;` in `unite@hardpixel.eu/stylesheet.css` for `#panel .window-button`

**Comment by shibotto** [comment]
This seems to be a problem again with GNOME 3.34

**Comment by rouvenvolkmann** [comment]
Yes, same for me. Would be great seeing this fixed.
