### ISSUE TITLE
[Feature Request] Make OSD full size.

### ISSUE THREAD

**Issue by Bernmeister** [hardpixel/unite-shell#130]
I have noticed that when OSD are displayed (Ubuntu 18.04) the size is truncated to show the summary line and only one line of the description.

If I mouse-over the OSD, the full summary/message shows.

Is this something you can address with this extension?

**Comment by jonian** [comment]
Hi @Bernmeister, this feature is not in the scope of this extension. Closing.
You can request this feature here: https://gitlab.gnome.org/GNOME/gnome-shell.
