### ISSUE TITLE
Extra Spacing Before App Icon / Title

### ISSUE THREAD

**Issue by murat-cileli** [hardpixel/unite-shell#133]
![image](https://user-images.githubusercontent.com/6532000/66153357-03e41080-e624-11e9-9a1f-c352060ed45b.png)

It's going back to normal when mouse over.

**Comment by jonian** [comment]
Hi @murat-cileli, thanks for the report. 

Are you using the latest commits from the master branch?   
I have made many changes today.

Please provide system details, settings screenshot and the output of `journalctl /usr/bin/gnome-shell`.

**Comment by murat-cileli** [comment]
Yes, I recently downloaded master branch.

[**Journalctl Output**](https://github.com/hardpixel/unite-shell/files/3687544/journalctl.txt)

![Screenshot from 2019-10-03 21-33-43](https://user-images.githubusercontent.com/6532000/66154153-89b48b80-e625-11e9-8fb0-a24144ea4953.png)

![Screenshot from 2019-10-03 21-34-01](https://user-images.githubusercontent.com/6532000/66154170-8faa6c80-e625-11e9-8ad8-f83544663ed7.png)
