### ISSUE TITLE
unite-shell overrides panel theme

### ISSUE THREAD

**Issue by freddyw** [hardpixel/unite-shell#134]
Not sure how to best describe the issue but here it goes. I am using unite-shell and dash-to-panel. I have a custom panel theme background color set in dash-to-panel. Since unite-shell v32 the panel background is set to black after a fresh reboot. Restarting gnome-shell (with ALT-F2 r) restores the custom background as set in dash-to-panel. I have been trying to pinpoint where things go wrong and it looks like line 21 in modules/themeMods.js is the culprit:
this._signals.connect(this.gtkSettings, 'notify::gtk-font-name', 'setPanelStyle')
as soon as I comment that line the panel (and background) looks fine (except the fonts offcourse). I have tried experimenting with disabling/enabling the "Apply system fonts to shell theme" but that does not seem to have any effect. Any idea what might be causing this rather odd incompatibility?

**Comment by freddyw** [comment]
The line was added in this commit: https://github.com/hardpixel/unite-shell/commit/80f094a7ad70ac038499804c65fcf67da9be3959

It happens both in gnome 3.32 (fedora 30) and gnome 3.34 (fedora 31). I can't reproduce the spacing issue mentioned in https://github.com/hardpixel/unite-shell/issues/132, even with the line commented.

**Comment by freddyw** [comment]
investigated a bit further and the "Main.panel.set_style" lines (2x) in themeMods seems to be the cause. I have commented both and things appear rather normal now.

**Comment by freddyw** [comment]
Without the two Main.panel.set_style lines there everything seems to be in working order if not for some weird spacing issue on mouse-over. That one is reported already in dash-to-panel:
https://github.com/home-sweet-gnome/dash-to-panel/issues/739
It could to be a bug in gnome-shell/clutter:
https://gitlab.gnome.org/GNOME/gnome-shell/issues/1708

**Comment by jonian** [comment]
Hi @freddyw, thanks for the report.

I have added a solution to the issue. Can you try it?  
Also you might want to disable `Reduce top items spacing` in appearance tab, if DtP handles the spacing.

Thanks

**Comment by freddyw** [comment]
I cloned the master branch and tested on 3.32 (fedora 30) and 3.34 (fedora 31). Seems to work pretty reliable now (apart from 1 missing panel icon for autokey in 3.34, dunno what causes that). A big thanks for the quick fix. 
The spacing in DtP restricts to the left panel as far as I can see where unite-shell handles the spacing of the right panel. So they are actually complementary so it seems.

**Comment by storm119** [comment]
> Hi @freddyw, thanks for the report.
> 
> I have added a solution to the issue. Can you try it?
> Also you might want to disable `Reduce top items spacing` in appearance tab, if DtP handles the spacing.
> 
> Thanks

@jonian 
First off all...I think I'm having the same if not almost identical issue with @freddyw just that I don't use DtP .

1- I can confirmed this solution sorted my issues with weird fonts sizing + background panel (I used dynamic-panel-transparency ext fwiw).
2- Imho...Weird spacing issue only happen if one use another extension with the same functionality...choose/activate only one so no more weird spacing while hoovering. 
3- Unite-shell running on Manjaro Arch (Gnome 3.34)

Thank you for the solutions...really appreciated!
