### ISSUE TITLE
Unite + Google Chrome 78

### ISSUE THREAD

**Issue by greenvorbisfan** [hardpixel/unite-shell#138]
![Screenshot 2019-10-31 01-59-12](https://user-images.githubusercontent.com/7892693/67905363-1ea59880-fb82-11e9-9b90-3141baa7415f.png)

**Comment by greenvorbisfan** [comment]
Ubuntu 18.04.3 x64 (GNOME-Shell 3.28.4), Google Chrome 78.0.3904.70.

**Comment by jonian** [comment]
Duplicate of #72
