### ISSUE TITLE
Close button should expand hitbox to top left

### ISSUE THREAD

**Issue by rouvenvolkmann** [hardpixel/unite-shell#139]
This issue is basically the same as #13 

> When I wanted to close a maximized window in Unity, I used to mindlessly jam the mouse in the top left corner and click. It was very convenient and I would love to have this in unite-shell.

It was fixed, but appears again after update of Gnome 3.34, so I think this deserves a new issue.

Happens on Ubuntu 19.10 / (default) Yaru Theme.

**Comment by jonian** [comment]
Does this happen with the default shell theme?

I'm on 3.34 and can't reproduce this.

**Comment by dimztimz** [comment]
Happens on Ubuntu 19.10 with its default shell theme (Yaru).

**Comment by dimztimz** [comment]
This might be a bug in Gnome shell itself or in Yaru. If you disable Unite and try to click the button Activity on the most top left pixel, nothing happens.

**Comment by dimztimz** [comment]
I found the upstream bug https://gitlab.gnome.org/GNOME/mutter/issues/893

**Comment by rouvenvolkmann** [comment]
Thanks @dimztimz, I'd say this can be closed now.
