### ISSUE TITLE
[Feature Request] Ability to select size of Top Icons

### ISSUE THREAD

**Issue by pezz** [hardpixel/unite-shell#141]
Hi there,

I find the default size for the top tray icons too small:

size: scaleSize(20)

It'd be great if this could be set through the UI as I normally end up modifying topIcons.js and changing it to 24.

Cheers.

**Comment by enachesilviu** [comment]
They look small, a size input would be useful.

![Screenshot from 2023-03-06 03-52-36](https://user-images.githubusercontent.com/7116229/223002213-d042cc1e-b1c3-4e34-93d1-384b351e70f8.png)

**Comment by jonian** [comment]
Since gnome 44, setting a custom size for tray icons results in icons being stretched and blurry.

**Comment by scarlion1** [comment]
Let's see...

With _AppIndicator and KStatusNotifierItem Support_ extension, can set tray icons up to 96 px.  Here I've set mine to 64 px which is the max size i could set the top bar (with _Just Perfection_ extension) (also have _Transparent Top Bar_ extension active and a starry space wallpaper):
![image](https://github.com/user-attachments/assets/7a0d5af2-050f-467e-ab61-75787b1d7f4f)

The icons this applies to are the 3 large ones on the left and i had the pointer hovering over ClipQ icon to colorize it.
_Just Perfection_ also has a setting for "Panel Icon Size" which I can set up to 60px, which results in:
![image](https://github.com/user-attachments/assets/dbb50664-c1b9-4d3f-a742-c83998858a5d)

This just leaves _Unite_'s smol min, max, close icons on the far right (shown using Breeze icon theme).  I thought it would work if I updated [themes/breeze/stylesheet.css](https://github.com/hardpixel/unite-shell/blob/c24840148d464ae9335da61c1849d3a933efe7a8/unite%40hardpixel.eu/themes/breeze/stylesheet.css#L1) with new <var>width</var> and <var>height</var> values, but no.  Now I think I'll try and make the svg icons bigger, but it seems there should be an easier way for those to scale...
