### ISSUE TITLE
unite appears to break suspend

### ISSUE THREAD

**Issue by rvertesi** [hardpixel/unite-shell#143]
With unite enabled, my laptop won't go into sleep but (randomly for the 2nd or 3rd time) it stays turned on and and locks up. 
I have a Thinkpad L380, running Ubuntu 18.04.3 with 5.0.0-32-generic (also tried with 4.15).
So currently I cannot use Unite. Please tell if you need any further information.

Expected behavior: 
1. closing the lid makes the computer enter suspend, after opening it prompts for password then resumes.
2. pressing suspend button/calling pm-suspend turns screen off, sends laptop to sleep. Pressing the power button it  resumes.

Experienced behavor:
1. by closing the lid the computer keeps running. opening the lid the screen is blank. 
2. the machine immediately prompts for the password, then locks up.
In both cases the light responds to FnLock on/off, but nothing happens for Alt+Ctrl+F2...8 or even Ctrl+Alt+Backspace. Only a hard reset (power button 5 seconds) helps.

Workaround: disable the Unite extension.

**Comment by jonian** [comment]
@rvertesi I have not been able to reproduce this. I you still use this extension, do you still have this issue with the latest version?

**Comment by jonian** [comment]
Closing due to no response. If the issue persists, please open a new issue.

**Comment by peci1** [comment]
Okay, so the sleep errors were caused by the super-outdated ubuntu-appindicators that ship with Ubuntu 18.04. But the exception I reported stays.

**Comment by jonian** [comment]
Hi @peci1, thanks for the report. What version of ubuntu are you using? Your unite version is very old. Can you update to the latest version?

**Comment by peci1** [comment]
I'm on ubuntu 18.04. https://extensions.gnome.org/local/ doesn't offer me any updates for my version of system, so I thought this is the latest compatible one... should master work on 18.04?

**Comment by jonian** [comment]
Master branch is compatible with gnome shell >= 3.32. Earlier versions of gnome shell are no longer supported. What is the gnome shell version on ubuntu 18.04?

**Comment by peci1** [comment]
It's 3.28...
