### ISSUE TITLE
Top bar title text cropped in Ubuntu 19.10

### ISSUE THREAD

**Issue by dandalf02** [hardpixel/unite-shell#144]
I hope this is the proper place to ask for help - after asking a similar question on AskUbuntu, I now think it's a Unite issue. 

Since I upgraded to Ubuntu 19.10  (from 18.04 LTS), I noticed that when I switch between windows, the title in the top bar doesn't show the full text, but a cropped and unaligned version (see below):

[![title bar cropped and unaligned][2]][2]

Here is the expected appearance of the titlebar:
	
[![correct appearance of titlebar][1] ][1]

II have replicated the issue in multiple user themes (and desktop environments). The top bar fixes itself when I interact with the window more (for example when I switch tabs in Firefox). 

  [1]: https://i.stack.imgur.com/MVeil.png
  [2]: https://i.stack.imgur.com/NoukS.png

**Comment by jonian** [comment]
Hi @dandalf02, thanks for the report. 

Can you try the master branch? I think this issue is fixed.

Thanks.

**Comment by dandalf02** [comment]
Hi @jonian, thank you for replying. I have extracted the master branch into to the specified folder and restarted, but now the Unite extension doesn't appear at all (I have also deleted the previous version). Is there something I am missing from the installation process?

**Comment by dandalf02** [comment]
Ok, I just installed the new version from the Gnome extension website and it works wonderfully. Thanks a lot for pointing me there!
