### ISSUE TITLE
Loosing icons after resume from lock

### ISSUE THREAD

**Issue by simontong** [hardpixel/unite-shell#15]
As per the title, when I resume from locked / suspend I have to do the trusty alt+F2 then 'r' command to get them back

**Comment by olibia** [comment]
@simontong thanks for reporting. This has been fixed in version 5, but both v5 and v6 are pending review in gnome shell extensions website. You can install it manually from here.

**Comment by simontong** [comment]
If I install manually does that mean I'll have to do that all the time or will I get a notification about newer updates than v6?

**Comment by jonian** [comment]
@simontong if you use this package https://github.com/hardpixel/unite-shell/releases/download/v6/unite-shell-v6.zip you will get notifications about updates.

**Comment by shiba89** [comment]
Was this bug about tray icons? If that's the case, it's still happening to me on v6 (GNOME 3.26), if it's not, I'll open a new issue.

**Comment by jonian** [comment]
@shiba89 the issue was solved in v5, but after a rewrite we did on v6 it appeared again.
I will try to release a new version soon that fixes it.

**Comment by simontong** [comment]
This has started happening again in v8
