### ISSUE TITLE
Stops working suddenly on Ubuntu 19.10

### ISSUE THREAD

**Issue by cedricfung** [hardpixel/unite-shell#152]
It works before, maybe after some system software updates and restart, it stops working. How to get some debug info?

**Comment by jonian** [comment]
Hi @cedricfung, you can get debug info using `journalctl /usr/bin/gnome-shell | grep unite`, or you can run a nested gnome-shell `dbus-run-session -- gnome-shell --nested --wayland`.

Use the master branch for your tests, it is a complete rewrite of the extension.

**Comment by cedricfung** [comment]
How do I install the master branch? Just copy all the files to `~/.local/share/gnome-shell/extensions/unite@hardpixel.eu`?

**Comment by jonian** [comment]
Yes copy the files from `unite@hardpixel.eu` to `~/.local/share/gnome-shell/extensions/unite@hardpixel.eu`.

**Comment by cedricfung** [comment]
I have copied them, but no logs appeared. And I even rebooted my system.

```
 inflating: /home/anonymous/.local/share/gnome-shell/extensions/unite@hardpixel.eu/modules/activateWindow.js
 inflating: /home/anonymous/.local/share/gnome-shell/extensions/unite@hardpixel.eu/themes/arrongin/maximize-hover.svg
 inflating: /home/anonymous/.local/share/gnome-shell/extensions/unite@hardpixel.eu/prefs.js
 inflating: /home/anonymous/.local/share/gnome-shell/extensions/unite@hardpixel.eu/themes/vimix/minimize-active.svg
 inflating: /home/anonymous/.local/share/gnome-shell/extensions/unite@hardpixel.eu/themes/telinkrin/stylesheet.css
 inflating: /home/anonymous/.local/share/gnome-shell/extensions/unite@hardpixel.eu/themes/vertex/close-active.svg
extracting: /home/anonymous/.local/share/gnome-shell/extensions/unite@hardpixel.eu/metadata.json
```

these logs appeared after I installed the extension from https://extensions.gnome.org/extension/1287/unite/

**Comment by cedricfung** [comment]
![Screenshot from 2020-01-02 18-43-04](https://user-images.githubusercontent.com/2269238/71663336-c2ccdb00-2d8f-11ea-99b7-23826ff5a5f3.png)

I toggle on this extension from the website, then it will always change back to off. Still no logs

**Comment by jonian** [comment]
If there are no logs, it means that unite does not have any errors. Install unite from master branch and enable it from gnome-tweaks.

**Comment by cedricfung** [comment]
It works now after I enabling it from gnome-tweaks, thank you. Maybe the website has bugs.
