### ISSUE TITLE
Unite crashes after unlock

### ISSUE THREAD

**Issue by BlackDex** [hardpixel/unite-shell#154]
Unite Version: V36
GNOME Shell 3.34.4
OS: Arch Linux

Sometimes (not always for some reason) Unite seems to crash after unlocking my systems.
I have a dual/multi screen configuration.

i get the following output when looking in the journalctl when it happens.
`
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: == Stack trace for context 0x55e8a9f9b5a0 ==
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #0   55e8b035d450 i   resource:///org/gnome/shell/ui/environment.js:243 (7efcb409a430 @ 22)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #1   7ffc09132990 b   /home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/handlers.js:54 (7efc98c891f0 @ 15)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #2   55e8b035d3b8 i   /home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/handlers.js:71 (7efc98c89310 @ 26)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #3   55e8b035d310 i   /home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/window.js:329 (7efc98c98280 @ 399)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #4   55e8b035d280 i   /home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/extension.js:13 (7efc98c76f70 @ 66)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #5   55e8b035d1f8 i   /home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/extension.js:39 (7efc98c7f1f0 @ 15)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #6   7ffc091353c0 b   resource:///org/gnome/shell/ui/extensionSystem.js:148 (7efc9b853a60 @ 504)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #7   7ffc09135460 b   resource:///org/gnome/shell/ui/extensionSystem.js:503 (7efc9b858af0 @ 15)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #8   7ffc09135550 b   self-hosted:261 (7efcb40bd040 @ 223)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #9   55e8b035d178 i   resource:///org/gnome/shell/ui/extensionSystem.js:502 (7efc9b858a60 @ 100)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #10   55e8b035d0f8 i   resource:///org/gnome/shell/ui/extensionSystem.js:530 (7efc9b858ca0 @ 53)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #11   7ffc09136c30 b   self-hosted:977 (7efc9b72f700 @ 413)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #12   7ffc09136d10 b   resource:///org/gnome/gjs/modules/signals.js:135 (7efcb40c6040 @ 376)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #13   7ffc09136e10 b   resource:///org/gnome/shell/ui/sessionMode.js:205 (7efc9b6ed280 @ 254)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #14   55e8b035d068 i   resource:///org/gnome/shell/ui/sessionMode.js:174 (7efc9b6ed0d0 @ 100)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #15   55e8b035cfe0 i   resource:///org/gnome/shell/ui/screenShield.js:1203 (7efc9b6d8700 @ 163)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #16   55e8b035cf60 i   resource:///org/gnome/shell/ui/screenShield.js:1189 (7efc9b6d8670 @ 17)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #17   55e8b035ced8 i   resource:///org/gnome/shell/gdm/authPrompt.js:492 (7efc9b6fb3a0 @ 61)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #18   55e8b035ce50 i   resource:///org/gnome/shell/ui/unlockDialog.js:134 (7efc9b70ac10 @ 25)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #19   55e8b035cdd0 i   resource:///org/gnome/shell/ui/screenShield.js:1189 (7efc9b6d85e0 @ 46)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #20   55e8b035cd50 i   resource:///org/gnome/shell/ui/screenShield.js:541 (7efc9b6d5b80 @ 13)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #21   7ffc0913a500 b   resource:///org/gnome/gjs/modules/signals.js:135 (7efcb40c6040 @ 376)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: #22   55e8b035ccb0 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:169 (7efcb40d3e50 @ 39)
Feb 18 09:00:56 mathijs-at gnome-shell[2642]: JS ERROR: Extension unite@hardpixel.eu: Error: Argument 'actor' (type interface) may not be null
                                              init/Clutter.Actor.prototype.toString@resource:///org/gnome/shell/ui/environment.js:243:16
                                              registerHandler@/home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/handlers.js:54:20
                                              connect@/home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/handlers.js:71:12
                                              _init@/home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/window.js:329:7
                                              _init@/home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/extension.js:13:28
                                              enable@/home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/extension.js:39:18
                                              _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:148:13
                                              _enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:503:17
                                              _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:502:13
                                              _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:530:13
                                              _emit@resource:///org/gnome/gjs/modules/signals.js:135:27
                                              _sync@resource:///org/gnome/shell/ui/sessionMode.js:205:9
                                              popMode@resource:///org/gnome/shell/ui/sessionMode.js:174:9
                                              _continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:1203:13
                                              deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:1189:39
                                              finish@resource:///org/gnome/shell/gdm/authPrompt.js:492:13
                                              finish@resource:///org/gnome/shell/ui/unlockDialog.js:134:9
                                              deactivate@resource:///org/gnome/shell/ui/screenShield.js:1189:13
                                              ScreenShield</</<@resource:///org/gnome/shell/ui/screenShield.js:541:52
                                              _emit@resource:///org/gnome/gjs/modules/signals.js:135:27
                                              _convertToNativeSignal@resource:///org/gnome/gjs/modules/overrides/Gio.js:169:5
`

And after that the following lines keep appearing in the logs:
`Feb 18 14:30:38 mathijs-at gnome-shell[2642]: Object St.Label (0x55e8ab4fd140), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Feb 18 14:30:38 mathijs-at gnome-shell[2642]: == Stack trace for context 0x55e8a9f9b5a0 ==
Feb 18 14:30:38 mathijs-at gnome-shell[2642]: #0   55e8b21c1870 i   /home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/window.js:265 (7efc98c97ee0 @ 44)
Feb 18 14:30:38 mathijs-at gnome-shell[2642]: #1   55e8b21c17f0 i   /home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/window.js:273 (7efc98c97f70 @ 47)
Feb 18 14:30:38 mathijs-at gnome-shell[2642]: #2   55e8b21c1770 i   /home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/window.js:395 (7efc98c98820 @ 37)
Feb 18 14:30:38 mathijs-at gnome-shell[2642]: #3   7ffc0913a880 b   self-hosted:979 (7efc9b72f700 @ 440)
Feb 18 14:30:38 mathijs-at gnome-shell[2642]: == Stack trace for context 0x55e8a9f9b5a0 ==
Feb 18 14:30:38 mathijs-at gnome-shell[2642]: #0   55e8b21c1870 i   /home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/window.js:266 (7efc98c97ee0 @ 99)
Feb 18 14:30:38 mathijs-at gnome-shell[2642]: #1   55e8b21c17f0 i   /home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/window.js:273 (7efc98c97f70 @ 47)
Feb 18 14:30:38 mathijs-at gnome-shell[2642]: #2   55e8b21c1770 i   /home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/window.js:395 (7efc98c98820 @ 37)
Feb 18 14:30:38 mathijs-at gnome-shell[2642]: #3   7ffc0913a880 b   self-hosted:979 (7efc9b72f700 @ 440)
Feb 18 14:30:38 mathijs-at gnome-shell[2642]: st_label_get_text: assertion 'ST_IS_LABEL (label)' failed
Feb 18 14:30:38 mathijs-at gnome-shell[2642]: Object St.Label (0x55e8ab4fd140), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Feb 18 14:30:38 mathijs-at gnome-shell[2642]: st_label_set_text: assertion 'ST_IS_LABEL (label)' failed
Feb 18 14:31:32 mathijs-at gnome-shell[2642]: Object St.Label (0x55e8ab4fd140), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Feb 18 14:31:32 mathijs-at gnome-shell[2642]: == Stack trace for context 0x55e8a9f9b5a0 ==
Feb 18 14:31:32 mathijs-at gnome-shell[2642]: #0   55e8b31af900 i   /home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/window.js:265 (7efc98c97ee0 @ 44)
Feb 18 14:31:32 mathijs-at gnome-shell[2642]: #1   55e8b31af880 i   /home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/window.js:273 (7efc98c97f70 @ 47)
Feb 18 14:31:32 mathijs-at gnome-shell[2642]: #2   55e8b31af800 i   /home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/window.js:395 (7efc98c98820 @ 37)
Feb 18 14:31:32 mathijs-at gnome-shell[2642]: #3   7ffc0913a880 b   self-hosted:979 (7efc9b72f700 @ 440)
Feb 18 14:31:32 mathijs-at gnome-shell[2642]: st_label_get_text: assertion 'ST_IS_LABEL (label)' failed
Feb 18 14:31:32 mathijs-at gnome-shell[2642]: == Stack trace for context 0x55e8a9f9b5a0 ==
Feb 18 14:31:32 mathijs-at gnome-shell[2642]: #0   55e8b31af900 i   /home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/window.js:266 (7efc98c97ee0 @ 99)
Feb 18 14:31:32 mathijs-at gnome-shell[2642]: #1   55e8b31af880 i   /home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/window.js:273 (7efc98c97f70 @ 47)
Feb 18 14:31:32 mathijs-at gnome-shell[2642]: #2   55e8b31af800 i   /home/mathijs/.local/share/gnome-shell/extensions/unite@hardpixel.eu/window.js:395 (7efc98c98820 @ 37)
Feb 18 14:31:32 mathijs-at gnome-shell[2642]: #3   7ffc0913a880 b   self-hosted:979 (7efc9b72f700 @ 440)
Feb 18 14:31:32 mathijs-at gnome-shell[2642]: Object St.Label (0x55e8ab4fd140), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Feb 18 14:31:32 mathijs-at gnome-shell[2642]: st_label_set_text: assertion 'ST_IS_LABEL (label)' failed
`

Let me know if you need more information.

**Comment by BlackDex** [comment]
Oke, i worked a few days without an extra display/monitor attached, and i noticed it didn't happened.
So i guess it has something to do with dual monitors.

**Comment by jonian** [comment]
@BlackDex I have not been able to reproduce this on Arch Linux. Is the issue still present in gnome shell 3.36?

**Comment by BlackDex** [comment]
@jonian It doesn't happen to me either anymore. And that probably is because i'm not using the [Multi Monitors Add-On by spin83](https://github.com/spin83/multi-monitors-add-on.git) any more.

They probably clashed somewhere.
