### ISSUE TITLE
Unite with Gnome Shell 3.36

### ISSUE THREAD

**Issue by galen1423** [hardpixel/unite-shell#155]
Hello,

Thanx for this wonderfull extension.

With **Ubuntu  20.04** & **G.S 3.35.91**, unfortunately, **Unite** no longer work anymore...
`TypeError: controls.reparent is not a function`

**Comment by TheAifam5** [comment]
ArchLinux rolled the 3.36.0 out to public. Any update on this issue?

**Comment by Zeph33** [comment]
Replace in panel.js  `controls.reparent(this.container)` by this code
```javascript
    const parent = controls.get_parent();
    if (parent) {
        parent.remove_child(controls);
    }
    this.container.add_child(controls);    
```
No error but dash not visible :(

**Comment by jonian** [comment]
Thanks for the reports. I'm on Arch too. I will update and try to fix the issue soon.

**Comment by jonian** [comment]
I have pushed a fix in master branch. Can you try it and confirm that it works?

**Comment by TheAifam5** [comment]
It works on my machine ™

**Comment by Zeph33** [comment]
Same issue as with my code, dash no visible
This version of Dash To Dock work for me : 
[https://github.com/3v1n0/dash-to-dock/tree/gnome-3-36](https://github.com/3v1n0/dash-to-dock/tree/gnome-3-36)

**Comment by jonian** [comment]
@Zeph33 How is Dash to Dock related to unite?

**Comment by Zeph33** [comment]
Replace Unite by 3 extensions"Dash to Dock" "No title Bar" and "KStatusNotifierItem/AppIndicator Support". I have tested your fix with this 3 extensions disable but the dock is not visible, no crash, no error ...

**Comment by jonian** [comment]
@Zeph33 unite is not a replacement for "Dash to Dock" and "KStatusNotifierItem/AppIndicator Support". From those extensions unite can only replace "No title Bar".

**Comment by Zeph33** [comment]
I have a lot of extension, I mixed ... your screenshot show Dash to Dock
I am sorry

**Comment by jonian** [comment]
@Zeph33 no problem.

**Comment by pezz** [comment]
Even after updating gnome-shell this morning, Unite still worked for me without that code change.

The main issue I have at the moment is that tray icons aren't looking quite right.
![tray](https://user-images.githubusercontent.com/372177/76172563-8d0efd00-61eb-11ea-81de-4b3d5f1a7733.png)

**Comment by jonian** [comment]
@pezz please open a new issue. Thanks.

**Comment by pezz** [comment]
Done #156

**Comment by subliminal-one** [comment]
Hello,

Running Arch here and after the latest update it seems unite will only work in an X session.  In Wayland the error comes up is `unite_hardpixel.eu has error: TypeError: object is null`.  

Thanks

**Comment by subliminal-one** [comment]
It seems after launching an X session and rebooting and then going back to Wayland it's now working.  I guess this can be ignored.

**Comment by mind-blowing** [comment]
> I have pushed a fix in master branch. Can you try it and confirm that it works?

It works, thx!

**Comment by radiomike** [comment]
On Arch with 3.36 on Wayland and getting same error as subliminal-one. Journal excerpt for the error below.


```
JS ERROR: Extension unite@hardpixel.eu: TypeError: object is null
registerHandler@/home/radiomike/.local/share/gnome-shell/extension/unite@hardpixel.eu/handlers.js:59:9
connect@/home/radiomike/.local/share/gnome-shell/extensions/unite@hardpixel.eu/handlers.js:71:17
[_init@/home/radiomike/.local/share/gnome-shell/extensions/unite@hardpixel.eu/layout.js:76:20]
_init@/home/radiomike/.local/share/gnome-shell/extensions/unite@hardpixel.eu/extension.js:12:28
enable@/home/radiomike/.local/share/gnome-shell/extensions/unite@hardpixel.eu/extension.js:39:18
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:160:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:311:26
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:536:18
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:515:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:545:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:576:18
init@resource:///org/gnome/shell/ui/extensionSystem.js:54:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:244:22
start@resource:///org/gnome/shell/ui/main.js:138:5
@<main>:1:47

**Comment by jonian** [comment]
@subliminal-one, @radiomike I can reproduce the issue. I will push a fix soon. Thanks for the reports.

**Comment by jonian** [comment]
@subliminal-one, @radiomike the fix is available on master branch.

**Comment by subliminal-one** [comment]
@jonian working, thanks!
