### ISSUE TITLE
Tray Icons not being displayed correctly

### ISSUE THREAD

**Issue by pezz** [hardpixel/unite-shell#156]
Hey there,

Updated gnome-shell to 3.36.0 on Arch Linux this morning and have noticed that tray icons are being displayed a little strangely:

![tray](https://user-images.githubusercontent.com/372177/76172679-6a311880-61ec-11ea-935a-efca2654344d.png)

Icons with issues are apps like Hexchat, Discord and Slack.

Cheers.

**Comment by ashucg** [comment]
Happens on Fedora (gnome-shell 3.34.4) as well. I simply restart the shell (`ALT+F2` `r`) to fix it right now.

**Comment by TheAifam5** [comment]
On my side looks like this:
![image](https://user-images.githubusercontent.com/2192274/76212655-3fa18880-6209-11ea-93b9-bceb2a20d5f6.png)

**Comment by AmyangXYZ** [comment]
And my SKYPE is so big
![](https://amyang.xyz/uploadsfolder/Screenshot%20from%202020-03-10%2020-03-48.png)

**Comment by jonian** [comment]
Looks like this is an issue with gnome shell 3.36 and not with unite:

https://www.reddit.com/r/gnome/comments/ft14np/squashed_tray_icons_in_gnome_traditional_theme/  
https://github.com/zhangkaizhao/gnome-shell-extension-tray-icons/issues/8

Is anyone having this issue with unite v37 and gnome shell 3.34?

**Comment by printempw** [comment]
Before updating to GNOME 3.36, there's no such icon issue on my machine.

**Comment by jonian** [comment]
A fix is available in master branch. If anyone can test it, please report back. Thanks!

**Comment by pezz** [comment]
![unite-new](https://user-images.githubusercontent.com/372177/78176104-b3048600-74a7-11ea-8a27-cfb4ff1b223c.png)

The icon is whole but really big. It also seem to do something strange with the positions of other icons and the size of the top bar overall as well.

**Comment by jonian** [comment]
Thanks @pezz. What app is the one with the big X icon?

**Comment by pezz** [comment]
Hexchat IRC client.

**Comment by jonian** [comment]
@pezz I have pushed another fix for the icon sizing in master branch. When you test it, please report back. Thanks!

**Comment by pezz** [comment]
![unite-new2](https://user-images.githubusercontent.com/372177/78182150-5908be00-74b1-11ea-8ac1-5ea1efe28942.png)

Better, but a bit small and the tray icons seem squished together. Other gnome / non-tray icons are fine.

Thanks for working on this!

**Comment by jonian** [comment]
Thanks for helping @pezz.

The latest commit looks like this on my machine:

![Screenshot from 2020-04-01 23-32-14](https://user-images.githubusercontent.com/4119508/78184283-e0ced800-7471-11ea-818e-f8ca90335321.png)

The icons size is consistent with the other top-bar non-tray icons, except for discord that has a small icon by default (same size applied to all icons).

![Screenshot from 2020-04-01 23-34-30](https://user-images.githubusercontent.com/4119508/78184349-04921e00-7472-11ea-9272-fe2945403f69.png)

**Comment by freddyw** [comment]
Looks good here on my end as well with this patch (Fedora 32 (Beta))

**Comment by linkages** [comment]
Any guess when this will be available via extensions.gnome.org?

**Comment by pezz** [comment]
Are there any numbers in one of the js files I can tinker with?

The tray icons are much smaller than other gnome and extension icons for me.

**Comment by jonian** [comment]
@pezz Yes the icon size is at https://github.com/hardpixel/unite-shell/blob/master/unite%40hardpixel.eu/buttons.js#L36.

@linkages I will upload a new version tomorrow but it might take some time in review (lately reviews have been very quick).

**Comment by pezz** [comment]
@jonian - that's great, looks much better if I set mine to 28.

One last thing, is there anything I can do to increase the spacing between the tray icons? They're tightly packed. I tried playing with panel-status-indicators-box style in a customer stylesheet but it doesn't seem to affect it.

**Comment by jonian** [comment]
@pezz Add a custom class in https://github.com/hardpixel/unite-shell/blob/master/unite%40hardpixel.eu/buttons.js#L41:

```js
this._indicators = new St.BoxLayout({ 
  style_class: 'panel-status-indicators-box my-custom-class' 
})
```

```css
.my-custom-class {
  spacing: 20px !important;
}
```

**Comment by pezz** [comment]
Awesome, thanks very much for that!

Using spacing didn't seem to change anything no matter how high I put the value, I tried "padding: 4px" and it looks perfect now.

**Comment by TheAifam5** [comment]
I would say some icons are now seriously too small
![image](https://user-images.githubusercontent.com/2192274/78507633-8b503f00-7781-11ea-954c-9a00dcda1797.png)

the first icon should be as here:
![image](https://user-images.githubusercontent.com/2192274/78507645-9c00b500-7781-11ea-8d11-40f79b013543.png)

**Comment by jonian** [comment]
@TheAifam5 does this happen if you use the default shell theme and icon theme?

> also the sound icon is so small

Unite does not change the size of panel icons, only the tray icons. All your panel icons are smaller than they should be. Probably a theme or icon-theme issue.
