### ISSUE TITLE
Restoring a maximized window that handles titlebar results in double titlebar

### ISSUE THREAD

**Issue by Pshemas** [hardpixel/unite-shell#159]
Some apps (Firefox for example) have an option to remove titlebar built-in. Sadly it causes issues with this awesome extension. When I maximize such app, then restore it to window mode the result is double titlebar.
![unite_doubletitle](https://user-images.githubusercontent.com/6144330/77590322-c33bc480-6eed-11ea-9322-619bcbf9a3d0.jpg)

It would be awesome to see a fix for it (some extensions do not seem to have this problem, like gtk title bar, but lack other functions offfered by Unite) - even a blacklist option would do the trick.

**Comment by jonian** [comment]
The extension is already compatible with Firefox title-bar. Every time you change the title-bar setting in Firefox you have to restart your browser.

If it does not work, then it is bug or you are using a very old version of the extension.

**Comment by jonian** [comment]
Closing since this is already implemented.
