### ISSUE TITLE
Top bar Clock Font doesn't match the rest of the fonts

### ISSUE THREAD

**Issue by tiotrom** [hardpixel/unite-shell#162]
This is without the Unite extension : ![image](https://user-images.githubusercontent.com/34804533/77825295-96172e00-7108-11ea-82f9-a3685458dc30.png)

This is with the Unite extension:
![image](https://user-images.githubusercontent.com/34804533/77825317-b515c000-7108-11ea-887d-83be828b90cb.png)

The top bar font becomes larger and more round with the Unite extension. Shouldn't it not affect the font?

**Comment by tiotrom** [comment]
Maybe these screenshots are more conclusive:
![image](https://user-images.githubusercontent.com/34804533/77825339-dbd3f680-7108-11ea-831f-c048338d1984.png)
and
![image](https://user-images.githubusercontent.com/34804533/77825345-e9897c00-7108-11ea-9cdb-1b8dd56ccfe8.png)

**Comment by jonian** [comment]
Thanks for the report. Please provide unite and gnome shell versions.

Also try disabling `Apply system fonts to shell theme` in appearance settings.

**Comment by tiotrom** [comment]
Gnome shell 3.36 and Unite version latest from here https://extensions.gnome.org/extension/1287/unite/. 

> Also try disabling Apply system fonts to shell theme in appearance settings.
I tried. Same. But I think the main thing it does is to increase the font size of the clock...

**Comment by jonian** [comment]
Thanks for reporting back @tiotrom. Also try disabling `Reduce top bar items spacing` in appearance settings.

**Comment by tiotrom** [comment]
Ok I tried but it doesn't make any difference...

**Comment by jonian** [comment]
Those two settings, `Apply system fonts to shell theme` and `Reduce top bar items spacing`, are the only things that apply font changes.

I can't reproduce this issue, so I can't help you. You can also try the latest version from master branch that does not apply any font changes on gnome-shell 3.36.

**Comment by tiotrom** [comment]
Ok i think I got it, it is the " Reduce top bar items spacing" option that makes the clock font bigger. But disabling that, makes the indicator icons too crowded. Can you make it so this option doesn't affect the clock font? Cheers!

**Comment by jonian** [comment]
> Can you make it so this option doesn't affect the clock font?

@tiotrom this is already done in master branch. You can install it manually or wait for a new version.

**Comment by tiotrom** [comment]
Thank you very much!

**Comment by tiotrom** [comment]
The last update fixes the issue, Thank you!

**Comment by jonian** [comment]
Thank you for reporting @tiotrom.
