### ISSUE TITLE
Packed top right icons after reboot, fix after move cursor on them

### ISSUE THREAD

**Issue by hotmule** [hardpixel/unite-shell#163]
Gnome 3.36, last version of Unite

**Comment by jonian** [comment]
Which icons? Please provide a screen-shot and the output of `journalctl /usr/bin/gnome-shell | grep unite`. Thanks.

**Comment by jonian** [comment]
@hotmule commit https://github.com/hardpixel/unite-shell/commit/a4121e35d2a39cbc542e12a11435269c9e493154 added a fix for panel icons spacing not applied until mouse-over on gnome shell >= 3.34. Can you confirm if it fixes this issue?

**Comment by hotmule** [comment]
If last commit was in version 39 - issue is still here
![Screenshot from 2020-04-03 17-02-26](https://user-images.githubusercontent.com/37577810/78369394-c873d000-75cd-11ea-9985-a83560f314eb.png)

**Comment by jonian** [comment]
@hotmule it is not in v39. You have to install it manually from master branch.

**Comment by hotmule** [comment]
![Screenshot from 2020-04-03 17-24-57](https://user-images.githubusercontent.com/37577810/78371120-33260b00-75d0-11ea-9bb3-80ed9b3cde51.png)
Nope, still here

**Comment by jonian** [comment]
@hotmule, @jwarkentin I can't reproduce this. Can you try with default theme, icon-theme and only unite enabled?

I looks like there are issues with some extensions and custom themes:
https://www.reddit.com/r/gnome/comments/g092i1/gnome_336_lockscreen_and_top_bar_icons_issues/

**Comment by hotmule** [comment]
I think it is because of "Reduce top bar items spacing" feature, I have weird behavior of icons in top bar after off/on this setting, similar to that packed icons issue

**Comment by jonian** [comment]
I can't reproduce this and it is an issue in gnom-shell, as reported [here](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1708).

This extension has a fix [here](https://github.com/hardpixel/unite-shell/blob/master/unite%40hardpixel.eu/layout.js#L230) which might not be reliable and there is nothing I can do about it. Sorry :(.

**Comment by jonian** [comment]
@hotmule I think I might have fixed this issue. Can you, please try the latest version from master branch?

Also, please provide the output of `journalctl /usr/bin/gnome-shell | grep unite`. Thanks!
