### ISSUE TITLE
[Feature Request] Allow centering title, moving clock left and placing window buttons immediately to the right of window title

### ISSUE THREAD

**Issue by jwarkentin** [hardpixel/unite-shell#164]
Title says it all. I would LOVE to be able to have the title centered to match the look of things like VSCode and my shell window title. I also really want to be able to make the window buttons stick next to the title (preferably on the right).

My primary goal is having a more easily accessible window close button which means centering it to place the buttons closer to my mouse at any given time; but then it would look weird next to the clock. Swapping the clock and title seems like it would actually be better all around, as long as I could also keep the window buttons with the title.

**Comment by jonian** [comment]
Hi @jwarkentin, thanks for the report. These features are out of the scope of this extension and will need a lot of work to implement. So this is a won't fix issue. Sorry.
