### ISSUE TITLE
Hide titlebar on WINE apps

### ISSUE THREAD

**Issue by fefifofum** [hardpixel/unite-shell#168]
Ubuntu 20.04

When I maximize a WINE app, titlebar is not hidden. I think this wasn't an issue before I updated from Ubuntu 18.04. I tested also with latest git version, same result. Other than that, this extension is working great! Thanks!

**Comment by jonian** [comment]
Hi @fefifofum, thanks for the report. Is this issue on wayland, xorg or both?

**Comment by fefifofum** [comment]
This is with xorg, I didn't try with wayland.

**Comment by jonian** [comment]
@fefifofum Are you referring to mutter titlebars or windows titlebars? Can you upload a screenshot? Thanks!

**Comment by fefifofum** [comment]
I guess windows titlebars. Here is a [screenshot](https://ibb.co/ysF649m).

**Comment by jonian** [comment]
I'm closing this issue and opened #183, as this happens with other apps too.
