### ISSUE TITLE
window menu is seen on lock screen

### ISSUE THREAD

**Issue by cmm** [hardpixel/unite-shell#172]
The window menu (the one on the left side of top bar, might be config-dependent?) is seen on the Gnome (GDM?) lock screen, regardless of Gnome privacy settings.  That's not very secure.

**Comment by jonian** [comment]
Hi @cmm, thanks for the report. Please provide distro, gnome, extension version info and the output of `journalctl /usr/bin/gnome-shell | grep unite`.

**Comment by cmm** [comment]
aaaaand of course it doesn't reproduce any more and I forgot on which of the two laptops on my desk I've seen it...
sorry about the noise I guess, I'll reopen with more details if/when it happens again.
