### ISSUE TITLE
Hide window titlebars maximized not working ubuntu 20.04

### ISSUE THREAD

**Issue by kauanmocelin** [hardpixel/unite-shell#173]
After update Ubuntu 18.04> 20.04, the problem occurs. Whenever I open a program first time and maximized it the window title bars still visible, so I close program and open it again for title bar are hidden.

I use extension called "Auto Move Windows", the problem only occurs if I open a program in a workspace that is not configured to auto move extensions. Ex. Chrome configured to open in a workspace number 1, if I go to workspace number 3 and open Chrome the problem occurs.

Unite > Hide window titlebars > Maximized

Gnom shell version: 3.36.1
Unite version: 40
Ubuntu version: 20.04

**Comment by wxq851685279** [comment]
Same problem
