### ISSUE TITLE
Status Menu underline shifted down when using Unite + Window List

### ISSUE THREAD

**Issue by Magean0** [hardpixel/unite-shell#179]
Hey,

I've a very minor niggle to mention: when using both Unite and (the official Window List extension)[https://extensions.gnome.org/extension/602/window-list/] (the one used in GNOME Classic), the underline that appears when clicking on the Status Menu is shifted downward: [this is how it looks like](https://imgur.com/4C2KcrR), and [how it should look like](https://imgur.com/rWLOQt8). Notice that the blue underline is off by a couple pixels, and appears on the maximized window's content.

Steps to reproduce:
-enable both Unite and Window List
-restart the shell
-maximize a window and focus that window
-open the Status Menu

This doesn't happen when using either extension alone.

Of course, Window List may be the one to blame.

**Comment by jonian** [comment]
Hi @Magean0, I cant reproduce this on:

- Distro: Arch Linux
- Gnome Shell: 3.36
- Unite: v41

Please provide info for the above, thanks!

**Comment by Magean0** [comment]
Sorry for the missing information, I'm still noticing this thing on:

Ubuntu 20.04 (up-to-date)
GNOME Shell 3.36.2
Unite: v41 (latest from the official platform)
Window List: v31 (latest from the official platform)

Not a big problem, of course.
