### ISSUE TITLE
Does not work for JavaFX applications (even for the very basic Hello World window)

### ISSUE THREAD

**Issue by HubKing** [hardpixel/unite-shell#180]
Ubuntu 20.04, OpenJDK 14, OpenJavaFX 14. I created a simple Hello word app with JavaFX, and maximised its window. The title bar did not go away. I wonder if this can be fixed.

![image](https://user-images.githubusercontent.com/10900489/81034702-0157db00-8ed3-11ea-9b52-816b4441cddf.png)

If you need a JavaFX application to test with, you can download one from http://download.oracle.com/otndocs/products/javafx/8/samples/Ensemble/Ensemble.jar
And you can install JavaFX from
https://gluonhq.com/products/javafx/
And run a JavaFX jar by following the instructions 
https://openjfx.io/openjfx-docs/#install-javafx

**Comment by eugene-rom** [comment]
Same for wine apps in Ubuntu 20.04.

**Comment by jonian** [comment]
Hi @HubKing, thanks for the report. I'm closing this issue and opened #183, as this happens with other apps too.
