### ISSUE TITLE
Support for Yaru Dark theme

### ISSUE THREAD

**Issue by JoelFeiner** [hardpixel/unite-shell#181]
The extension currently supports the regular Yaru theme, but does not support the Yaru Dark theme. If I select Yaru for the window button style, it causes my actual shell theme to oscillate between Yaru and Yaru Dark. Even if the theme isn't supported, it still shouldn't cause my shell theme to change.

**Comment by jonian** [comment]
Hi @JoelFeiner, thanks for the report.

Yaru and Yaru-dark themes use the same icons for window controls, so there is no need for a separate theme for yaru-dark.

> Even if the theme isn't supported, it still shouldn't cause my shell theme to change.

Unite extension, does not change the shell theme in any way. You can use any gtk/shell theme with any window-buttons theme provided by unite.
