### ISSUE TITLE
Inverting buttons order

### ISSUE THREAD

**Issue by maciejfikus** [hardpixel/unite-shell#184]
Hi guys, I re-posting someone's suggestion from gnome extensions:

> Just one more thing (as also pointed out by ecceccecc): It'd be nice to have the option of inverting the order of min/max/close, so that the very top left pixel of the screen corresponds to the 'close' action. (That is, if I choose to put the window buttons in the left corner.)
Maybe this behavior should even be the default if the buttons are put on the left side: If I use "Tweaks" to switch between left and right position for the window buttons of non-maximized windows, the "close" button is always the outer button! In that sense, Unite's current behavior is at odds with Gnome's general behavior.

Gnome shell is pretty much right-oriented when it comes to window buttons, which is even more visible in recent releases. Not sure if this is a bug, but right now many core apps like gnome-settings are broken if you choose to stick with left-side buttons, it just doesn't cooperate well with sidebars. Another example would be gnome-tweaks which is simply broken (https://gitlab.gnome.org/GNOME/gnome-tweaks/issues/245). 

As long as I have Unite extension, it seems acceptable to switch to right side buttons as I do not really use them anyway, and atleast UI doesn't suffer then. In the same time, Unite window buttons also change order so that close button isn't in the top left corner anymore. It would be perfect to customize placement of these buttons and make them more independent from shell settings (optionally). 

Cheers!

**Comment by jonian** [comment]
Hi @maciejfikus, unite already has a setting for window buttons placement in `Appearance` tab. The available options are `auto`, `first`, `last`, `left`, `right`.

Maybe I'm not understanding something?

**Comment by jonian** [comment]
@maciejfikus, please try the master branch. The issue that prevented reversing window buttons order is fixed.

**Comment by maciejfikus** [comment]
Hey @jonian, thanks for this patch. It works, but some weird spacing appeared.

![image](https://user-images.githubusercontent.com/24628237/82491516-06c54000-9ae5-11ea-9ae5-18cf48f3cf17.png)

**Comment by jonian** [comment]
Yep that's weird. Is the space there if you restart the shell?  
What is the output of `dconf read /org/gnome/desktop/wm/preferences/button-layout` ?

**Comment by maciejfikus** [comment]
Output: `':minimize,maximize,close'`

There is no space after re-log, however it appears as soon as I restart shell by `alt+f2` + `r`.
