### ISSUE TITLE
Can't lock computer while enable this extension.

### ISSUE THREAD

**Issue by plumlis** [hardpixel/unite-shell#185]
This is a weird issue.

I use my thinkpad X1 Carbon with thunderbolt3 dock, and two monitors connected.

When I keep this extension enabled, I can't lock my laptop, Gnome-shell will crash and autostart again.

I checked log file but with no luck,  can only find this maybe relate to this problem.

`gnome-shell[9881]: segfault at 280 ip 00007f679952b252 sp 00007fffbeeafab0 error 4 in libst-1.0.so`
`(EE) client bug: timer event11 debounce short: scheduled expiry is in the past (-6ms), your system is too slow`

I tried many ways to reproduce this issue.

Extension Disabled , Thunderblot3 Dock connected with two monitors, Try to lock  ->  OK
Extension Enabled , Thunderblot3 Dock connected with two monitors, Try to lock  -> Crash
Extension Disabled , Thunderblot3 Dock connected with two monitors, Login to system and Enable extension , Try to lock  -> OK
Extension Disabled , Don't use Dock,Try to lock -> OK
Extension Enabled,，Don't use Dock , Try to lock -> OK

I'm not sure if this issue is this extension related, But the truth is after I disable it, Lock is working well.

Weird

**Comment by jonian** [comment]
Hi @plumlis, thanks for the report. I can't debug you issue because I don't have a Thunderblot3 Dock. Can you try to disable all the unite features and test them one by one? This will help to identify the feature that causes the issue, since there is no error in the logs.

You can try with the decorations feature first, as it uses an external program, `xprop`.

**Comment by plumlis** [comment]
Thankyou for your reply!

I tried as you said.

And found the problem is "Restrict functionalities to the primary screen"

I disabled it and I can lock my laptop successfully.
