### ISSUE TITLE
[not a bug] Modify Clock placement (keep it centered)

### ISSUE THREAD

**Issue by stheid** [hardpixel/unite-shell#186]
Maybe this is a stupid question, but is it possible to configure that the clock stays in the center with this extension enabled? The Readme and the config menu give me the feeling this is not the case.

i dont think it is related to #70, #41 or #90  as this seems to be the intended behaviour. Maybe this is a feature request. Any workarrounds would be welcome as well.

**Comment by jonian** [comment]
Hi @stheid, to keep the clock centered "Extend left box" setting should be off.

**Comment by stheid** [comment]
Thanks a lot for the lightning fast reply. Maybe consider to renaming this option or place a hint in the Readme, that this feature can be turned off.
