### ISSUE TITLE
Conflict issues between this plugin and the multi-monitors extension

### ISSUE THREAD

**Issue by rick-pri** [hardpixel/unite-shell#19]
This may be a wontfix situation but I'm using both of these extensions (multi-monitor [here](https://github.com/spin83/multi-monitors-add-on)) because I want the time at the top of every window although I prefer your placement over to the right a al unity's shell, and I'd like the functionality that I can get with both of these extensions on the primary monitor across my other two monitors.

I'm on Xorg, Gnome 3.26.1 on Ubuntu 17.10.

**Comment by Jhackler** [comment]
would love this in multi monitor as well

**Comment by rick-pri** [comment]
I don't know if that is the better place to make the request.  I like unite-shell for much more than that though, however, I've had to do without it for quite some time now (now on Ubuntu 19.10 so now almost two and a half years on).  I've not tried `unite-shell` again since to test what it's currently working like.

I guess it's still not working correctly because of all the thumbs ups over the years.  Given that multi display working is _de rigueur_ these days I'm constantly surprised by the lack of development in this area by FOSS; the Gnome development is very much at fault here as they should be already handling the multi-monitor stuff themselves, they should be multi-monitor first, rather than foisting it onto a 3rd party (it's a bit like sticking to single process blocking (synchronous) execution these days).

**Comment by jonian** [comment]
@rick-pri I do not use multiple monitors very often, so this is not something I will work on. You can make a PR if you want this implemented.

**Comment by rick-pri** [comment]
I find this very strange @jonian .  I've been using multiple monitors for over a decade, I find using only a single monitor so restrictive and such a compromised desktop user experience that I don't even like to use my laptop unplugged, and since most of the company that I work at are reporting that they are similarly struggling now that they are having to work from home with a single screen, I'd suggest that you give it a concerted try :wink: :grin: 

As I understand it, these modules are just javascript under the hood?  I might take a look.  It's really not a language suited to my personal tastes but I'm making a react front end for a small project at the moment so I can at least have a look.

**Comment by jonian** [comment]
Extension seems to have stopped development.
