### ISSUE TITLE
Titlebar Buttons and Top Panel Buttons Same Theme

### ISSUE THREAD

**Issue by dsreyes1014** [hardpixel/unite-shell#190]
Is it possible to maybe have "Default" use the same theme being used for gtk applications/gnome shell as far as the titlebar buttons go?  To keep the theme cohesive with gnome shell/gtk applications.

**Comment by jonian** [comment]
Hi @dsreyes1014, it is possible to detect current GTK theme and match the buttons theme. Maybe an "Auto" option can be added, since "Default" is theme agnostic and matches the styles of the other icons in top panel.

**Comment by sanwablo** [comment]
> Hi @dsreyes1014, it is possible to detect current GTK theme and match the buttons theme. Maybe an "Auto" option can be added, since "Default" is theme agnostic and matches the styles of the other icons in top panel.

Is it "possible" for developers or current users? The "Auto" option would be amazing.

**Comment by smalltimer** [comment]
+1 from me! Definitely would be an awesome enhancement to this already fantastic extension.
