### ISSUE TITLE
Ubuntu Software (Snap Store app) double window bottom

### ISSUE THREAD

**Issue by edurojasr** [hardpixel/unite-shell#191]
Hi thanks for this extension!

I'm new to gnome and this extension really make it feel great, just want to point that the Ubuntu Software app (snap store) shows double window bottoms

![Screenshot from 2020-08-15 18-05-27](https://user-images.githubusercontent.com/35645729/90323711-4227ad00-df22-11ea-8f9b-b4384e4a1adb.png)

thanks!

**Comment by jonian** [comment]
Hi @edurojasr, thanks for the report. Unite hides window buttons from headerbars using css, which is not possible for applications installed with snap/flatpak. Is Ubuntu Software installed as a snap?

Also, when you first enable the extension, you should kill all open applications for the css to take effect, or logout and re-login.

**Comment by edurojasr** [comment]
hi @jonian 
Indeed Ubuntu Software is now the Snap Store that it is a snap itself. I have read Unite does not work with snaps apps but I have others snaps and the extension works great. This is the list of my apps installed as snaps:

![Screenshot from 2020-08-29 12-29-05](https://user-images.githubusercontent.com/35645729/91643771-6f309100-e9f3-11ea-81c2-352902510444.png)

And here are some examples of this snaps working great with Unite:

![Screenshot from 2020-08-29 12-33-16](https://user-images.githubusercontent.com/35645729/91643846-0ac20180-e9f4-11ea-9c64-97b6169637c8.png)

![Screenshot from 2020-08-29 12-33-26](https://user-images.githubusercontent.com/35645729/91643857-1ca3a480-e9f4-11ea-87cc-230ac90b0652.png)

![Screenshot from 2020-08-29 12-34-41](https://user-images.githubusercontent.com/35645729/91643847-10b7e280-e9f4-11ea-8b43-22a10cbdc803.png)

![Screenshot from 2020-08-29 12-34-26](https://user-images.githubusercontent.com/35645729/91643865-25947600-e9f4-11ea-90de-caa3a35a330f.png)

So thats for me its a little weird that for the apps in snaps works great, but for the snap store its self does not work.

**Comment by jonian** [comment]
Firefox and VS Code use SSD (Server Side Decorations). Unite supports all applications that use SSD even if they are installed with snap/flatpak since there is no css required to hide de decorations.

Software Store uses CSD (Client Side Decorations). These applications require css to hide the window buttons and unite does not support them if they are installed with snap/flatpak.

Maybe I should add this in the readme, since many users have reported similar issues.

**Comment by edurojasr** [comment]
I see, yes all of my snap that I list above works great, I suppose that all of them use SSD

Good idea add the explanation to the README since the snaps that use SSD are supported, maybe like a disclaimer about snaps, the user can expect that some snaps work and other not and that depend of the snap implementation of the decorations

thanks @jonian

**Comment by jonian** [comment]
Closing this, I will add a readme section for this and other issues/workarounds when I have some free time.
