### ISSUE TITLE
On Ubuntu 20.04 clock appears to get pushed to the right to the point of being partially visible or not visible

### ISSUE THREAD

**Issue by arooni** [hardpixel/unite-shell#192]
Example

![image](https://user-images.githubusercontent.com/556667/91210072-4a29de80-e6d2-11ea-82dd-3f7f4659e84c.png)

or

![image](https://user-images.githubusercontent.com/556667/91210115-5615a080-e6d2-11ea-9e3c-151ea4850678.png)

ideas?

**Comment by jonian** [comment]
Hi @arooni, unite does not move the clock to the right of the status area. Do you use any extension for that? Also, could you provide a screenshot that shows the full top bar?

**Comment by jonian** [comment]
Closing due to no response.

**Comment by arooni** [comment]
i realize i hadn't replied in ages.  here's the total topbar

![image](https://user-images.githubusercontent.com/556667/107101826-25d44100-67de-11eb-8f29-b249df04a0c9.png)

**Comment by arooni** [comment]
i don't recall using a different extension to move the clock.  here are all of my extensions

![image](https://user-images.githubusercontent.com/556667/107101872-4ef4d180-67de-11eb-9b91-15a7d6dc48f8.png)

![image](https://user-images.githubusercontent.com/556667/107101902-5c11c080-67de-11eb-9d36-66bd212b32b8.png)

![image](https://user-images.githubusercontent.com/556667/107101925-6df36380-67de-11eb-8170-ec0eb6447620.png)

**Comment by jonian** [comment]
I don't know how your clock is on the right side of the top panel. Unite does not move the clock. Dash to Panel is an extension that allows you to move the clock but is looks disabled in your screenshots.

**Comment by arooni** [comment]
Your suggestion was perfect!  Many thanks!  That extension + unite is the perfect combo.  Love the clean, functional interface.  Many thanks for your help and patience.
