### ISSUE TITLE
Don't separate battery icon and manually enabled battery percentage

### ISSUE THREAD

**Issue by BjoernDaase** [hardpixel/unite-shell#195]
The separation of the menu items in the top bar is very good and makes things way easier to read.

Unfortunately, it also separates the battery icon the manually enabled battery percentage. From my point of view, this looks a bit weird as I would stay they are one content item:

![image](https://user-images.githubusercontent.com/24682367/91638235-16babd00-ea0e-11ea-8fd8-8021d1baee69.png)

Therefore, I would suggest to not add spacing between those two.

**Comment by jonian** [comment]
Hi @BjoernDaase, thanks for the report! This looks like a bug, grouped indicators in status area should have smaller spacing between them. I will submit a fix soon.

**Comment by BjoernDaase** [comment]
Great, thanks a lot @jonian for that super fast fix!
