### ISSUE TITLE
more monitor support not the best

### ISSUE THREAD

**Issue by zsoltii** [hardpixel/unite-shell#2]
When use on more monitor, the application which is on the second monitor the window control buttons on the first monitor.

See the attached screenshot. ![kepernyokep errol 2017-09-05 09-10-55](https://user-images.githubusercontent.com/8914013/30049367-acf560c6-921a-11e7-8e39-6052048581e1.png)
The application on the right monitor, windows controll button on the left monitor.

I don't know which will be the best solution.
Maybe, on that monitor which is not the main monitor, the application will work normal mode with unity menu support.

I love your extension, good work :)

**Comment by tewald** [comment]
Unity shows the main bar on all monitors, so I think there's 2 ways of solving this:
1. Extend the main bar to all monitors, not only the primary one, and show the buttons only on the correct bar;
2. Check if the focused windows is on the primary monitor and keep the window titlebar and buttons visible accordingly.

My 2 cents.

**Comment by olibia** [comment]
Thanks for reporting this issue.
Currently, there is no multi monitor support, but it is on our to-do list.
We will probably add settings in order to choose the desired behavior.

**Comment by franglais125** [comment]
@olibia Great extension. If you find it useful, check out my fork of Pixel Saver: https://github.com/franglais125/no-title-bar

I included multi-monitor support, and many other options, plus bug fixing. You can have a working prefs.js and GUI :).

**Comment by olibia** [comment]
Hi @franglais125, thanks! I've seen your extension too, it's realy good.

Thank you for letting me know I can have a look, I probably will as soon as we decide to add settings and multi-monitor support.

**Comment by cbowman57** [comment]
Just a modification I made to stylesheet.css so I could substitute my own icon for the activities button without having to resize the icon.

#panel #panelActivities {
  width: 55px; }
  #panel #panelActivities > * {
    background-color: transparent;
    color: transparent;
    background-image: url("assets/activities.svg");
    background-position: center;
    **_background-size: contain; }_**

**Comment by jonian** [comment]
@zsoltii, @tewald this is the current behaviour for multiple monitors:

- Window decorations are not removed for windows not in primary monitor.
- Window buttons are hidden for windows not in primary monitor.
- App menu shows app name for windows not in primary monitor.

Window decorations work only on Xorg. Support for Wayland will be tracked on issue #14.
