### ISSUE TITLE
Firefox 82's close/minimize/maximize buttons are not hidden

### ISSUE THREAD

**Issue by dgutov** [hardpixel/unite-shell#201]
Starting with version 82, it seems to have two modes: with and without titlebar (controlled via a checkbox in the Customize interface). In neither mode Unite manages to recognize and hide those buttons, however.

I've just upgraded to 82 (developer edition), so I saw it today for the first time.

**Comment by dgutov** [comment]
As a result Firefox ends up with two sets of those buttons: one inside the window, and another on the top panel.

**Comment by jonian** [comment]
Hi @dgutov, thanks for the report. After toggling "Title Bar" in customize, you should restart firefox. Is the issue present after restarting?

**Comment by dgutov** [comment]
Oh. That fixed it!

I tried disabling-enabling the extension, but that did not do the trick.

It's great that another way exists. Thanks a lot!

And many thanks for this indispensable extension. :+1:

**Comment by thunderface88** [comment]
Why

**Comment by yogesmhrj** [comment]
Hi, actually the issue is still prevalent on Firefox 92 with Unite v55. If somebody can post a solution for this. This would be really helpful.

![image](https://user-images.githubusercontent.com/13461608/133224695-d884f1c7-fb11-4fe4-bc99-f40525f35ee0.png)

**Comment by jonian** [comment]
@yogesmhrj check https://github.com/hardpixel/unite-shell/issues/239#issuecomment-823856544
