### ISSUE TITLE
Don't remove window buttons for GTK apps

### ISSUE THREAD

**Issue by dobroweb** [hardpixel/unite-shell#202]
Please add option for don't remove window buttons for GTK apps like it's done in [GTK Title Bar extension](https://github.com/velitasali/GTKTitleBar)
Now it's look like:
![image](https://user-images.githubusercontent.com/11454622/94116074-fee72500-fe63-11ea-8397-cad140d9d860.png)
Settings:
![image](https://user-images.githubusercontent.com/11454622/94116120-0b6b7d80-fe64-11ea-95cd-658210bf6f3c.png)
[This has already been requested before](https://github.com/hardpixel/unite-shell/issues/101)

**Comment by MikeStutzzzz** [comment]
This is a good Idea I ended up installing GTK Title bar, would be nice to have it all in one app
