### ISSUE TITLE
[Feature request] Add "Hide top bar" functionality

### ISSUE THREAD

**Issue by FastThenLeft** [hardpixel/unite-shell#205]
LOVE this extension. I recommend it to all my friends.

Since it's doing so much with the top bar already, it would make sense to add "hide top bar" functionality and that would be one less extension to load.

**Comment by Leleat** [comment]
I've implemented this feature in my own extension https://github.com/Leleat/simple-task-bar

The way I did it:
- shrink the panel to 2 px and set the the opacity to 0
- add a black bar of 2 px to mask the desktop wallpaper

This way I kept the functionality of the panel (hot corners, notification and system dropdown and window buttons). If this is an accecptable workaround to "hide the top bar", I can open a PR @jonian.

**Comment by jonian** [comment]
Closing as I will not implement this. The "hide top bar" extension [here](https://github.com/mlutfy/hidetopbar) is very good and well maintained. Having many extensions is not a problem and the goal of this extension is not to replace others.

Thanks @Leleat for willing to help.
