### ISSUE TITLE
Incorrect applications names

### ISSUE THREAD

**Issue by ilyaryabikin** [hardpixel/unite-shell#206]
Hi.
For some reason applications names are shown as "Unknown" when the option "Show window title in app menu" is set to "Never".

![Screenshot from 2020-10-06 04-00-53](https://user-images.githubusercontent.com/42956521/95147162-a0397980-0788-11eb-9d71-d80328c236cb.png)

I'm running Arch Linux with Gnome 3.38 and the latest version(43) of Unite extension. I tried different versions of the extension and different options of installing it, tried to wipe all local cache and Gnome settings, but still no positive result. I've faced with this problem on Gnome 3.36 too.

Here is the list of activated extensions:

![image](https://user-images.githubusercontent.com/42956521/95147454-703ea600-0789-11eb-9fa4-3054914e1c70.png)

And my settings of Unite:

![image](https://user-images.githubusercontent.com/42956521/95147487-93695580-0789-11eb-810d-24ff4a9f23ad.png)
![image](https://user-images.githubusercontent.com/42956521/95147496-9c5a2700-0789-11eb-9530-f13f33b7a411.png)

I don't know if this problem is somehow connected with my system or the extension itself, but it's kind of annoying. Any help will be appreciated. Thanks.

**Comment by jonian** [comment]
Hi @ilyaryabikin, I have the same setup as you (Arch, Gnome 3.38) and tested with the same extensions and settings, but I can't replicate the issue.

**Comment by ilyaryabikin** [comment]
I just figured out that this problem occurs only during the Wayland session. Are you setting X11 by default?

**Comment by jonian** [comment]
Yes, I was on X11. I can confirm that the issue is present on Wayland.

**Comment by KonstantMan** [comment]
I checked again and again that I'm on xorg but unfortunately the bug remains

**Comment by ceiphr** [comment]
I'm still having this issue. v43 of Unite. Ubuntu 20.10 Wayland.

**Comment by jonian** [comment]
@KonstantMan, @ceiphr the issue is fixed on master branch and is not available in the latest version. I will release a new version today.
