### ISSUE TITLE
[Feature] Use GTK Window button theme from themes

### ISSUE THREAD

**Issue by NovaViper** [hardpixel/unite-shell#207]
Hi, I just started using Gnome with the Dracula GTK theme and noticed that the extension does not detect the theme's window button icons. hence breaking the unified feel that the theme offers. I wish that the extension has the ability to use the window decorations that whatever theme I install.

Here's some links to the theme:
https://draculatheme.com/gtk
https://github.com/dracula/gtk

**Comment by sanwablo** [comment]
I'm using [Yaru Colors](https://github.com/Jannomag/Yaru-Colors/releases) and it would be great to have this feature developed, if it's not too much to ask!

**Comment by sanwablo** [comment]
@NovaViper there is an enhancement request [here](https://github.com/hardpixel/unite-shell/issues/190).

**Comment by jonian** [comment]
Closing this, the "Auto" option mentioned in #190 has been implemented. Getting the window buttons from the GTK theme is not possible. 

If unite does not have a buttons theme to match your GTK theme, submit a PR to include it or add your custom theme in `~/.local/share/unite-shell/themes`. You can check [here](https://github.com/hardpixel/unite-shell/tree/master/unite%40hardpixel.eu/themes) the structure of a theme.
