### ISSUE TITLE
Hide Window Titlebars Not Working With Flatpak Apps

### ISSUE THREAD

**Issue by dsreyes1014** [hardpixel/unite-shell#210]
When selecting `Hide window titlebars` `Maximized` with flatpak apps nothing happens.  Is there a way to get this working with flatpak apps?

**Comment by dsreyes1014** [comment]
Nevermind.  Sorry.  This works when enabling the `User Themes` extension.

**Comment by Froggy232** [comment]
Hi,
I try to make unite work with flatpak without success.
Can you detail the step you did?
I tried to enable user theme extension, but it didn't change anything.
Thanks you

**Comment by uohmak4fvpqe** [comment]
I have the same issue and I already have the user theme extension on

**Comment by jonian** [comment]
@uohmak4fvpqe try the solution in https://github.com/hardpixel/unite-shell/issues/303#issuecomment-1193269456.
