### ISSUE TITLE
No signal 'allocate' on object 'Gjs_ui_panel_Panel'

### ISSUE THREAD

**Issue by morfyum** [hardpixel/unite-shell#213]
On Fedora 33 with gnome 3.38 - Wayland.
Error: No signal 'allocate' on object 'Gjs_ui_panel_Panel'
I cant enable because show this... 
Impossible to use over some fedora release. 

xorg-x11-utils is installed, but im using Wayland. :cry: 

Unite version:   8-8.fc33

**Comment by jonian** [comment]
@morfyum you are using a very old version (8) that is not compatible with gnome 3.38. Please install the latest version (44).
