### ISSUE TITLE
[Feature request] Add a toggle to disable top bar desktop name text

### ISSUE THREAD

**Issue by Rodancoci** [hardpixel/unite-shell#214]
Currently I am using Unite along with an extension called 'Dash to Panel' which merges the GNOME Dash with the top bar.

They work great together except for a small detail: when I go to the desktop (e.g. by hiding all windows) the desktop name in the top bar shifts my icons to the right, even if I set the top bar desktop name to an empty string.

Top bar with Firefox open:
![image](https://user-images.githubusercontent.com/11667577/99487590-722d8480-2945-11eb-892a-decdcb140271.png)

Top bar with everything minimized and top bar desktop text set to empty string:
![image](https://user-images.githubusercontent.com/11667577/99487628-8b363580-2945-11eb-8f3a-45f2a925ad89.png)

It would be nice if there were a toggle for the top bar desktop name text or if setting the text to an empty string disabled the feature altogether.

**Comment by jonian** [comment]
Hi @Rodancoci, there is a toggle to disable desktop name in "General" settings tab.

**Comment by Rodancoci** [comment]
So there is! Can't believe I missed that. Thank you!
