### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by mzanetti** [hardpixel/unite-shell#216]
Yesterday I got a notification that an update for this extension is available. I tried to install and it always fails, just showing "Error". 

Ubuntu 20.04 focal, no other extensions installed except the Ubuntu preinstalled ones.

**Comment by ddehart** [comment]
Same for me. Removing the extension through https://extensions.gnome.org/local/ and adding it again doesn't resolve the issue

**Comment by henryhinze** [comment]
Same for me. Also on Ubuntu 20.04.

**Comment by ddehart** [comment]
> Same for me. Removing the extension through https://extensions.gnome.org/local/ and adding it again doesn't resolve the issue

Removing the extension, restarting, and then adding it again seems to have fixed it

**Comment by pLum0** [comment]
Reloading Gnome is enough -> Alt-F2 -> Type "r" and press Enter.

**Comment by m-pereira** [comment]
> No need to restart, reloading Gnome is enough -> Alt-F2 -> Type "r" and press Enter.

It worked for me, thanks!
