### ISSUE TITLE
Dconf Schema does not exist

### ISSUE THREAD

**Issue by isti03** [hardpixel/unite-shell#218]
The dconf schemas are not registered correctly. 

Only the keys of the values that I change in the GTK settings dialog appear in the `dconf-editor`, but they appear as non-available. 
I cannot get or set the values via `gsettings set` and `gsettings get`, it says that there is no „org.gnome.shell.extensions.unite” schema.  

I assume it might be because of an API change.

**Comment by kerbrek** [comment]
You can point gsettings to extension's schemadir (look `gsettings help`):
`gsettings --schemadir "$HOME/.local/share/gnome-shell/extensions/unite@hardpixel.eu/schemas" set org.gnome.shell.extensions.unite notifications-position 'center'`

All settings available in "$HOME/.local/share/gnome-shell/extensions/unite@hardpixel.eu/schemas/org.gnome.shell.extensions.unite.gschema.xml" file.


Or you can write to dconf database directly without schema checks with `dconf` (look `man dconf`)
`dconf write /org/gnome/shell/extensions/unite/notifications-position "'center'"`

**Comment by isti03** [comment]
@kerbrek I don't have an `extensions` folder in `~/.local/share/gnome-shell/`, but even if it was the case, registering the dconf schemas just like any other extension would be the proper behaviour in my opinion.

**Comment by kerbrek** [comment]
> registering the dconf schemas just like any other extension would be the proper behaviour in my opinion.

Yeah, agree.

But if you find where `extensions` folder is stored on your system, you can [copy and compile schemas](https://askubuntu.com/questions/1171093/) by yourself.

**Comment by jonian** [comment]
@isti03 how is unite installed on your system? gnome-extensions? AUR?

**Comment by isti03** [comment]
I installed the `gnome-shell-extension-unite` (the non-git version) from the AUR @jonian

**Comment by jonian** [comment]
Fixed in AUR package. I'm marking this as invalid because it is an issue of the AUR package and not the extension.
