### ISSUE TITLE
Window title and global / locally-integrated menu behavior plans?

### ISSUE THREAD

**Issue by derrgill** [hardpixel/unite-shell#219]
I wondered if there were any plans to give users the option of having this work the way it did in Unity 7? What I mean specifically is where the window title was shown in the top bar until the mouse pointer hovered over it, which would reveal the (conventional, non-GNOME) app menu for the focused application, and this same menu would [re-appear inside the app window when](https://blog.3v1n0.net/informatica/linux/ubuntu-introducing-locally-integrated-menus-to-unity-7/) its window was not maximized. For me this is the only feature missing from the Unite extension, and would save just that bit more of screen space over the current form as seen in my screenshot:
![unite-gnome-extension-001](https://user-images.githubusercontent.com/7062385/103010422-5732cf00-4506-11eb-905f-68bce25a093b.png)

I love this extension, thank you for creating it!

**Comment by jonian** [comment]
Hi @derrgill, there are currently no plans for global menu but is  doable. Locally integrated menus are not possible through gnome extensions.

I'm closing this issue since it is already discussed in #67
