### ISSUE TITLE
[Feature Request] If you use the always-on window buttons, don't remove them, if there are no windows (to prevent shifting panel items).

### ISSUE THREAD

**Issue by Leleat** [hardpixel/unite-shell#220]
I use the `always`-on window buttons in the `last` position. That means, if I close the last or open the first window on a workspace the system menu needs to shift. This also applies to the `first` position and the `Activities` button.

It would be better to just grey the buttons out, if they aren't connected to a window so that other panel items don't move around.

**Comment by jonian** [comment]
Duplicate #208
