### ISSUE TITLE
Extension enters error state on upgrade

### ISSUE THREAD

**Issue by zlatko23** [hardpixel/unite-shell#225]
Thank you for the useful extension! Today I upgraded to v45 and it broke on gnome 3.38(Ubuntu 20.04 LTS).

**Comment by jonian** [comment]
@zlatko23, please provide the output of 

```
journalctl /usr/bin/gnome-shell | grep unite
```

**Comment by zlatko23** [comment]
@jonian - there is nothing in the log, empty in respect to "unite". I removed v45 and reinstalled v44. Restarted my session.

**Comment by jonian** [comment]
I tested with Ubuntu 20.04 LTS before releasing version 45. Maybe try again with v45 and restart your session and make sure the extension is enabled. If there are no errors in logs I can't help with this issue.

**Comment by zlatko23** [comment]
I removed totally extension, then installed it again - now there is no error message anymore.

**Comment by jonian** [comment]
So, it works now?

**Comment by zlatko23** [comment]
Yes, no error message. I am not sure if I should close the issue as it's not clear what was the problem and I see one more report of the same situation at extensions.gnome.org?

**Comment by jonian** [comment]
We can leave this issue open in case someone can provide more info or a way to replicate the issue. Thanks @zlatko23.

**Comment by jeffdyke** [comment]
I ran into this as well today, and found with the above command that i had to logout of the session.  Error message was 
```
JS ERROR: Extension unite@hardpixel.eu: Error: A different version was loaded previously. You need to log out for changes to take effect.
```

Doing just that solved the problem.

**Comment by nora-anne** [comment]
I updated today and got an error message as well. I can't figure out how to re-install a previous version, so now it's just broken.

**Comment by loxK** [comment]
Same: `Error` in the browser, and `JS ERROR: Extension unite@hardpixel.eu: Error: A different version was loaded previously. You need to log out for changes to take effect.` in logs.

Ubuntu 20.10

**Comment by jonian** [comment]
This is an upstream bug. Manually updating extensions without restarting GNOME does never work. The manual update feature on extensions.gnome.org is broken (see this [issue](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2514#note_758574)).

This has been reported on other extensions:

- corecoding/Vitals#165
- mzur/gnome-shell-wsmatrix#118 
- ai/autohide-battery#13
