### ISSUE TITLE
Does not place window buttons on left side

### ISSUE THREAD

**Issue by tutuca** [hardpixel/unite-shell#23]
![image](https://user-images.githubusercontent.com/70032/32358236-3e104b9e-c023-11e7-9eea-cc8e49f0186e.png)

With either ambiance or arc themes.

**Comment by jonian** [comment]
Use Gnome Tweak Tool to move the buttons to the left.
![screenshot from 2017-11-03 10-42-52](https://user-images.githubusercontent.com/4119508/32365804-14a002de-c084-11e7-9905-29ab1d426c8a.png)
