### ISSUE TITLE
Error after upgrade

### ISSUE THREAD

**Issue by ph-legacy** [hardpixel/unite-shell#232]
![image](https://user-images.githubusercontent.com/383295/112656654-e75c1980-8e51-11eb-9b67-774fa360613a.png)

Extension stopped working, but I dont know where to find any logs. If you tell me where to find it, I hapily provide additional info,

**Comment by jonian** [comment]
Hi @ph-legacy, have you tried restarting or logout/login? Maybe you issue is related to #225.

**Comment by jonian** [comment]
Closing since author has not responded.

**Comment by antimirov** [comment]
JFYI, restarting Gnome helped in my case.
