### ISSUE TITLE
Remove "Top bar desktop name text" completely

### ISSUE THREAD

**Issue by ananaso** [hardpixel/unite-shell#235]
Is there a way to completely remove/disable the "top bar desktop name text", so that blank desktops simply have no text at all in the top left corner?

I found you can simply leave the textbox blank, but this still leaves an artifact that becomes apparent when you're using extensions that are left-justified like "Places Status Indicator". Here's a comparison between a desktop without any windows and a desktop with a window, which should show how the places menu ("Orte") shifts awkwardly.

![topBarTextCompare](https://user-images.githubusercontent.com/44685609/114244101-b34d2200-9942-11eb-8d9a-e0eb7410871b.png)

**Comment by jonian** [comment]
There is a "Show desktop name in top bar" toggle in the "General" settings tab.

**Comment by ananaso** [comment]
Ahh, I guess I should have looked more carefully before opening my big mouth lol. Thanks!
