### ISSUE TITLE
Right click on top bar menu doesn't stay open

### ISSUE THREAD

**Issue by willgfx** [hardpixel/unite-shell#236]
When right clicking on the top bar with the "Enable titlebar actions on top bar click" and "Hide window titlebars" features enabled; the menu only momentarily displays during the down state of the right click, rather than staying open the way it normally would when right clicking on a titlebar.

I believe this behavior started with Gnome Shell 40. I am on version 48 of the extension.

You can work around the issue by holding down the right click to make your menu selection. Sometimes the menu will stay open on a long right click, but it is not consistent.

**Comment by meiser79** [comment]
Some on Ubuntu 20.04 with gnome-shell 3.36.7.
