### ISSUE TITLE
Scroll workspaces when scrolling on the top panel

### ISSUE THREAD

**Issue by Leleat** [hardpixel/unite-shell#237]
I am aware that GNOME 40 implements a `Super` + `Alt` +  `Scroll` but that only works on Wayland. There are also a bunch of other extensions, which offer this feature... but I'd like to reduce the amount of extensions I need :) and I think it makes sense to add it to Unite since Unite already interacts with GNOME's panel a lot.

**Comment by jonian** [comment]
Hi @Leleat, sorry for the late response. I will not implement this as the goal of this extension is not to replace others.
