### ISSUE TITLE
[QUESTION] How is the Unite "system tray" different from AppIndicator extensions? 

### ISSUE THREAD

**Issue by RedBearAK** [hardpixel/unite-shell#244]
I have this strange thing that I just noticed. I have two applications on my Ubuntu 21.04 system that were refusing to show an indicator icon in the standard indicator tray, which has icons from several other applications, and works when I use either Ubuntu's own AppIndicator extension or the identical extension from the GNOME extensions website. 

The two applications are AnyDesk and jDownloader. I could not get their indicator icons to appear no matter what I tried. 

I installed the Unite extension and enabled "Show system tray in top bar". At first I wasn't sure what it was doing. But then I noticed that the AnyDesk indicator icon had suddenly appeared! I started up jDownloader and that showed an indicator right next to AnyDesk, but it's messed up. It appears to be a transparent square that just shows what's behind it. But it's right next to the AnyDesk indicator icon and both are separated from the regular "AppIndicator" tray. 

So I'm looking for some technical information on how exactly this "system tray" that Unite enables is different from the regular indicator tray that all the other applications are using. Maybe I can help solve this problem of the missing AnyDesk icon for other people too, or communicate with the AnyDesk developers on what the problem is. But I have to understand what I'm talking about first.

**Comment by jonian** [comment]
Hi @RedBearAK, SystemTray and AppIndicator/KStatusNotifierItem are different things. Some applications have support for both and some only for SystemTray.

For more technical information I think it would be better to ask at https://github.com/ubuntu/gnome-shell-extension-appindicator .
