### ISSUE TITLE
Autohide status bar from the bottom instead of the top of the screen

### ISSUE THREAD

**Issue by joelostblom** [hardpixel/unite-shell#245]
I use this extension to autohide the status (top) bar and it is working great when I need to just occasionally peek at the status bar, which is most of the time. Occasionally I need to have the status bar visible for a longer period (e.g. to watch the time more closely) and while this is possible by setting the timeout to zero and binding a keyboard shortcut, the problem is that the position of the bar at the top means that it will display over important window information such as tabs, which is often located at the top of each window. It would be great to be able to show and hide the status bar from the bottom of the panel instead of from the top.

While there are other extensions that move the status bar to the bottom, I have not found one that work  with Unite's autohide functionality which will bring the bar back to the top. Would it be possible to support autohiding the bar from the bottom of the screen either via another extension or by baking this functionality into Unite?

**Comment by jonian** [comment]
Hi @joelostblom, sorry for the late response. Unite does not have a feature to auto-hide the status bar (top panel). Maybe you can check https://github.com/mlutfy/hidetopbar and make a feature-request there.

**Comment by joelostblom** [comment]
Whooops, I must have mixed my extensions! Sorry about that and thanks for pointing me to the correct one.
