### ISSUE TITLE
Make app menu responsive 

### ISSUE THREAD

**Issue by KonstantMan** [hardpixel/unite-shell#246]
Is there any way to make app menu responsive  in order to hide when there is no application open ?
![Screenshot from 2021-06-14 19-52-39](https://user-images.githubusercontent.com/56481040/121929551-d7592500-cd30-11eb-8742-7a52da64a03f.png)
![Screenshot from 2021-06-14 19-52-33](https://user-images.githubusercontent.com/56481040/121929554-d7f1bb80-cd30-11eb-83d6-a60b5d24d1bd.png)

**Comment by jonian** [comment]
Hi @KonstantMan, sorry for the super late response. Unite does not handle appmenu visibility, it is handled by gnome-shell. Maybe you should report this issue upstream.
