### ISSUE TITLE
Missing settings to control clock placement

### ISSUE THREAD

**Issue by ghost** [hardpixel/unite-shell#247]
Hi! I'd like to know if there's a simple way (by editing something) to change the clock placement to something other than the current 'move to right' approach. If there isn't, I'd like to help with that, but I think I would need some hints to get going. Thanks!

**Comment by jonian** [comment]
Hi @nhermosilla-smbtc, unite extension does not move the clock, it extends the left panel area, and there is no simple way to do it.

There are other extensions that you can use to move the clock:

- https://extensions.gnome.org/extension/2/move-clock
- https://extensions.gnome.org/extension/3843/just-perfection
