### ISSUE TITLE
Menu bar

### ISSUE THREAD

**Issue by dhra** [hardpixel/unite-shell#26]
Is it possible to add software menu bar in top left panel?

**Comment by jonian** [comment]
Please give more info. I do not understand the request.

**Comment by RockOnHero** [comment]
@dhra maybe means the menu of the software currently in focus. This would make the extension even more similar to unity. I am not sure, but this feature request is because of the gnome api not possible.

**Comment by jonian** [comment]
@RockOnHero global menu implementation is not possible now and maybe not in the future.
