### ISSUE TITLE
unite is making the telegram open in the conversation every time a notification arrives.

### ISSUE THREAD

**Issue by hadsonmartins** [hardpixel/unite-shell#262]
Hello, I'm using ubuntu 20.04 gnome 3.36 and when I use the desktop telegram and a notification arrives, it opens alone in the conversation, but if I disable the unite extension it returns to normal only the notification appears. conclusion unite is making the telegram open in the conversation every time a notification arrives.

**Comment by jonian** [comment]
Hi @hadsonmartins, you can disable this by switching off "Auto focus new windows". When #82 is implemented, you will be able to disable it per application.
