### ISSUE TITLE
Title disappears from bar

### ISSUE THREAD

**Issue by MartyJustice** [hardpixel/unite-shell#27]
When I use the "super"  key the title of e.g. a webpage disappears from the top panel. 
What for information do you need to debug the issue? 

Extension installed from https://extensions.gnome.org/
Using Ubuntu 17.10 (Ubuntu dock removed) 
Gnome: 3.26.2

**Comment by jonian** [comment]
Please give more info.

> When I use the key

Which key?

**Comment by MartyJustice** [comment]
@jonian  `<super>` key

**Comment by jonian** [comment]
@MartyJustice this is not a bug. This is how the extensions works. It shows the application title only when a window is focused.
