### ISSUE TITLE
v58 window titles still missing after uninstalling the extension

### ISSUE THREAD

**Issue by tomaszwaraksa** [hardpixel/unite-shell#270]
After brief experimenting with the extension I have uninstalled it. Didn't work well enough for me. Unfortunately, window titles are now gone on many application windows, rendering them unusable. Cannot move some windows around. How to restore the system back to sanity? What has been changed in settings / gtk themes? Help...

------------------------------
OS: Pop!_OS 21.04 x86_64 
Kernel: 5.13.0-7614-generic 
Shell: bash 5.1.4 
DE: GNOME 
WM: Mutter 
WM Theme: Pop 
Theme: Pop [GTK2/3] 
Icons: Deepin [GTK2/3] 
Terminal: tilix

**Comment by tomaszwaraksa** [comment]
Slack, with window titlebar gone.

![image](https://user-images.githubusercontent.com/1721566/139646221-7dcefb61-0c15-45bc-b335-59ddca69f34d.png)

**Comment by tomaszwaraksa** [comment]
Thunderbird, titlebar gone

![image](https://user-images.githubusercontent.com/1721566/139646287-4489ef28-6410-4a8c-a4af-287c164ba08f.png)

**Comment by jonian** [comment]
Did you uninstall the extension from extensions app/website or you just removed the extension folder manually? Did you try to restart your session?

**Comment by tomaszwaraksa** [comment]
Hi, thanks,
I've uninstalled it the standard way. First disabled the extension using the Extension app, then uninstalled it completely. As far as I can see, there's no residue left in `/usr/share/gnome-shell/extensions`:

```
drwxr-xr-x - root 17 Sep  8:34 cosmic-dock@system76.com
drwxr-xr-x - root 14 Aug 13:14 ding@rastersoft.com
drwxr-xr-x - root 17 Sep  8:36 pop-cosmic@system76.com
drwxr-xr-x - root  9 Oct 20:44 pop-shell@system76.com
drwxr-xr-x - root 18 Sep 12:20 system76-power@system76.com
drwxr-xr-x - root  2 Jul 14:46 ubuntu-appindicators@ubuntu.com
drwxr-xr-x - root  2 Jul 14:54 ubuntu-dock@ubuntu.com
```

**Comment by jonian** [comment]
Hi, is the issue resolved?

You should always remove extensions from the extensions app. All extensions remove their changes when they are disabled/uninstalled.

**Comment by tomaszwaraksa** [comment]
Hi, 

I have uninstalled the extension using the extensions app, the proper way.

Unfortunately, the issue remains. I've restarted the session, to no avail. Then tried restoring system settings with TimeShift, a few days back. Didn't help either. Hence I'm curious, what exactly does the extension change. Any gtk+ stylesheets outside TimeShift's scope?

thanks!

**Comment by tomaszwaraksa** [comment]
As of now, many applications remain broken. Seems like only native-Gnome applications are okay. Others are messed up - Thunderbird, Softmaker Office, Electron-based apps (Signal, Slack etc). They've lost window chrome - no titlebars, cannot resize or move any of them .

**Comment by jonian** [comment]
The extension does not change any settings. As for GTK stylesheets, it adds a css import in `~/.config/gtk-3.0/gtk.css`, that can't cause any issues if the extension is removed.

**Comment by jonian** [comment]
Did you try to disable all extensions? Maybe some other extension is causing issues. Pop OS has it's own extension `pop-shell` that also removes title-bars https://github.com/pop-os/shell/blob/master/src/xprop.ts

**Comment by tomaszwaraksa** [comment]
Hi, thanks for the tip, appreciated! Looks indeed like something got messed up with `pop-shell`. When I switch it off, title bars are back. Closing the issue, I'll continue investigating further.
