### ISSUE TITLE
Fedora 35 Silverblue

### ISSUE THREAD

**Issue by DiogoToraci** [hardpixel/unite-shell#271]
Hello, I hope you are doing well, after I upgraded today to Fedora 35 Silverblue there is a lot off error notification "xprop failed" if the Unite Gnome extension is on. I am using Wayland too.

Thank in advance

**Comment by DiogoToraci** [comment]
There is a screenshot with the notification, my system is in Portuguese, sorry for that.

![Captura de tela de 2021-11-02 17-42-54](https://user-images.githubusercontent.com/66385817/139948855-20066b79-aa6a-4d56-8188-c81e8d852753.png)

**Comment by jonian** [comment]
Hi @DiogoToraci, you have to install `xprop` for the extension to work properly. I think you can install it with:

```sh
dnf install xprop
```

**Comment by DiogoToraci** [comment]
Hi @jonian thanks, i had tried the installation and had not succeeded, after you recommended me i tried again and it worked. :)
For knowledge, the command is: 

`rpm-ostree install xprop`

Have a nice Day!

**Comment by jonian** [comment]
Thanks for reporting back @DiogoToraci. I will add the install command for Silverblue in the readme.

Have a nice day!
