### ISSUE TITLE
Windows Tittle cut in gnome 41

### ISSUE THREAD

**Issue by Froggy232** [hardpixel/unite-shell#272]
Hi,
First, thanks you a lot for this extention!
Since the last gnome update, when I activate the "Show windows tittle in app menu", the text is cut and not appear entirely, like in this screenshot : https://zupimages.net/up/21/45/5kxl.png
Is there a way to have the entire tittle in place of theses three dots, like in previous version of gnome?
Thanks you,
Best regards

**Comment by jonian** [comment]
Hi @Froggy232, sorry the the late response. I can't access the screenshot you provided. Check the settings in "Appearance" tab for "Max width for the app menu", maybe that is causing your issue. I'm on gnome 41 and I don't have any issues with the app menu.

**Comment by Froggy232** [comment]
Hi,
Thanks for your answer, I took another screenshot here : https://zupimages.net/viewer.php?id=21/49/s4ww.png
Max widht for the app menu is on 0, the problem is still here if I put it to max (1000).
Thanks for your help!

**Comment by jonian** [comment]
Gnome has broken backwards compatibility for extensions. This extension now supports only gnome 45.
