### ISSUE TITLE
Changing workspaces creates a JS error

### ISSUE THREAD

**Issue by Leleat** [hardpixel/unite-shell#274]
When changing workspaces I get the error

```
JS ERROR: Error: Expected an object of type ClutterActor for argument 'sibling' but got type undefined
_syncStacking@resource:///org/gnome/shell/ui/workspaceAnimation.js:80:18
```

in my journalctl with Unite enabled.

[Edit]

**System Info**
- Fedora 35
- GNOME Shell 41.2
- Unite version: 59

**Comment by jonian** [comment]
Hi @Leleat, sorry for the super late response. Are you still having this issue? I can't replicate it.

**Comment by Leleat** [comment]
Nope, can't reproduce this anymore.
