### ISSUE TITLE
[Feature request] Global Menu

### ISSUE THREAD

**Issue by neffscape** [hardpixel/unite-shell#278]
I absolutely love this extension: thank you very much for your amazing work!!! The only thing that I now miss is an integrated Global Menu. I'm now using [Fildem's Global Menu Extension](https://github.com/gonzaarcr/Fildem) but it's buggy and doesn't integrate with unite very well. Please consider including this feature in a future version. Thank you again so much for your amazing work!

**Comment by jonian** [comment]
Duplicate of #67
