### ISSUE TITLE
[feature request] GUI option to change the dock's application button position

### ISSUE THREAD

**Issue by Adzetko** [hardpixel/unite-shell#28]
Actually, if you're using Ubuntu's dock extension, the applications menu's button is on the bottom of your dock (on the right if yours is on the bottom of your screen), but as you might know, Unity has it's menu button on the top (and on the left if you used Unity Tweak Tool to set the dock at the bottom of your screen).
If I understand correctly the purpose of this plugin, the goal is to mimick the behaviour of Unity shell.
So that's why I'm requesting this feature!

**Comment by jonian** [comment]
This can be done by uninstalling the Ubuntu Dock and installing Dash to Dock. Having options to change settings for other extensions is not a good practice.
