### ISSUE TITLE
Firefox title bar not showing when maximized on second screen

### ISSUE THREAD

**Issue by mezcalbert** [hardpixel/unite-shell#281]
Dear all,

Thanks for that wonderful Unite extension that has been saving my life since I switched back to Gnome shell from the Unity dash.

Now, I have 2 issues and I will list them separately.

This one is regarding Firefox. I have title bars enabled in the customize menu of Firefox and that title bar disappears entirely when maximized on the second screen (where there is no top bar). 
I think there's a similar issue with CSDs but in this case since I activated the title bar I'm actually deactivating CSDs, hence it shouldn't be a problem.

I can still grab the window by positioning the cursor at the very top of the screen and unmaximize it by dropping it below. So it's not a huge deal.

![Screenshot from 2022-02-07 18-30-20](https://user-images.githubusercontent.com/19873056/152841116-f02ec770-6c21-4ef2-9e9f-bdd3a734c260.png)

Last piece of info. This issue disappears when I disable Unite.

![Screenshot from 2022-02-07 18-40-16](https://user-images.githubusercontent.com/19873056/152842294-0f268419-0266-497a-9090-aa6c3c9dd1d0.png)

**Comment by mezcalbert** [comment]
Hi,
Yes, it does. That option is always enabled.
It happens not just with Firefox but with Writer, Inkscape, and probably more, but not with GIMP though (weird as it also has a title bar).

**Comment by jonian** [comment]
@mezcalbert are you using firefox with wayland enabled `MOZ_ENABLE_WAYLAND=1`? You can check in `about:support` and search for `Window Protocol`.

If you are running it in wayland mode, then this is a known issue #74.
