### ISSUE TITLE
MS Edge doubling down window controls when maximized in top bar

### ISSUE THREAD

**Issue by mezcalbert** [hardpixel/unite-shell#282]
Hi, 

The second issue I'm facing has to do with the window controls of Edge that do not disappear _entirely_ in the top bar. Although my preferences say it should. Hence, I have 2 rows of buttons.

I think it doesn't work in Chrome either, but I'm a 100% sure that it worked with Edge at the early stage of the porting to Linux, about a year ago when it was still the dev version, and maybe even during the beta phase. So I'm disappointed to see they're back as in Chrome.

![Screenshot from 2022-02-07 18-50-15](https://user-images.githubusercontent.com/19873056/152843897-8fc3bfd0-3a14-40d2-b424-a3f9b9c968a2.png)

**Comment by jonian** [comment]
The only solution is what @wojpawlik suggested
