### ISSUE TITLE
GTK application buttons removed even when the extension is not activate

### ISSUE THREAD

**Issue by Microwave-WYB** [hardpixel/unite-shell#285]
I freshed installed manjaro gnome in virtual machine to test this bug. Before I activate Unite, the application buttons behaved normally. When I turned on and configured Unite, the application buttons could be moved to the top bar as expected. However, when I then turned off the extension, GTK apps are not showing buttons when maximized. 
Is there any way to have the buttons back when I maximize the window?

**Comment by jonian** [comment]
GTK apps with client side decorations use CSS to hide their decorations. For the changes to take effect you have to restart those apps.
