### ISSUE TITLE
Putting window buttons to the left of system tray icons

### ISSUE THREAD

**Issue by Motor-head** [hardpixel/unite-shell#288]
Currently setting window buttons at "Right" makes the buttons appear between the keyboard layout and Settings drop down menu:
![Screenshot from 2022-03-20 01-19-06](https://user-images.githubusercontent.com/93347209/159136360-f0c122a6-e146-471d-9a35-6d74f8d8df2f.png)
Putting the Window buttons to the left of System tray icons will make it look less garbled: 
![Screenshot from 2022-03-20 01-19-06 (copy)](https://user-images.githubusercontent.com/93347209/159136525-8a7674ec-be12-41a9-bef3-bb1e4ddd6dd5.png)

**Comment by jonian** [comment]
It is not possible. Please refer to #41
