### ISSUE TITLE
Titlebar action double-click not working on GNOME 42

### ISSUE THREAD

**Issue by Krindog7337** [hardpixel/unite-shell#290]
the "enable titlebar action on top bar right click" are not working on GNOME 42. Re-enabling the settings not working at all. it was working on GNOME 41 until I updated to GNOME 42

![image](https://user-images.githubusercontent.com/92032579/162475149-ad525f7d-d7cf-482e-89ba-662fd743fb23.png)

**Comment by jonian** [comment]
Thanks for the report @Krindog7337. It looks like `event.get_count_click()` not available anymore and it throws an error. The extension can't check if the user double clicked the top bar and invoke the action. It also looks like single primary click not working anymore.

**Comment by Krindog7337** [comment]
thanks for fixing it. working flawlessly rn
![image](https://user-images.githubusercontent.com/92032579/164894009-7a764edd-b4e7-4bca-8203-ae929dbf109f.png)

**Comment by jonian** [comment]
Hi @haoadoreorange, n the issue has not been fixed yet.

**Comment by haoadoreorange** [comment]
There's another extension "unmaximized..." that does just that (double click gnome top bar to unmaximize). Sadly it comes with other side effects. Maybe we can look at how they done it ?

**Comment by jonian** [comment]
That will help. Do you have a link to the extension repository?

**Comment by gcvl** [comment]
Nonetheless holding and dragging down the top panel/title bar demaximizes the window.

**Comment by jonian** [comment]
Gnome has broken backwards compatibility for extensions. This extension now supports only gnome 45.
