### ISSUE TITLE
Double title bar buttons in different apps

### ISSUE THREAD

**Issue by Rudqo** [hardpixel/unite-shell#295]
- OS: [Ubuntu 22.04]
 - GNOME Shell version [42]
 - Unite version [65]

Firefox Developer Edition 100.0b9 (64-bit)
![firefox_double_title_bar_buttons](https://user-images.githubusercontent.com/104697707/166123858-1820185c-f008-4200-b75b-c979846ae609.png)

Ubuntu software (snap store)
![snap_double_title_bar_buttons](https://user-images.githubusercontent.com/104697707/166123897-22ba4638-0e6d-4c23-a9c0-2a043170b796.png)

Telegram v 3.7
![telegram_double_title_bar_buttons](https://user-images.githubusercontent.com/104697707/166123925-ee171c2b-bc89-4046-855a-fc6cd2d1f8f9.png)

**Comment by jonian** [comment]
Firefox: disable "Title Bar" from customize screen
Telegram: enable "Use system window frame" from settings -> advanced
Snap Store: Snap and Flatpak apps are not supported

Closing since these have been answered many times and have been answered in multiple issues.
