### ISSUE TITLE
3 buttons positionned properly when used with Dash to Panel.

### ISSUE THREAD

**Issue by HubKing** [hardpixel/unite-shell#296]
**Is your feature request related to a problem? Please describe.**
I am using Unite with [Dash to Panel](https://github.com/home-sweet-gnome/dash-to-panel). The problem I am experiencing is that the 3 buttons (minimise/maximise/close) often go beneath icons from other apps (such as an IME, like Fcitx5). When Gnome is first started, they don't overlap, but after some time of use, the Fcitx icon is displayed above the maximise button.

**Describe the solution you'd like**
Maybe this is because the 3 buttons are not reserving the space properly? I am not sure, and since the combination of using both Unite and Dash to Panel could be rare, I am not sure which software is responsible. But it if is not too much trouble, I would like this problem to be solved.

**Comment by jonian** [comment]
Hi @HubKing, there is no way to reserve the position of buttons/widgets added to top panel. The order is based on the order the extensions are loaded. Check #41 for more info.

**Comment by HubKing** [comment]
I have found a sort-of solution. It seems that this problem only happens when "Reduce top bar items spacing". The default spacing is too wide between the time and battery+etc, but I guess it is better than having overlapped icons.
