### ISSUE TITLE
The button does not work，restarting the computer after the computer locks the screen， in GNOME42

### ISSUE THREAD

**Issue by zxm-bupt** [hardpixel/unite-shell#299]
**Describe the bug**
When I wake up the computer from the lock screen, the buttons no longer work, and when I open a new app, the buttons resume.

**To Reproduce**
1. Open a software， such as gnome-terminal
2. lock screen
3. wake up computer
4. buttons will don't work when I click it

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - GNOME Shell version 42
 - Unite version 65

**Comment by jonian** [comment]
Hi @zxm-bupt, I can't reproduce the issue. Please provide the output of `journalctl -g unite`.

**Comment by jonian** [comment]
Closing due to no response. Also I can't reproduce the issue on arch linux and ubuntu 22.04

**Comment by jonian** [comment]
Re-opening. I can reproduce this on wayland only.
