### ISSUE TITLE
Error: No signal 'size-changed' on object 'ShellWM'

### ISSUE THREAD

**Issue by yafp** [hardpixel/unite-shell#3]
I can not activate the unite extension (installed latest version via: extensions.gnome.org) on my Ubuntu 16.04 installation (dual monitor setup)

LG shows the following error:

> Error: No signal 'size-changed' on object 'ShellWM'

**Comment by jonian** [comment]
Hi, thank you for the report.
What gnome shell version do you have installed?

**Comment by jonian** [comment]
This is now fixed in version 3. I have submited the new version in gnome shell extensions website and it will be available in the next days.

**Comment by yafp** [comment]
Ubuntu 16.04 (current LTS version) is using a pretty old version: 3.18.5
