### ISSUE TITLE
Add the Unity Menu

### ISSUE THREAD

**Issue by heschy2** [hardpixel/unite-shell#300]
**Is your feature request related to a problem? Please describe.**
Gnome has a great Application Menu, but it is a bit frustrating that when i press Super,
Gnome opens up the Activity Overview instead of the Application Menu. 

But Unity had an even better Application Menu, wich also could run commands from the search.
I want to have such a menu in gnome.

And yes, i kno that Arc Menu has a Unity-like layout, but it does not really look like unity and itonly searches in applications,
not in the Terminal-commands.

Of course, there are things in that menu you could make better then cannonical, for example the menu could pop up in any corner 
of the screen, not only in the upper left.

**Describe the solution you'd like**
Unite wants to imintate the Unityshell, so I think it would be in your opinion to create a 
Unity-like Application Menu for gnome. Where you can run commands and open apps.

Just Press Super and instead of Gnome Overview that Meu apears in corner.

**Describe alternatives you've considered**
1. Gnome has the Run Command Function, (ALT+F2 I think) and you could add a Application list to that dialog.
2. You could deactivate the Overview via the extension.

**Additional context**

**Comment by philipl** [comment]
Arc-Menu has a Unity mode. Does that give you what you want?

**Comment by heschy2** [comment]
As I said, no it doesn't
> And yes, i know that Arc Menu has a Unity-like layout, but it does not really look like unity and it only searches in applications,  
> not in the Terminal-commands.
Its important for me to run terminal commands using this feature in unity. If it would support the Gnome Titlebars (of course it doesn't) I would use unity, because of that feature. But because unity doesnt (it uses the Gnome Titlebar AND adds the standart Titlebar) I want to have that feature in Gnome.

Yes I know that I can use SUPER+F1 to open the execute Command Layout, but I want to have it all in one single Menu.

I hope that Explanation helps.

**Comment by jonian** [comment]
Closing this as I agree with @philipl, arc menu is a great extension that provides a unity mode menu.
