### ISSUE TITLE
add icons for orchis theme.

### ISSUE THREAD

**Issue by rodrigoGA** [hardpixel/unite-shell#301]
please add icons for [orchis theme](https://github.com/vinceliuice/Orchis-theme)

**Comment by jonian** [comment]
You can add custom themes in `~/.local/share/unite-shell/themes`. Check existing themes [here](https://github.com/hardpixel/unite-shell/tree/master/unite%40hardpixel.eu/themes) to see how a theme is implemented. 

You can also submit a PR with your theme, so other people can use it.
