### ISSUE TITLE
Top bar window buttons appear when all windows closed

### ISSUE THREAD

**Issue by lbell** [hardpixel/unite-shell#302]
**Describe the bug**
If all windows are closed, the top bar window buttons magically reappear, even though there is not target to minimize, close, etc.

**To Reproduce**
1. Close all windows
2. The top bar window buttons appear

**Expected behavior**
There should be no top bar window buttons when all windows are closed.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - GNOME Shell version: 42.2
 - Unite version: 64

**Other details**
Only started recently (last update?) was initially working fine on 22.04

**Comment by Coeur-Noir** [comment]
Hi,

I can see something similar but I think I know why : 
⋅ do you make use of DiNG extension for showing icons on desktop ?
⋅ are you on a wayland session ?

Unite Version here is 65 on a regular gnomish Ubuntu 22.04.

**Comment by lbell** [comment]
Bingo. On Waylund and using DiNG. Was not an issue initially, so sounds similar.

Would like to be able to use waylund and DiNG.

So would the fix:  `check the "window.skip_taskbar" flag and ignore any windows with that set. Then it won't get fooled by DING technically being a maximized window.` work for unite?

Thanks!

**Comment by Coeur-Noir** [comment]
« _So would the fix: check the "window.skip_taskbar" flag and ignore any windows with that set. Then it won't get fooled by DING technically being a maximized window. work for unite?_ »

I don't know, just an assumption, I'm no dev' just a stupid user ;-) It just sounds like same « logic ».

**Comment by Idechix** [comment]
Hi,
I'm experiencing the same issue.
I'm using a fresh install of Ubuntu 22.04 on Wayland, but **without DING installed**.
In my case the top bar window buttons are visible as soon as the session starts.
It shows each time the desktop is visible.

**Comment by Coeur-Noir** [comment]
Isn't DING installed by default on 22.04 ?

Maybe you turned off icons on desktop but did not really stop the extension.

Here if I turn off DING, buttons no longer appear / only appear when expected.

Le 28 juillet 2022 10:47:27 GMT+02:00, Idechix ***@***.***> a écrit :

**Comment by Idechix** [comment]
I checked on apt, and the ding package is not installed on my system.
Am I wrong?

**Comment by Idechix** [comment]
> Isn't DING installed by default on 22.04 ? Maybe you turned off icons on desktop but did not really stop the extension. Here if I turn off DING, buttons no longer appear / only appear when expected. Le 28 juillet 2022 10:47:27 GMT+02:00, Idechix ***@***.***> a écrit :
> […](#)
> Hi, I'm experiencing the same issue. I'm using a fresh install of Ubuntu 22.04 on Wayland, but **without DING installed**. In my case the top bar window buttons are visible as soon as the session starts. It shows each time the desktop is visible. -- Reply to this email directly or view it on GitHub: [#302 (comment)](https://github.com/hardpixel/unite-shell/issues/302#issuecomment-1197850158) You are receiving this because you commented. Message ID: ***@***.***>

I checked on apt, and the ding package is not installed on my system.
Am I wrong?

**Comment by Idechix** [comment]
> I checked on apt, and the ding package is not installed on my system.
> Am I wrong?

Ok guys, I was stupid... I found the ding extension, and yes it was installed on my desktop by default!
Turning it off solved the problem.
