### ISSUE TITLE
Flatpak + Flatseal

### ISSUE THREAD

**Issue by Froggy232** [hardpixel/unite-shell#303]
Hi,
I desperately try to use the "Hide Windows Titlebar" function with flatpak app, and I was wondering if it was possible by tweaking flatseal.
![Capture d’écran du 2022-07-22 00-27-39](https://user-images.githubusercontent.com/72796064/180325783-4fabdf95-de86-4279-9429-9d566cd9dd70.png)
Here is a screen capture of flatseal.
If not, do you know if this function will work with flatpak in the future?
Thanks you

**Comment by jonian** [comment]
Hi @Froggy232, I don't know how you can do it with flatseal, but you can make flatpak apps work using the commands below:

```sh
sudo flatpak override --filesystem=xdg-config/gtk-3.0
sudo flatpak override --filesystem=xdg-config/gtk-4.0

# This commands depends on where unite is installed
sudo flatpak override --filesystem=xdg-data/gnome-shell/extensions/unite@hardpixel.eu/styles
```

After that you can run `flatpak override --show` to see if your commands worked.

```
[Context]
filesystems=xdg-config/gtk-3.0;xdg-data/gnome-shell/extensions/unite@hardpixel.eu/styles;xdg-config/gtk-4.0;
```

If you can do the same with flatseal, please share you solution.

**Comment by Froggy232** [comment]
Hello,
Thanks you a lot for your answer!
I'm away from home for a few days, but I will try your solution ASAP.
I don't know how to make it work with flatseal, but if it's work with CLI it's good.
I will report back and close the issue if it work.
Thanks you a lot!

**Comment by Froggy232** [comment]
It worked!
Thanks you a lot

**Comment by uohmak4fvpqe** [comment]
Not working for me, be it Flatseal or Gedit
I have the path ```~/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles``` indeed
and ```flatpak override --show``` prints the same as you

**Comment by uohmak4fvpqe** [comment]
> Hi @Froggy232, I don't know how you can do it with flatseal, but you can make flatpak apps work using the commands below:
> 
> ```shell
> sudo flatpak override --filesystem=xdg-config/gtk-3.0
> sudo flatpak override --filesystem=xdg-config/gtk-4.0
> 
> # This command depends on where unite is installed
> sudo flatpak override --filesystem=xdg-data/gnome-shell/extensions/unite@hardpixel.eu/styles
> ```
> 
> After that you can run `flatpak override --show` to see if your commands worked.
> 
> ```
> [Context]
> filesystems=xdg-config/gtk-3.0;xdg-data/gnome-shell/extensions/unite@hardpixel.eu/styles;xdg-config/gtk-4.0;
> ```
> 
> If you can do the same with flatseal, please share you solution.

Not working for me, be it Flatseal or Gedit
I have the path ~/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles indeed
and flatpak override --show prints the same as you

**Comment by gaussandhisgun** [comment]
> If you can do the same with flatseal, please share you solution.

forcing the same overrides to global under Filesystem seemed to work (if anyone still cares about this)
![image](https://github.com/hardpixel/unite-shell/assets/63512006/76a9363a-2e6e-4c1e-8eb4-7c1869a19138)
![image](https://github.com/hardpixel/unite-shell/assets/63512006/b39cd966-5c6e-444d-a49f-b88cd6854444)

**Comment by siddhpant** [comment]
@jonian It doesn't seem to work, I'm trying with Slack. Any pointers?

**Comment by siddhpant** [comment]
Nmv, after a restart it seems to be gone. Thanks!
