### ISSUE TITLE
Epiphany: Duplication of window buttons

### ISSUE THREAD

**Issue by YulBrinner90** [hardpixel/unite-shell#304]
Hi, thanks for your work.

With Epiphany the window buttons are duplicated when maximized: three on the top panel and three on the Epiphany GUI. Yes, Epiphany hasn't a proper titlebar as Firefox. File also hasn't a titlebar but works perfectly.

![Screenshot from 2022-07-22 10-42-12](https://user-images.githubusercontent.com/88581172/180400489-7018338e-1bda-4bfd-9733-69cdef8eb613.png)

 - OS: Ubuntu: 22.04
 - GNOME Shell version: 42
 - Unite version: 65

`-- Boot ed542e29b79747c4b2a6ebb2e6f72a31 --
-- Boot 4a5663e2d74c412c9d5970d5c12e7ff1 --
-- Boot 30af54c0ee0348c6a8d12eb544678a55 --
lug 09 14:21:14 alberto-XPS gnome-shell[1675]: Could not create transient scope for PID 0: GDBus.Error:org.freedesktop.systemd1.UnitExists: Unit app-gnome-or>
lug 09 14:21:33 alberto-XPS gnome-shell[1675]: Could not create transient scope for PID 0: GDBus.Error:org.freedesktop.systemd1.UnitExists: Unit app-gnome-or>
-- Boot 370c80c3b5c74f3888ba9d399fab3879 --
lug 09 14:35:03 alberto-XPS gnome-shell[1665]: Could not create transient scope for PID 0: GDBus.Error:org.freedesktop.systemd1.UnitExists: Unit app-gnome-or>
lug 09 14:36:41 alberto-XPS gnome-shell[1665]: Could not create transient scope for PID 0: GDBus.Error:org.freedesktop.systemd1.UnitExists: Unit app-gnome-or>
lug 09 14:45:23 alberto-XPS gnome-shell[3912]: Could not create transient scope for PID 0: GDBus.Error:org.freedesktop.systemd1.UnitExists: Unit app-gnome-or>
lug 09 14:45:42 alberto-XPS gnome-shell[3912]: Could not create transient scope for PID 0: GDBus.Error:org.freedesktop.systemd1.UnitExists: Unit app-gnome-or>
lug 09 14:51:03 alberto-XPS gnome-shell[3912]: Could not create transient scope for PID 0: GDBus.Error:org.freedesktop.systemd1.UnitExists: Unit app-gnome-or>
-- Boot 51178413474b46cfad162519c4917859 --
-- Boot fe1d686c7d1645b4ae5971ede7db5394 --
lug 09 15:09:26 alberto-XPS gnome-shell[1675]: Could not create transient scope for PID 0: GDBus.Error:org.freedesktop.systemd1.UnitExists: Unit app-gnome-or>
lug 09 15:09:29 alberto-XPS gnome-shell[1675]: Could not create transient scope for PID 0: GDBus.Error:org.freedesktop.systemd1.UnitExists: Unit app-gnome-or>
lug 09 15:09:36 alberto-XPS gnome-shell[1675]: Could not create transient scope for PID 0: GDBus.Error:org.freedesktop.systemd1.UnitExists: Unit app-gnome-or>
lug 09 15:16:00 alberto-XPS gnome-shell[1675]: Could not create transient scope for PID 0: GDBus.Error:org.freedesktop.systemd1.UnitExists: Unit app-gnome-or>
lug 09 15:23:01 alberto-XPS gnome-shell[1675]: Could not create transient scope for PID 0: GDBus.Error:org.freedesktop.systemd1.UnitExists: Unit app-gnome-or>
lug 09 15:37:28 alberto-XPS gnome-shell[1675]: Could not create transient scope for PID 0: GDBus.Error:org.freedesktop.systemd1.UnitExists: Unit app-gnome-or>
lug 09 16:40:26 alberto-XPS gnome-shell[31568]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/
lug 09 16:40:26 alberto-XPS gnome-shell[31568]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/panel.js
lug 09 16:40:26 alberto-XPS gnome-shell[31568]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/layout.js
lug 09 16:40:26 alberto-XPS gnome-shell[31568]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/helper.js
lug 09 16:40:26 alberto-XPS gnome-shell[31568]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/window.js
lug 09 16:40:26 alberto-XPS gnome-shell[31568]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/prefs.js
lug 09 16:40:26 alberto-XPS gnome-shell[31568]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/settings.ui
lug 09 16:40:26 alberto-XPS gnome-shell[31568]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/styles/
lug 09 16:40:26 alberto-XPS gnome-shell[31568]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/styles/spacing-cl>
lug 09 16:40:26 alberto-XPS gnome-shell[31568]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/styles/spacing-le>
lug 09 16:40:26 alberto-XPS gnome-shell[31568]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/schemas/
lug 09 16:40:26 alberto-XPS gnome-shell[31568]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/schemas/org.gnome.shell.ext>
lug 09 16:40:26 alberto-XPS gnome-shell[31568]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/schemas/gschemas.compiled
lug 09 16:40:26 alberto-XPS gnome-shell[31568]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/
lug 09 16:40:26 alberto-XPS gnome-shell[31568]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/
lug 09 16:40:26 alberto-XPS gnome-shell[31568]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-left/
`

Thanks

**Comment by jonian** [comment]
Hi @YulBrinner90, if Epiphany is a Flatpak it will not work.

**Comment by jonian** [comment]
If it is a flatpak, check #303 for a solution.

**Comment by YulBrinner90** [comment]
Great! You are great, man! With the commands in #303 Unite-shell is able to wide the "original" window buttons of all flatpak applications: Epiphany, Flatseal, Video, Video-downloader... Now my system is perfect!
