### ISSUE TITLE
Unite & MultiMonitor on Gnome 42

### ISSUE THREAD

**Issue by RomanValov** [hardpixel/unite-shell#310]
**Describe the bug**
Hi

I'm running Ubuntu 22.04, Gnome 42 on two-monitor setup with Unite and MultiMonitor extensions.
My aim to get absolutely symmetrical setup on both monitor (each monitor to have a dock and top bar panel).

The MultiMonitor addon I'm using is cloned from fork by realh: https://github.com/realh/multi-monitors-add-on
where support for Gnome 42 was added. The results I've got so far:

Top bar panels exist on both monitors and windows when maximized don't use title bars

But:
 - I have no window controls (min,max,close) on second monitor.
   When window on second monitor is selected controls on first monitor top bar acts on a window
 - I have no title/icon of application on second monitor.
   When window on second monitor is selected title and icon are shown on first monitor top bar
 - I can't drag maximized window at second monitor by pressing mouse on top bar on second monitor
  Pressing mouse on first monitor top bar doesn't work either
 - datetime control right alignment option has no effect and tray icons are not shown also

**To Reproduce**
1. Install Ubuntu 22.04 with Gnome 42
2. Install Unite extension
3. Install Multi Monitor addon extension

**Screenshots**
My settings:

![Screenshot from 2022-10-17 17-29-40](https://user-images.githubusercontent.com/5928128/196168666-7c24ae1b-6fe0-4e5b-ba63-edb14ace8c45.png)
![Screenshot from 2022-10-17 17-29-29](https://user-images.githubusercontent.com/5928128/196168669-59326518-43e1-4eea-b3f4-45f317aef207.png)

First monitor:

![Screenshot from 2022-10-17 17-27-59](https://user-images.githubusercontent.com/5928128/196168673-71bd89cb-b95f-4595-8767-db8aa1c7c9e4.png)

Second monitor:

![Screenshot from 2022-10-17 17-28-05](https://user-images.githubusercontent.com/5928128/196168671-3c73151d-358f-47f7-a8d4-f0dfccca2c58.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - GNOME Shell version 42
 - Unite version 68
 - MultiMonitor version [b47418b](https://github.com/realh/multi-monitors-add-on/commit/b47418b7a098eb33524116d04e5d563c7e81907d)

**Logs**
[gnome-shell.logs.gz](https://github.com/hardpixel/unite-shell/files/9800104/gnome-shell.logs.gz)

**Comment by RomanValov** [comment]
Just checked same setup on Ubuntu 20.04 / Gnome 3.36. I thought it was working there but actually it behaves almost the same.

However on Ubuntu 20.04 / Gnome 3.36 I'm able to drag maximized window on second monitor by pressing on top bar on second monitor. Since I've configured my gnome terminal not to show title bar it becomes tricky to drag the terminal window once it became maximized on second monitor.

**Comment by mavik** [comment]
I have the same problem.

**Comment by jonian** [comment]
Gnome has broken backwards compatibility for extensions. This extension now supports only gnome 45.
