### ISSUE TITLE
Double title in headerbar apps

### ISSUE THREAD

**Issue by natewind** [hardpixel/unite-shell#311]
When I maximize a window that has a headerbar instead of a titlebar, the same title appears in the headerbar and in the panel. Please consider hiding it in the headerbar (at least as an option).

Ubuntu 20.04
Gnome 3.36.8

**Comment by natewind** [comment]
What does the “invalid” label mean? Is it “can’t reproduce” or “won’t fix”?

**Comment by jonian** [comment]
Hey @natewind, sorry I misread your issue. I thought it was about the buttons.

**Comment by natewind** [comment]
@jonian no problem)
