### ISSUE TITLE
Window title sometimes not showing in the top bar

### ISSUE THREAD

**Issue by LostinSpacetime** [hardpixel/unite-shell#32]
My system:
Ubuntu 18.04 (17.02.2018)
Gnome 3.26
unite-shell V10

Your extension runs very well for the most part, but when I switch windows from the overview, the window title disappears from the top bar.

**Comment by jonian** [comment]
Hi, thank you for your report. Do you have application menu enabled in the top bar?
![screenshot from 2018-02-18 12-24-23](https://user-images.githubusercontent.com/4119508/36350825-7105340a-14a7-11e8-9d76-e0e0a7cd2af0.png)

**Comment by LostinSpacetime** [comment]
No, I wasn't. Now it works perfectly. Thank you!

**Comment by LostinSpacetime** [comment]
It's probably not OK to ask here, but I couldn't find a solution and you might know. In your extension I can activate the system tray in top bar. But when I do (gnome session), the icons don't show a dropdown menu when I click on them. In the ubuntu session it's not necessary to activate system tray and the menus work. I assumed it might be a dconf setting but I couldn't find it. Any Idea how to fix this?

**Comment by jonian** [comment]
This is still a bug, since it is supposed to work even with application menu disabled in the top bar.

**Comment by jonian** [comment]
Ubuntu session, as far as I know, uses [AppIndicator](https://github.com/Ubuntu/gnome-shell-extension-appindicator) for the system tray, so you do not need unite-shell system tray enabled.

Sorry, I do not know how you can fix it. Maybe the AppIndicator extension is causing the conflict.

**Comment by LostinSpacetime** [comment]
Fix works, thank you!
