### ISSUE TITLE
Doesn't work on GNOME 43

### ISSUE THREAD

**Issue by Barugon** [hardpixel/unite-shell#321]
**Describe the bug**
Title says it all. Here's a screenshot of the extension manager:

![Screenshot from 2023-02-26 14-12-58](https://user-images.githubusercontent.com/16503728/221440590-7cb5bd7a-41d1-48b0-8596-f49c3a28de43.png)

**Comment by jonian** [comment]
@Barugon the extension has been compatible with gnome 43 since gnome 43 was released. There might be an issue with the way you installed the extension or an issue with your system. Please install unite from gnome shell extensions website.

**Comment by Barugon** [comment]
Ah, Fedora package is old.
