### ISSUE TITLE
"Hide Window Titlebar" doesn't seem to have any effect on GNOME 44

### ISSUE THREAD

**Issue by rolaca11** [hardpixel/unite-shell#324]
**Describe the bug**
Enabling "Hide Window Titlebar" doesn't seem to have any effect on GNOME 44.

**To Reproduce**
1. Install Fedora 38
2. Enable "Hide Window Titlebar" (any option)
3. Titlebars are unchanged

**Expected behavior**
Titlebars should disappear from apps, like Discord, or IntelliJ

**Screenshots**
![image](https://user-images.githubusercontent.com/3016706/230321094-d4104c7b-fcfa-4cd1-963a-f5c00fa10497.png)
![image](https://user-images.githubusercontent.com/3016706/230322095-080cfd1a-81a2-4fee-bbf2-04a3d179cffb.png)

**Environment (please complete the following information):**
 - OS: Fedora 38
 - GNOME Shell version: 44
 - Unite version: 70

**Logs**
```
-- Boot 6ab9025146134de3a9902d14bc677dc5 --
-- Boot 35f3854a5c7345f983ceba6a48482396 --
Apr 05 14:58:36 MiWiFi-R3600-srv gnome-software[10309]: Failed to run in transient scope: GDBus.Error:org.freedesktop.systemd1.UnitExists: Unit app-flatpak-org.gnome.Extensions-10309.scope was already loaded or has a fragment file.
-- Boot 59841b723fce46658761224cf87bd267 --
-- Boot 2abb1415dc1d4536a573bbfe9aeef1f2 --
Apr 06 08:42:55 MiWiFi-R3600-srv gnome-software[4659]: Failed to run in transient scope: GDBus.Error:org.freedesktop.systemd1.UnitExists: Unit app-flatpak-org.freedesktop.Platform.GL.nvidia\x2d530\x2d30\x2d02-4659.scope was already loade>
Apr 06 08:51:36 MiWiFi-R3600-srv gnome-software[4659]: Failed to run in transient scope: GDBus.Error:org.freedesktop.systemd1.UnitExists: Unit app-flatpak-ca.desrt.dconf\x2deditor-4659.scope was already loaded or has a fragment file.
Apr 06 08:57:14 MiWiFi-R3600-srv gnome-shell[9122]:    creating: /home/ropi/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/
Apr 06 08:57:14 MiWiFi-R3600-srv gnome-shell[9122]:   inflating: /home/ropi/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/panel.js
Apr 06 08:57:14 MiWiFi-R3600-srv gnome-shell[9122]:   inflating: /home/ropi/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/layout.js
Apr 06 08:57:14 MiWiFi-R3600-srv gnome-shell[9122]:   inflating: /home/ropi/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/helper.js
Apr 06 08:57:14 MiWiFi-R3600-srv gnome-shell[9122]:   inflating: /home/ropi/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/window.js
Apr 06 08:57:14 MiWiFi-R3600-srv gnome-shell[9122]:   inflating: /home/ropi/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/prefs.js
Apr 06 08:57:14 MiWiFi-R3600-srv gnome-shell[9122]:   inflating: /home/ropi/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/settings.ui
Apr 06 08:57:14 MiWiFi-R3600-srv gnome-shell[9122]:    creating: /home/ropi/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/styles/
Apr 06 08:57:14 MiWiFi-R3600-srv gnome-shell[9122]:   inflating: /home/ropi/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/styles/spacing-classic.css
Apr 06 08:57:14 MiWiFi-R3600-srv gnome-shell[9122]:   inflating: /home/ropi/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/styles/spacing-legacy.css
Apr 06 08:57:14 MiWiFi-R3600-srv gnome-shell[9122]:    creating: /home/ropi/.local/share/gnome-shell/extensions/unite@hardpixel.eu/schemas/
Apr 06 08:57:14 MiWiFi-R3600-srv gnome-shell[9122]:   inflating: /home/ropi/.local/share/gnome-shell/extensions/unite@hardpixel.eu/schemas/org.gnome.shell.extensions.unite.gschema.xml
Apr 06 08:57:14 MiWiFi-R3600-srv gnome-shell[9122]:   inflating: /home/ropi/.local/share/gnome-shell/extensions/unite@hardpixel.eu/schemas/gschemas.compiled
Apr 06 08:57:14 MiWiFi-R3600-srv gnome-shell[9122]:    creating: /home/ropi/.local/share/gnome-shell/extensions/unite@hardpixel.eu/scripts/
Apr 06 08:57:14 MiWiFi-R3600-srv gnome-shell[9122]:    creating: /home/ropi/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/
```

**Comment by jonian** [comment]
Hey @rolaca11, for flatpak apps check this https://github.com/hardpixel/unite-shell/issues/303#issuecomment-1193269456

**Comment by rolaca11** [comment]
ohh looks like I made a mistake. IntelliJ isn't a flatpak app on my system and still is unaffected

**Comment by jonian** [comment]
How did you install IntelliJ? I have installed Fedora 38 in gnome-boxes and it has only flatpak version. Please provide the output of `xprop` for the IntelliJ window (type xprop in a terminal and the click on the IntelliJ window).

**Comment by emko** [comment]
yea same for me, i am on fedora 38 gnome 44 and both flatpak or native apps title bar always shows on 43 it worked perfect

**Comment by piotrowskiadam** [comment]
I have the opposite problem. I want titlebars to show even when the app is full screen but I cannot and for the apps like VSCode it dissapears in fullscreen. How can I keep the titlebar?
Fullscreen
![image](https://user-images.githubusercontent.com/55131509/233278229-5149acd2-03b2-4646-aa5d-01928812835e.png)
No fullscreen
![image](https://user-images.githubusercontent.com/55131509/233278565-fbe2b30a-6e59-4387-817c-e9db8cd09102.png)

**Comment by rolaca11** [comment]
Looks like I don't have the problem anymore in Ubuntu 23.04

**Comment by Barugon** [comment]
Having the same issue with Fedora 38.

**Comment by developer0108** [comment]
Having the same problem on Fedora 38. The title bar hide function seems to be the only one with no effect.

**Comment by FallingLights** [comment]
@jonian  

`_MOTIF_DRAG_RECEIVER_INFO(_MOTIF_DRAG_RECEIVER_INFO) = 0x6c, 0x0, 0x5, 0x0, 0x4c, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0
XdndAware(ATOM) = BITMAP
_GTK_EDGE_CONSTRAINTS(CARDINAL) = 170
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_MUTTER_NEEDS_FRAME(CARDINAL) = 1
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
_NET_WM_USER_TIME(CARDINAL) = 3428717
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_MOTIF_WM_HINTS(CARDINAL) = 2, 0, 2, 0, 0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_FOCUSED
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 74, 0
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		Initial state is Normal State.
_NET_WM_ICON(CARDINAL) = 	Icon (128 x 128):
	(not shown)

_NET_WM_PID(CARDINAL) = 21241
WM_CLIENT_MACHINE(STRING) = "fedora-local"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS
WM_CLASS(STRING) = "jetbrains-goland", "jetbrains-goland"
WM_CLIENT_LEADER(WINDOW): window id # 0x1000030
_NET_WM_ICON_NAME(UTF8_STRING) = "Vector_Clock"
WM_ICON_NAME(STRING) = "Vector_Clock"
_NET_WM_NAME(UTF8_STRING) = "Vector_Clock"
WM_NAME(STRING) = "Vector_Clock"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 538, 64
		program specified location: 538, 64
		program specified size: 2800 by 1926
		program specified minimum size: 680 by 0
		window gravity: NorthWest`

**Comment by denis3509** [comment]
same issue on 23.04

here is syslog: 

> 2023-05-06T13:23:13.848218+03:00 denis-pc gnome-shell[5497]: Could not create transient scope for PID 68253: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 68253 does not exist.
> 2023-05-06T13:23:13.873772+03:00 denis-pc gnome-shell[5497]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55e634412500] is on because it needs an allocation.
> 2023-05-06T13:23:13.873842+03:00 denis-pc gnome-shell[5497]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55e63baac5b0] is on because it needs an allocation.

**Comment by jonian** [comment]
I can't replicate the issue on Gnome 44 on arch linux, fedora 38 or ubuntu 23.04.

**Comment by Barugon** [comment]
Version 71 update fixed it for me.

**Comment by Neo-29** [comment]
not working here on archlinux

**Comment by denis3509** [comment]
This fixed it for me:
1.  Uninstall extension
2. Remove the unite settings keys  using desktop config editor
3. Install extension again 
![Снимок экрана от 2023-05-09 19-46-47](https://github.com/hardpixel/unite-shell/assets/19351927/96b96500-ec1e-49f9-9b3a-b3618ec51c0e)

On the picture you can see that every setting has label "schema not found"
[](url)

**Comment by wengole** [comment]
I too am having this issue, although it's working for maximised windows, but nothing else

**Comment by emko** [comment]
was working on 44 up until today, not sure what changed but all my windows have title bars now :(

**Comment by wep777** [comment]
> This fixed it for me:
> 
> 1. Uninstall extension
> 2. Remove the unite settings keys  using desktop config editor
> 3. Install extension again

unfortunately on updated Fedora 38 these steps did not help

**Comment by cwells** [comment]
> ![Снимок экрана от 2023-05-09 19-46-47](https://user-images.githubusercontent.com/19351927/237166445-96b96500-ec1e-49f9-9b3a-b3618ec51c0e.png)
> 
> On the picture you can see that every setting has label "schema not found"
> 
> This fixed it for me:
> 
> 1. Uninstall extension
> 2. Remove the unite settings keys  using desktop config editor
> 3. Install extension again

Tried this, but dconf always shows "Schema not found" and apps like vscode and slack have titlebars. Fedora 38/GNOME 44.1

**Comment by Barugon** [comment]
I installed this on my notebook but it won't let me enable the plugin. Strangely, the title bar is hidden even without having the plugin enabled (which is wrong) but other features don't work (like having the window buttons in the top bar).

**Comment by cwells** [comment]
For those scrambling for a solution, I installed 

https://extensions.gnome.org/extension/4630/no-titlebar-when-maximized/

and this fixed the issue for me, although, as the name suggests, it's not as configurable as Unite.

**Comment by hyperair** [comment]
This was working for me on 44.0, but it stopped working on 44.1. Checking with xprop, it looks like `_MOTIF_WM_HINTS` is being set correctly to `0x2, 0x0, 0x2, 0x0, 0x0`, but gnome-shell seems to be ignoring that hint now.

Taking a hint from https://github.com/velitasali/gtktitlebar/issues/36#issuecomment-1455278899, I tried changing `_HIDE_FLAGS` like so. Now window decorations disappear, but don't come back. :confused: 


```diff
diff --git a/unite@hardpixel.eu/window.js b/unite@hardpixel.eu/window.js
index f7ae532..87e6f18 100644
--- a/unite@hardpixel.eu/window.js
+++ b/unite@hardpixel.eu/window.js
@@ -19,7 +19,7 @@ const VALID_TYPES = [
 const MOTIF_HINTS = '_MOTIF_WM_HINTS'
 
 const _SHOW_FLAGS = ['0x2', '0x0', '0x1', '0x0', '0x0']
-const _HIDE_FLAGS = ['0x2', '0x0', '0x2', '0x0', '0x0']
+const _HIDE_FLAGS = ['0x2', '0x0', '0x0', '0x0', '0x0']
 
 function isValid(win) {
   return win && VALID_TYPES.includes(win.window_type)

```

**Comment by olivertzeng** [comment]
same issue

**Comment by Lcchy** [comment]
Same for me, but the proposed PR (https://github.com/hardpixel/unite-shell/pull/334) by @hyperair  fixed it for me, thanks!

**Comment by cwells** [comment]
Mine's been working fine since some recent update (I think GNOME, not Unite).

**Comment by jonian** [comment]
Gnome has broken backwards compatibility for extensions. This extension now supports only gnome 45.

**Comment by koppor** [comment]
IntelliJ still shows the window title bar with v77

![image](https://github.com/hardpixel/unite-shell/assets/1366654/d30f6b3f-48d9-4870-9d7c-e444bf8c7fc7)

Should I open a new issue? @jonian

**Comment by Neo-29** [comment]
It never worked since gnome 45...

**Comment by koppor** [comment]
I played around with other configuration options, restarted IntelliJ. And now it works great!

![image](https://github.com/hardpixel/unite-shell/assets/1366654/1fa3ba00-8fd9-45f2-8fc3-34be8c3bb916)

Great suff :)
