### ISSUE TITLE
Unity shell tray icons

### ISSUE THREAD

**Issue by oveeauki** [hardpixel/unite-shell#327]
[screenshot](https://cdn.discordapp.com/attachments/667446707826458654/1104562182894657577/image.png)

 - OS: [Arch Linux LTS-kernel]
 - GNOME Shell version [44.1]
 - Unite version [70]

System tray icons look visually bugged after update of gnome shell

**Comment by gzpr** [comment]
I'm also on arch and while the 71 update seems to have fixed the icons being distorted they still lack [transparency](https://i.imgur.com/d6bkSNx.png)

**Comment by jonian** [comment]
@gzpr gnome has changed the implementation for the tray as you can see [here](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2590). I can't do anything to fix the transparency. You should open an issue in the gnome issue tracker.

**Comment by oveeauki** [comment]
for me all fine almost now expect this little visual detail you can see there. can it be fixed? ![ss](https://cdn.discordapp.com/attachments/896192123324497921/1104877705201188894/image.png)

**Comment by jonian** [comment]
@oveeauki that is the missing transparency issue. It can't be fixed in the extension.

**Comment by gzpr** [comment]
@jonian Is it even worth it since tray icons aren't technically even supported by gnome? Breaking things for no reason, classic gnome devs I guess.

**Comment by oveeauki** [comment]
> @oveeauki that is the missing transparency issue. It can't be fixed in the extension.

okok so its like gnome shell thing? i always love this so much when updating to newer gnome and it breaking stuff like this xd

**Comment by jonian** [comment]
Yes, it is a gnome shell thing.
