### ISSUE TITLE
Window buttons are always visible on the top bar

### ISSUE THREAD

**Issue by LostinSpacetime** [hardpixel/unite-shell#33]
After returning from overview mode, the window buttons are always visible in the top bar, except if I chose to never show them in the options.
This issue appeared after updating Gnome-Shell to 3.28 (3.27.92).
I am using unite-shell form git with Ubuntu 18.04.

**Comment by jonian** [comment]
Hi @LostinSpacetime. Can you test the latest version from master branch?
If the issue is still present, please upload a screenshot with your settings.

**Comment by LostinSpacetime** [comment]
It's fixed! Also.. nice update. Thank you! :)

**Comment by jonian** [comment]
Thanks!
