### ISSUE TITLE
Hide window titlebars doesn't work for tiled windows in Gnome 44

### ISSUE THREAD

**Issue by prurigro** [hardpixel/unite-shell#333]
**Describe the bug**

The setting to hide window titlebars works great for maximized apps, and they're always hidden if it's set to `Always`. If the setting is set to `Both` or `Tiled` however, tiling the windows doesn't hide the titlebars.

**To Reproduce**

1. Ensure Gnome 44 is installed
2. Configure `Hide window titlebars` to either `Tiled` or `Both`
3. Reload the shell (the setting doesn't update on the fly)
4. Open an app that uses server-side decorations
5. Tile the app (either side of the screen will do)
6. The decorations are still present

**Expected behavior**

The decorations should be hidden while tiled

**Environment (please complete the following information):**
 - OS: Arch Linux (up to date)
 - GNOME Shell version 44
 - Unite version 71

**Logs**

Nothing appears to get logged when tiling or maximizing windows.

**Additional context**

I can provide some if this isn't easily reproduced

**Comment by medigencedev** [comment]
so to be specific it is not working with GNOME44.2

**Comment by prurigro** [comment]
Yeah, sorry- I should have specified 44.2 since I can't confirm it wasn't working on previous versions.

**Comment by mogorman** [comment]
doesn't work on gnome 44.1 on my install.

**Comment by harpreetsb** [comment]
any update on fix?

**Comment by phamson02** [comment]
I tried to follow the fix as in this [pull request ](https://github.com/hardpixel/unite-shell/pull/334) and it works. I am on Gnome 44.2.

**Comment by medigencedev** [comment]
now what happens is, when you login back after your screen sleeps, the windows are unmaximized.

**Comment by jonian** [comment]
This and is a mutter issue and probably #324 too. The PR #334 is not the best solution since it has it's own issues. I have reported this [upstream](https://gitlab.gnome.org/GNOME/mutter/-/issues/2912).

**Comment by jonian** [comment]
Gnome has broken backwards compatibility for extensions. This extension now supports only gnome 45.
