### ISSUE TITLE
icon menu shows on other side of screen

### ISSUE THREAD

**Issue by cshellen2** [hardpixel/unite-shell#337]
**Describe the bug**
when you right click on the systemtray icon of any app(system tray on right side) the menu will appear on the left side of the screen.

**To Reproduce**
right click on the icon

**Expected behavior**
menu should show up underneath the icon, not the other side of screen
![corectrl_submenu_wrong_side](https://github.com/hardpixel/unite-shell/assets/142510780/ca421902-3845-4590-a6c5-2a9ad21f8939)
![pia_internet](https://github.com/hardpixel/unite-shell/assets/142510780/77a13656-7f44-437e-9e09-d6deb50b7bed)

**Screenshots**
2 examples attached

**Environment (please complete the following information):**
 - OS: Fedora Linux 38 (Workstation Edition)
 - GNOME Shell version [44.3]
 - Unite version [72]

**Logs**
Provide system logs related to unite extension using `[unite.txt](https://github.com/hardpixel/unite-shell/files/12369913/unite.txt)`.

**Additional context**

**Comment by cshellen2** [comment]
![settings-1](https://github.com/hardpixel/unite-shell/assets/142510780/d71567ae-0668-4287-af8c-094be3527234)
![settings-2](https://github.com/hardpixel/unite-shell/assets/142510780/c74d4e25-ef0f-4c42-9945-435a0bf4dcc5)

**Comment by jonian** [comment]
This issue is not coming from the extension. Gnome changed their implementation of SystemTray and broke the icons sizing, transparent background and menu position. Please report this on Gnome bug tracker. Nothing can be done here to fix this.
