### ISSUE TITLE
[Possible bug, support] Element flatpak titlebar isn't hiding

### ISSUE THREAD

**Issue by 42Willow** [hardpixel/unite-shell#347]
All the other titlebars are gone, but element's blinding one is still there..
![image](https://github.com/hardpixel/unite-shell/assets/70784752/65766009-6c4b-4584-88f8-3e622646a041)

**Comment by jonian** [comment]
Hi @42Willow, have you tried https://github.com/hardpixel/unite-shell/issues/303#issuecomment-1193269456?

**Comment by 42Willow** [comment]
No I haven't, just uninstalled the flatpak and installed it from the opensuse website (on fedora? since when?) and the titlebar is gone.. now I'll uninstall it and reinstall the flatpak and try it out

**Comment by 42Willow** [comment]
Nope, didn't work.
