### ISSUE TITLE
ugly buttons on v12

### ISSUE THREAD

**Issue by UaHummer** [hardpixel/unite-shell#35]
after upgrade (v12,v13) buttons looks ugly. all fine on v11

![2018-03-20 20-41-23](https://user-images.githubusercontent.com/321529/37676074-9499e75e-2c7f-11e8-8906-fa1ce9736fae.png)

Gnome-Shell 3.28.0
Ubuntu 18.04

**Comment by jonian** [comment]
Thank you for the report. What GTK theme are you using?

**Comment by UaHummer** [comment]
Ark-Dark

**Comment by jonian** [comment]
And gnome-shell theme?

**Comment by UaHummer** [comment]
same

**Comment by jonian** [comment]
Try latest version from master branch. It looks fine for me.
![screenshot from 2018-03-20 20-54-56](https://user-images.githubusercontent.com/4119508/37676644-247aa8a8-2c81-11e8-9f7c-af5b3266cb21.png)

**Comment by UaHummer** [comment]
nope, work only on v11

**Comment by jonian** [comment]
Maybe some other extension is causing it. Sorry cannot reproduce.

**Comment by UaHummer** [comment]
Disable all extension, enable default theme, restart gnome-shell. Same ugly buttons

**Comment by jonian** [comment]
I will create a branch with a potential fix. Will you be able to test it? 
I do not have ubuntu installed. Maybe it is ubuntu related.

**Comment by UaHummer** [comment]
ok

**Comment by jonian** [comment]
It is ready https://github.com/hardpixel/unite-shell/tree/fix_ugly_window_buttons

**Comment by UaHummer** [comment]
it did not work

**Comment by jonian** [comment]
I installed ubuntu 18.04 in gnome boxes and I still cannot reproduce.
![screenshot from 2018-03-20 22-41-08](https://user-images.githubusercontent.com/4119508/37681665-05433d60-2c90-11e8-85a4-aaf30e95e7cf.png)

**Comment by jonian** [comment]
This is happening in gnome classic session. Fixed now.
