### ISSUE TITLE
Unite doesn't show up among extensions

### ISSUE THREAD

**Issue by glow12121** [hardpixel/unite-shell#354]
**Describe the bug**
I've followed Hardpixel's guide, but Unite is still not among Gnome's extensions. ('xprop' is already installed.)

**To Reproduce**
1. Follow the guide
2. Open Extensions program
3. Unite is not among extensions

**Expected behavior**
The plugin appears in Extensions program.

**Screenshots**

![image](https://github.com/hardpixel/unite-shell/assets/29035180/e11883da-823c-4b2c-8a3f-ba2f427b9ccb)

![image](https://github.com/hardpixel/unite-shell/assets/29035180/c227c619-ac21-4f71-a521-97b6bcedb7e0)

![image](https://github.com/hardpixel/unite-shell/assets/29035180/9ec29932-df6b-4a97-aa87-29218c4c4ff0)

**Environment (please complete the following information):**
 - OS: Fedora 39 Workstation
 - GNOME Shell version 45

**Comment by jonian** [comment]
Hi @glow12121, you should place the folder `unite@hardpixel.eu` in the `~/.local/share/gnome-shell/extensions` folder. The readme instructions need updating.

**Comment by glow12121** [comment]
@jonian Thanks, the extension works now. In my case, a reboot was needed before Extensions program recognized the plugin.
