### ISSUE TITLE
Title Bars not properly hidden on Wayland

### ISSUE THREAD

**Issue by Redoxahmii** [hardpixel/unite-shell#358]
**Describe the bug**
The titlebar is not being hidden on Wayland for some applications

**To Reproduce**
1. Install Neovide 
2. Open it and see that the windows top bar does not disappear.
3. Works fine on Xorg.

**Expected behavior**
display no titlebar

**Screenshots**

**On Wayland**

![Screenshot from 2023-12-05 01-57-44](https://github.com/hardpixel/unite-shell/assets/13983258/31345342-8f53-4377-9e2e-a925ebec9d0e)
**On Xorg**

![Screenshot from 2023-12-05 02-07-29](https://github.com/hardpixel/unite-shell/assets/13983258/82b0489d-96fb-459f-9bf5-ed0097d66e8e)

**Environment (please complete the following information):**
 - OS: Arch Linux
 - GNOME Shell Version: 45.2
 - Unite version : 77

**Logs**
`Dec 04 17:08:17 Ahmii gnome-shell[686]: Extension unite@hardpixel.eu already installed in /usr/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
Dec 05 01:27:26 Ahmii gnome-shell[1437]: Can't update stage views actor <unnamed>[<Gjs_unite_hardpixel_eu_buttons_UniteTrayIndicator>:0x5578b049cc00] is on because it needs an allocation.
Dec 05 01:28:01 Ahmii gnome-shell[98032]: Extension unite@hardpixel.eu already installed in /usr/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded`

**Additional context**

**Comment by jonian** [comment]
Hi @Redoxahmii, thanks for the report. On wayland only GTK apps are supported (using css), apps that use libdecor and Xwayland apps.

Neovide uses [winit](https://github.com/rust-windowing/winit) which does not use standard decorations, neither libdecor, but a custom implementation, as you can see at rust-windowing/winit#1967.

The only way to make the decorations removal work on wayland is to run neovide in xwayland mode:
```
WINIT_UNIX_BACKEND=x11 neovide
```

If you want you can add the env variable above in `/etc/environment` and any app that uses winit will run in xwayland mode without having to set the variable every time you run it.

**Comment by Redoxahmii** [comment]
Thank you for responding. changing this has made it indeed work properly.
Thank you again.

**Comment by Redoxahmii** [comment]
> Hi @Redoxahmii, thanks for the report. On wayland only GTK apps are supported (using css), apps that use libdecor and Xwayland apps.
> 
> Neovide uses [winit](https://github.com/rust-windowing/winit) which does not use standard decorations, neither libdecor, but a custom implementation, as you can see at [rust-windowing/winit#1967](https://github.com/rust-windowing/winit/issues/1967).
> 
> The only way to make the decorations removal work on wayland is to run neovide in xwayland mode:
> 
> ```
> WINIT_UNIX_BACKEND=x11 neovide
> ```
> 
> If you want you can add the env variable above in `/etc/environment` and any app that uses winit will run in xwayland mode without having to set the variable every time you run it.


Hey this method does not seem to be working anymore.
I reinstalled neovide and now it is again not working.
Is there someway to verify if it is being run X11 or not.

Below is the /etc/environment file 
```sh
#
# This file is parsed by pam_env module
#
# Syntax: simple "KEY=VAL" pairs on separate lines
#
QT_QPA_PLATFORMTHEME=qt5ct
#QT_STYLE_OVERRIDE=kvantum
BROWSER=firefox
EDITOR=nvim
WINIT_UNIX_BACKEND=x11 neovide
```
