### ISSUE TITLE
Problem with Pop!_OS distro

### ISSUE THREAD

**Issue by yuritoledo** [hardpixel/unite-shell#36]
Hello,

It's probably a problem in the Pop!_OS distro, but I will comment here with you.
When Pop! _OS returns from the lock screen or suspend, your extension is disabled, having to restart the Gnome Shell, to it works again.

Do you have an idea why?

Extensions like Pixel Saver, doesnt break after suspend / lock screen.

But i prefer your extension, its so far, better and complete.

**Comment by jonian** [comment]
Hi,

Could you provide info for versions:
- Pop!_OS
- Unite
- Gnome Shell

Also provide the output of `journalctl -r /usr/bin/gnome-shell | grep unite`. Thanks!

**Comment by yuritoledo** [comment]
I dont have access to my notebook now, but I open a issue to Pop guys

NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

About Unite, I used the github version then extensions.gnome.org version 


This helps you ?

**Comment by jonian** [comment]
I tried Pop!_OS in gnome boxes with unite v14 and it works without problems.

Download it from here https://github.com/hardpixel/unite-shell/releases/download/v14/unite-shell-v14.zip and test it.

**Comment by yuritoledo** [comment]
omg

ok, I will try it when I back home

Thanks fot attention :)

**Comment by yuritoledo** [comment]
Hi @jonian 

I've found the problem. It happens only when the  [User Themes](https://extensions.gnome.org/extension/19/user-themes/) is ON. Its a Pop bug. But it affects your extensions.

Can I suggest another thing?Can you add to the extension, the power to reduce the topbar height? Some it's so high.

Thanks.

**Comment by jonian** [comment]
Hi @yuritoledo 

I tried with the User Themes anabled and still can't reproduce the issue.
As for the topbar (gnome shell panel?) please open a new issue as feature request.

**Comment by yuritoledo** [comment]
Oh, ok man

Thanks to attention.
