### ISSUE TITLE
GNOME 45 + unite-shell 77 crash

### ISSUE THREAD

**Issue by dgutov** [hardpixel/unite-shell#360]
**Describe the bug**

I've been getting some crashes lately, but they occur randomly. But that happened several times today, so far.

**To Reproduce**

The last time it happened, was after I pressed the `Win` button on the keyboard, which usually invokes dash, but caused the crash instead.

No reliable repro: after the restart, I've pressed the same button a few times, and the dash displays normally. Not all the same applications are running yet, though.

**Screenshots**
Not applicable.

**Environment (please complete the following information):**
 - OS: Ubuntu 23.10
 - GNOME Shell version: 45.1
 - Unite version: 77

**Logs**
Provide system logs related to unite extension using `journalctl -g unite`.

Here's the earlier entry from journalctl around the beginning of the crash:

```
Dec 26 23:36:07 potemkin gnome-shell[8950]: GNOME Shell crashed with signal 11
Dec 26 23:36:07 potemkin gnome-shell[8950]: == Stack trace for context 0x558e312e0e30 ==
Dec 26 23:36:07 potemkin gnome-shell[8950]: #0   558e313a3668 i   file:///home/dgutov/.local/share/gnome-shell/extensions/unite@hardpixel.eu/panel.js:350 (380549de5380 @ 36)
Dec 26 23:36:07 potemkin gnome-shell[8950]: #1   558e313a35c0 i   file:///home/dgutov/.local/share/gnome-shell/extensions/unite@hardpixel.eu/panel.js:364 (380549de53d0 @ 134)
Dec 26 23:36:07 potemkin gnome-shell[8950]: #2   558e313a3538 i   resource:///org/gnome/shell/ui/panel.js:674 (8f9f9510880 @ 17)
Dec 26 23:36:07 potemkin gnome-shell[8950]: #3   7ffcaef58ca0 b   resource:///org/gnome/gjs/modules/core/_signals.js:130 (1cbbfd6956f0 @ 126)
Dec 26 23:36:07 potemkin gnome-shell[8950]: #4   7ffcaef58d80 b   resource:///org/gnome/gjs/modules/core/_signals.js:119 (1cbbfd695600 @ 286)
Dec 26 23:36:07 potemkin gnome-shell[8950]: #5   558e313a3490 i   resource:///org/gnome/shell/ui/overview.js:314 (144b21877240 @ 282)
Dec 26 23:36:07 potemkin gnome-shell[8950]: #6   558e313a3400 i   resource:///org/gnome/shell/ui/overview.js:578 (144b218779c0 @ 244)
Dec 26 23:36:07 potemkin gnome-shell[8950]: #7   558e313a3360 i   resource:///org/gnome/shell/ui/overview.js:560 (144b21877970 @ 253)
Dec 26 23:36:07 potemkin gnome-shell[8950]: #8   558e313a32c0 i   resource:///org/gnome/shell/ui/overview.js:666 (144b21877bf0 @ 87)
Dec 26 23:36:07 potemkin gnome-shell[8950]: #9   558e313a3208 i   resource:///org/gnome/shell/ui/overviewControls.js:443 (144b2187b740 @ 396)
Dec 26 23:36:07 potemkin gnome-shell[8950]: #10   558e313a3178 i   resource:///org/gnome/shell/ui/init.js:21 (1cbbfd670ba0 @ 48)
```

`journalctl -g unite`, OTOH, only says this:

```
Dec 26 23:36:07 potemkin gnome-shell[8950]: #0   558e313a3668 i   file:///home/dgutov/.local/share/gnome-shell/extensions/unite@hardpixel.eu/panel.js:350 (380549de5380 @ 36)
Dec 26 23:36:07 potemkin gnome-shell[8950]: #1   558e313a35c0 i   file:///home/dgutov/.local/share/gnome-shell/extensions/unite@hardpixel.eu/panel.js:364 (380549de53d0 @ 134)
Dec 26 23:37:08 potemkin kernel: audit: type=1400 audit(1703626628.061:243): apparmor="DENIED" operation="open" class="file" profile="snap.snapd-desktop-integration.snapd-desktop-in>
Dec 26 23:37:08 potemkin snapd-desktop-i[15162]: Theme parsing error: gtk.css:2:122: Failed to import: Error opening file /home/dgutov/.local/share/gnome-shell/extensions/unite@hard>
```

(The last entry before that is from 22:42:32).

**Additional context**

For your convenience, the last two steps in the backtrace are
https://github.com/hardpixel/unite-shell/blob/6028bcbd39fb5a3e1b202e9e3176b8978dac0827/unite%40hardpixel.eu/panel.js#L364
and
https://github.com/hardpixel/unite-shell/blob/6028bcbd39fb5a3e1b202e9e3176b8978dac0827/unite%40hardpixel.eu/panel.js#L350

I'll see if any subsequent crashes also have this backtrace, or a different one.

Other extensions I have enabled are: `Block Caribou 36`, `Dash to Dock 89`, `Light Shell 22` (no JS in there) and Ubuntu's built-in `Ubuntu Appindicators` and `Ubuntu Tiling Assistant 44`.

**Comment by dgutov** [comment]
I've just seen this again. Also after pressing `Win`.

Note that my GNOME Shell has been fairly unstable lately (basically after the upgrade to 23.10), so I'm not sure how much of the blame should be placed at this extension in particular.

There had been other crashes as well (just today), and they looked differently (e.g. a "general protection error" in libgobject).

**Comment by jonian** [comment]
Hi @dgutov, thanks for the report. I have not been able to reproduce this on arch linux. This is a weird issue because the removal of a style class name should not crash the shell. If you manage to find a way to replicate this, please let me know.

**Comment by dgutov** [comment]
Hi @jonian, thank you for the response. I fully agree that this shouldn't crash the shell (no GNOME extension should be able to, aside from some OOM, I guess). I figured you might see something useful in this backtrace, but it's okay if not.

As you can see above, I've been battling some general instability with GNOME, and I think I have found the culprit now - and it's a different extension, one that looked the most harmless because it has almost zero JS code inside (just a theme file). I'm working on filing a proper report for it, and I suppose we can close this issue now. I'll reopen if I see this again and manage to gather more information.
