### ISSUE TITLE
Support for GNOME 46

### ISSUE THREAD

**Issue by Froggy232** [hardpixel/unite-shell#362]
Hi,
Is it planned to port the extension to gnome 46?
Thanks for your work

**Comment by jonian** [comment]
Hi @Froggy232, the extension v78 already supports gnome 46 but it is not released any more on gnome extensions website. You have to install it manually from [here](https://github.com/hardpixel/unite-shell/releases).

**Comment by Neo-29** [comment]
gnome 47 needs some ajustments
though working
![image](https://github.com/user-attachments/assets/f41872d8-6892-4e5a-af83-74ffefe153ae)

**Comment by jonian** [comment]
@Neo-29 the extension has been updated for gnome 47 (v79) and I have found only 1 bug. What are the issues?

**Comment by Neo-29** [comment]
> @Neo-29 the extension has been updated for gnome 47 (v79) and I have found only 1 bug. What are the issues?

I may be on 78.
Otherwise, apart from the slider (image), everything is ok

**Comment by Neo-29** [comment]
same issue on 79 as soon as a modification or any extension is updated or new installed...

![image](https://github.com/user-attachments/assets/b3935c68-ed49-4da1-bf30-99c6277867c9)

Now it's in addition ,broken

**Comment by jonian** [comment]
@Neo-29 if you don't provide any logs there is no way someone can help you. Also this looks like there are some issues with your gnome install and not the extensions themselves.

An extension declares in metadata.json what gnome versions it supports. If your gnome version is not declared there, the extension appears incompatible. To see if an extension has an error you should check the logs, for example to get unite logs use:
```bash
journalctl -g unite
```
If you want to see the log in real time, use:
```bash
journalctl -g unite -f
```

**Comment by jonian** [comment]
@Neo-29 Also if you are on arch linux, you should use the [aur package](https://aur.archlinux.org/packages/gnome-shell-extension-unite) to get automatic updates.
```bash
yay -S gnome-shell-extension-unite
```

**Comment by Neo-29** [comment]
> @Neo-29 if you don't provide any logs there is no way someone can help you. Also this looks like there are some issues with your gnome install and not the extensions themselves.
> 
> An extension declares in metadata.json what gnome versions it supports. If your gnome version is not declared there, the extension appears incompatible. To see if an extension has an error you should check the logs, for example to get unite logs use:
> 
> ```shell
> journalctl -g unite
> ```
> 
> If you want to see the log in real time, use:
> 
> ```shell
> journalctl -g unite -f
> ```

```Extension unite@hardpixel.eu: TypeError: dockManager is null

                                           Stack trace:
                                             getApps@file:///home/neo29/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locations.js:1489:9
                                             getRunningApps@file:///home/neo29/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locations.js:1502:12
                                             get@file:///home/neo29/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1890:59
                                             get focusApp@file:///home/neo29/.local/share/gnome-shell/extensions/unite@hardpixel.eu/window.js:349:26
                                             get focusApp@file:///home/neo29/.local/share/gnome-shell/extensions/unite@hardpixel.eu/extension.js:38:5
                                             _syncState@file:///home/neo29/.local/share/gnome-shell/extensions/unite@hardpixel.eu/panel.js:107:21
                                             activate@file:///home/neo29/.local/share/gnome-shell/extensions/unite@hardpixel.eu/panel.js:75:10
                                             onChange@file:///home/neo29/.local/share/gnome-shell/extensions/unite@hardpixel.eu/handlers.js:289:24
                                             add/feature._doActivate@file:///home/neo29/.local/share/gnome-shell/extensions/unite@hardpixel.eu/handlers.js:300:7
                                             activate/<@file:///home/neo29/.local/share/gnome-shell/extensions/unite@hardpixel.eu/handlers.js:312:46
                                             activate@file:///home/neo29/.local/share/gnome-shell/extensions/unite@hardpixel.eu/handlers.js:312:19
                                             activate@file:///home/neo29/.local/share/gnome-shell/extensions/unite@hardpixel.eu/panel.js:773:21
                                             enable@file:///home/neo29/.local/share/gnome-shell/extensions/unite@hardpixel.eu/extension.js:18:23
                                             _callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:227:55
                                             _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:637:24
                                             async*_onUserExtensionsEnabledChanged@resource:///org/gnome/shell/ui/extensionSystem.js:603:20
                                             _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:735:18
                                             createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730:46
                                             set UserExtensionsEnabled@resource:///org/gnome/shell/ui/shellDBus.js:486:25
                                             _handlePropertySet@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:395:35
                                             _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:414:35
                                             @resource:///org/gnome/shell/ui/init.js:21:20```

**Comment by jonian** [comment]
@Neo-29 looks like an issue with your system/install. To make sure that it is not an issue with unite, remove unite and re-install v80:

```bash
gnome-extensions uninstall unite@hardpixel.eu

wget https://github.com/hardpixel/unite-shell/releases/download/v80/unite-v80.zip
gnome-extensions install unite-v80.zip
```
Disable all other extensions and check the logs for unite errors. If you are still having problems, open a new issue and fill all the info required in the issue template.

**Comment by Neo-29** [comment]
I already did all that.
I'll go with AUR version and check.

**Comment by korason7117** [comment]
not working for me.
Windows> Titlebars>Hide titlebars (select Maximized)
uptodate archlinux system and unite ver 80.
