### ISSUE TITLE
Gnome 46 wayland does not hide tittle bar

### ISSUE THREAD

**Issue by psyhlo** [hardpixel/unite-shell#366]
**Describe the bug**
After updating to latest release of Manjaro Linux (update not fresh install)
Unite stopped hiding the tittle bar

**Screenshots**
![image](https://github.com/hardpixel/unite-shell/assets/1803170/f3d94bb3-4e5c-4743-897e-3551203c96a5)

**Environment (please complete the following information):**
 - OS: Manjaro Linux 24
 - GNOME Shell version 46
 - Unite version 78

**Logs**
Provide system logs related to unite extension using `journalctl -g unite`.
the log is empty

**Additional context**
# System Details Report
---

## Report details
- **Date generated:**                              2024-05-16 12:03:52

## Hardware Information:
- **Hardware Model:**                              ASRock X570 Steel Legend
- **Memory:**                                      32,0 GiB
- **Processor:**                                   AMD Ryzen™ 9 5900X × 24
- **Graphics:**                                    AMD Radeon™ RX 6650 XT
- **Disk Capacity:**                               1,0 TB

## Software Information:
- **Firmware Version:**                            P5.50
- **OS Name:**                                     Manjaro Linux
- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.9.0-1-MANJARO

**Comment by psyhlo** [comment]
after installing wlprop - found it after many hours of searching
Everything is back to normal.
Sorry for the spam

**Comment by psyhlo** [comment]
Something strange happened and again not hiding the title bar
this is the output from: journalctl -g unite.
`май 16 09:29:59 StarCaster gnome-shell[1291]: Extension unite@hardpixel.eu already installed in /usr/share/gnome-shell/extensions/unite@hardpixel.eu. /usr/share/gnome-shell/extensions/unite@hardpixel.eu will not be loaded
май 16 10:30:01 StarCaster mx-extract[3930]: Failed to parse DIDL-Lite: No 'DIDL-Lite' node in the DIDL-Lite XML:
                                                <?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns2:repository xmlns:ns2="http://schemas.android.com/repository/android/common/02" xmlns:ns3="http://schemas.android.com/repository/android/common/01" xmlns:ns4="http://schemas.>
                                                
                                                This is the Android Software Development Kit License Agreement
                                                
                                                1. Introduction
                                                
                                                1.1 The Android Software Development Kit (referred to in the License Agreement as the "SDK" and specifically including the Android system files, packaged APIs, and Google APIs add-ons) is licensed to you subject to the terms of the L>
                                                
                                                1.2 "Android" means the Android software stack for devices, as made available under the Android Open Source Project, which is located at the following URL: http://source.android.com/, as updated from time to time.
                                                
                                                1.3 A "compatible implementation" means any Android device that (i) complies with the Android Compatibility Definition document, which can be found at the Android compatibility website (http://source.android.com/compatibility) and wh>
                                                
                                                1.4 "Google" means Google Inc., a Delaware corporation with principal place of business at 1600 Amphitheatre Parkway, Mountain View, CA 94043, United States.
`

**Comment by neopostmodern** [comment]
I'm facing the same issue (titlebar not hidden) after updating Manjaro. Did you install the `wlprop` from AUR?
Ideally the extension could warn users that something is broken if `wlprop` or whatever is necessary for the user's machine is missing?

**Comment by psyhlo** [comment]
Yes I have it installed wlprop
And again something strange happened 
After removing unite-shell and installing it again everything start to work again
