### ISSUE TITLE
Gap between the left border and the first button of the "header bar"

### ISSUE THREAD

**Issue by JeanValjean30** [hardpixel/unite-shell#367]
Hi,

In some apps (e.g. files, contacts, clocks, errands, celluloid, clover, komikku, cartdriges, flatseal), when a window is maximized, there is a gap between the left border and the first element like the "backward button" in "files".  

**Expected behavior**
The first element of the "header bar" next to the left border.

**Screenshots**
![Schermata del 2024-05-27 09-54-05](https://github.com/hardpixel/unite-shell/assets/168914674/f41fb6c9-41a4-45b5-a955-7f80f0952ea1)

**Environment (please complete the following information):**
 - OS: Debian 12
 - GNOME Shell version: 43.9
 - Unite version: 72

**Logs**
`Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
-- Boot 6ff007fe451a42af8f4c5fe7d11a4bba --
-- Boot 89f1d537a90646c8924a4972e6d0b6c5 --
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/s>
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/s>
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/s>
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/s>
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/s>
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/s>
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/s>
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/s>
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/s>
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/s>
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/s>
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/s>
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/s>
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/s>
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/s>
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/s>
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/s>
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/s>
lines 1-20...skipping...
-- Boot 6ff007fe451a42af8f4c5fe7d11a4bba --
-- Boot 89f1d537a90646c8924a4972e6d0b6c5 --
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/panel.js
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/layout.js
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/helper.js
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/window.js
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/prefs.js
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/settings.ui
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/styles/
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/styles/spacing-classic.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/overrides/styles/spacing-legacy.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/schemas/
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/schemas/org.gnome.shell.extensions.unite.gsche>
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/schemas/gschemas.compiled
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/scripts/
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-left/
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-left/both.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-left/always.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-left/maximized.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-left/tiled.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-right/
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-right/both.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-right/always.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-right/maximized.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk4/buttons-right/tiled.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-left/
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-left/both.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-left/always.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-left/maximized.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-left/tiled.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-right/
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-right/both.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-right/always.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-right/maximized.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-right/tiled.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/shell/
mag 25 15:05:02 XPS9370 gnome-shell[79874]:   inflating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/shell/spacing.css
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/alberto/.local/share/gnome-shell/extensions/unite@hardpixel.eu/themes/
mag 25 15:05:02 XPS9370 gnome-shell[79874]:    creating: /home/`

**Additional context**
Thanks for the help. Have a good day.

**Comment by jonian** [comment]
Hi @JeanValjean30, apologies for the late response. Do you have the same issue when using the default theme (adwaita)? What is the theme that you are using?

**Comment by JeanValjean30** [comment]
> Hi @JeanValjean30, apologies for the late response. Do you have the same issue when using the default theme (adwaita)? What is the theme that you are using?

Don't worry. No problem. Your observation is correct. With adwaita theme I haven't this problem. Now I report this to the theme author. Thanks!
