### ISSUE TITLE
Disable custom keybindings?

### ISSUE THREAD

**Issue by spacekookie** [hardpixel/unite-shell#37]
I couldn't find any information about this so I thought I'd just open an issue. I've noticed that when I press `alt` that the current window loses focus. This is especially annoying when using a terminal :confused: 

Is this a desired effect of this extension or a bug or weird side-effect?

**Comment by jonian** [comment]
Unite shell does not set any custom keybindings.
I can't reproduce the issue on Arch Linux and Ubuntu 18.04 with GNOME 3.28.

Could you provide more info about your system?
- Distro version
- Gnome version
- Installed extensions

Also provide the output of `journalctl -r /usr/bin/gnome-shell | grep unite`. Thanks!

**Comment by spacekookie** [comment]
Hey there! Thanks for the quick reply, my computer crashed earlier and since then the issue hasn't occurred again. "Restarting" GNOME might have removed some weird interaction between other extentions that I had enabled.

So I think I'll close this issue for now
