### ISSUE TITLE
Fedora40 Gnome 46 Unite-shell fails (no left sidebar)

### ISSUE THREAD

**Issue by test242450** [hardpixel/unite-shell#370]
Installed last version 78 from zip file to .local/share/gnome-shell/extensions/unite@hardpixel.eu

**Unite shells loads ok, but no left sidebar visible**. Top bar and modify settings via extension manager works. Not any journalctl -g unite logs.

Fedora40 with latest updates + GNOME 46

**Comment by test242450** [comment]
![Screenshot from 2024-07-02 07-39-28](https://github.com/hardpixel/unite-shell/assets/174406895/aca8a878-d37d-46f3-b262-269f14f120aa)
![Screenshot from 2024-07-02 07-47-30](https://github.com/hardpixel/unite-shell/assets/174406895/d00d32dc-7e2d-4d99-991e-fd7016ee8a69)

**Comment by test242450** [comment]
![Screenshot from 2024-07-02 07-48-16](https://github.com/hardpixel/unite-shell/assets/174406895/0bb46870-ada4-4310-baeb-711a5c368d89)

**Comment by jonian** [comment]
Hi @test242450, what do you mean by left bar? The left bar in the screenshots is from dash to dock, this extension does not include any left bar (dock).

**Comment by BernardoChomboAlvarez** [comment]
Hi @test242450, I have the same issue, but after checking it a bit more deeply, it seems that the Unite version is incompatible with the GNOME 46 version. Hope they update it soon.

**Comment by jonian** [comment]
@BernardoChomboAlvarez unite **is compatible with gnome 46**, you can downlad the latest version from the [releases](https://github.com/hardpixel/unite-shell/releases/tag/v78).

**Comment by test242450** [comment]
Yes dash to dock was missing left bar option. All works fine now. I close ticket
