### ISSUE TITLE
Stop working for me

### ISSUE THREAD

**Issue by sssoulllessss** [hardpixel/unite-shell#374]
Technical details
The settings of extension unite@hardpixel.eu had an error:
```
SyntaxError: import declarations may only appear at top level of a module @ resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:4:0

Stack trace:
  @file:///home/soulless/.local/share/gnome-shell/extensions/unite@hardpixel.eu/prefs.js:4:21
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
```
Any idea how can i get titlebar actions on the top panel alternatively?

**Comment by jonian** [comment]
The extension version you use is not compatible with your gnome version. The issue template has sections where you could have provided that info.

**Comment by sssoulllessss** [comment]
> The extension version you use is not compatible with your gnome version. The issue template has sections where you could have provided that info.

does it. didn't pay attantion. because it was working fine for a few days then idk what happen. i installed dash to dock and removed it and then it stop. but it was fine before that. i installed it vie the extension manager instead vie the web page i guess thats why i didn't see the gnome version. any plans to update it for 46? i'm thinking of reinstalling os now going back to old version...

**Comment by jonian** [comment]
Latest version is compatible with gnome up to 47, but there will be no new releases in gnome extensions website. Install manually using:

```
wget https://github.com/hardpixel/unite-shell/releases/download/v79/unite-v79.zip
gnome-extensions install unite-v79.zip
```

**Comment by sssoulllessss** [comment]
Thanks, U r brilliant! I am so use to minimize windows with the middle mouse button on top panel. It became a habit. So grateful. Thanks again. Coolest extension ever.
