### ISSUE TITLE
 Support Gnome 47

### ISSUE THREAD

**Issue by Neo-29** [hardpixel/unite-shell#375]
see here
https://github.com/hardpixel/unite-shell/issues/362#issuecomment-2035661615

**Comment by jonian** [comment]
Gnome 47 is supported since v79 but an important error fix has been released in v80. Install using the commands below.
```bash
wget https://github.com/hardpixel/unite-shell/releases/download/v80/unite-v80.zip
gnome-extensions install unite-v80.zip
```

**Comment by korason7117** [comment]
> Gnome 47 is supported since v79 but an important error fix has been released in v80. Install using the commands below.
> 
> ```shell
> wget https://github.com/hardpixel/unite-shell/releases/download/v80/unite-v80.zip
> gnome-extensions install unite-v80.zip
> ```
not working for me.
Windows> Titlebars>Hide titlebars (select Maximized)
uptodate archlinux system and unite ver 80.

**Comment by jonian** [comment]
@korason7117 If you are on wayland, you probably have to log out and log back in after activating the extension, check #369. For arch linux there is an [AUR package](https://aur.archlinux.org/packages/gnome-shell-extension-unite), so it is better to use that instead of installing manually. The extension works fine on arch since I'm on arch too.

**Comment by korason7117** [comment]
why cant it be through regular manual install `gnome-extensions install unite-v80.zip`?

**Comment by jonian** [comment]
@korason7117 you can install manually, I suggested the aur package for easier install and automatic updates. I can't understand what is going on with your system from the video toy provided, I ain't no magician. You should provide logs using `journalctl -g unite` and do your testing with the default adwaita theme and other extensions disabled.

**Comment by korason7117** [comment]
i've only noticed a slight difference with regular gnome apps. their close/maximize/minimize buttons disappearing.

>You should provide logs using journalctl -g unite

here. nothing meaningful, though
```sh
Oct 08 19:59:15 archlinux gnome-shell[15907]: st_widget_get_theme_node called on the widget [0x60ee249dc420 Gjs_ui_panel_Panel.dashtopanelBottom reduce-spacing unite-shell:first-child last-child "panel"] which is not in the stage.
Oct 08 19:59:15 archlinux gnome-shell[15907]: st_widget_get_theme_node called on the widget [0x60ee249dc420 Gjs_ui_panel_Panel.dashtopanelBottom reduce-spacing unite-shell:first-child last-child "panel"] which is not in the stage.
Oct 08 19:59:15 archlinux gnome-shell[15907]: st_widget_get_theme_node called on the widget [0x60ee249dc420 Gjs_ui_panel_Panel.dashtopanelBottom reduce-spacing unite-shell:first-child last-child "panel"] which is not in the stage.
```
>and do your testing with the default adwaita theme and other extensions disabled.

my toy video was recorded with extensions enabled. but i had already tested with only _Unite_ enabled and all other disabled.  all default. 

is extension supposed to hide all title bars, qt and gtk?

**Comment by jonian** [comment]
Thanks for the extra info. So the extension works but not for some apps, is that correct?

The extension supports all applications that use SSR (server side decorations), that means all X11 (xwayland) apps. For CSD (client side decorated) apps there is support only for GTK. For Qt apps you can force X11 using the command below:

```
QT_QPA_PLATFORM=xcb dolphin
```
You can also set the env variable in `/etc/environment` to force X11 for all Qt applications.

**Comment by jonian** [comment]
Also Firefox is supported if you enable `Title Bar` in customize screen.

![Screenshot From 2024-10-09 09-34-41](https://github.com/user-attachments/assets/38f654c8-9ba7-4f4b-912b-a1c5f82ff084)

And Chrome (chromium, brave etc) if you enable "Use system titlebars and borders".

**Comment by korason7117** [comment]
so it will work on xwayland/x11 apps. which was never my point. it'll be best to reflect this in the README. since its difficult to fully support a wayland enviroment

**Comment by scarlion1** [comment]
What about this tho?  When I ask the Upgrade Assistant what's compatible with Gnome 47:
![image](https://github.com/user-attachments/assets/389bd354-11af-4d20-9b9c-e92811581893)

**Comment by jonian** [comment]
@scarlion1 I guess upgrade assistant checks with the latest version on EGO (gnome extensions website). This extension has stopped publishing new versions there since gnome 45.

**Comment by scarlion1** [comment]
> [@scarlion1](https://github.com/scarlion1) This extension has stopped publishing new versions there since gnome 45.

Otay 😋 
n wat abt w/ wayland do i need wlprop installed still [like is mentioned for gnome 46](https://github.com/hardpixel/unite-shell/issues/366#issuecomment-2114944615)?

**Comment by jonian** [comment]
No wlprop is not needed or used by the extension.
