### ISSUE TITLE
Error in installation of the extension

### ISSUE THREAD

**Issue by Biziol** [hardpixel/unite-shell#377]
SyntaxError: import declarations may only appear at top level of a module @ resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:4:1

Stack trace:
  @file:///home/bizio/.local/share/gnome-shell/extensions/unite@hardpixel.eu/prefs.js:4:21
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  
![Schermata del 2024-09-27 16-15-41](https://github.com/user-attachments/assets/12dfb61a-7048-4b5a-b2c8-b22298ffce38)

**Comment by jonian** [comment]
You are using an extension version that does not support your gnome version. Also you ignored the issue template that asks for these information.

**Comment by jonian** [comment]
If you gnome version is 45 or newer, use the installation instructions at https://github.com/hardpixel/unite-shell?tab=readme-ov-file#installation.
