### ISSUE TITLE
Multiple buttons

### ISSUE THREAD

**Issue by Phlya** [hardpixel/unite-shell#38]
![screenshot from 2018-04-05 09-33-39](https://user-images.githubusercontent.com/2895034/38355328-77a65556-38b4-11e8-8641-6eae6ac3c6f6.png)
This happens after unlocking the computer after it locked itself due to inactivity, or by switching the extension on and off (done here multiple times, normally it just adds one more set of buttons).

I'm on Ubuntu 18.04.

**Comment by olibia** [comment]
Hi @Phlya, what version of Unite are you using?

We had noticed this happening randomly and it has been fixed in the latest versions,

**Comment by Phlya** [comment]
Um, I installed it from extensions.gnome.org, not sure how to check the version...

**Comment by olibia** [comment]
The latest available version on extensions.gnome.org is v11, versions up to v16 are pending review.

You can install v16 manually by downloading the [release package](https://github.com/hardpixel/unite-shell/releases/download/v16/unite-shell-v16.zip) and extracting it in `~/.local/share/gnome-shell/extensions` folder.

After that you will need to restart gnome shell.
