### ISSUE TITLE
Setting to limit the length of window name string in top bar

### ISSUE THREAD

**Issue by thyttan** [hardpixel/unite-shell#386]
**Is your feature request related to a problem? Please describe.**
Firefox can have very long window titles depending on the open web adress. So long that they overlap other elements in the top bar.

**Describe the solution you'd like**
I suggest the introduction of two new settings:
- The maximum length of the window name string.
- Where to truncate the string (start, middle, end)

**Alternate solution**
Instead of truncating the string, hide it behind other ui elements in some way. E.g. by replacing characters in the string at those positions to `space`s. Maybe the user is responsible for defining the character indexes to replace with spaces.

**Additional context**
![Screenshot From 2024-12-10 01-50-25](https://github.com/user-attachments/assets/bd0387c9-2aad-4702-9a7d-1e8aa773e13c)

**My system**
Fedora Linux 41
Gnome 47.1
Firefox 133.0
Extensions: 
>BingWallpaper@ineffable-gmail.com
>caffeine@patapon.info
>display-scale-switcher@knokelmaat.gitlab.com
>emoji-copy@felipeftn
>gestureImprovements@gestures
>gnome-fuzzy-app-search@gnome-shell-extensions.Czarlie.gitlab.com
>gsconnect@andyholmes.github.io
>ideapad-controls@azzamalsharafi.gmail.com
>quick-lofi@eucaue
>quick-touchpad-toggle@kramo.hu
>reorder-workspaces@jer.dev
>tilingshell@ferrarodomenico.com
>windows-search-provider@G-dH.github.com
>unite@hardpixel.eu
>pano@elhan.io
>light-style@gnome-shell-extensions.gcampax.github.com
>dash-to-panel@jderose9.github.com

**Comment by jonian** [comment]
Hey @thyttan, these settings already exist (for a long time). What version of unite are you using?
![Screenshot From 2024-12-15 09-45-35](https://github.com/user-attachments/assets/830eee66-e6be-4f91-857f-b1b3d2779dfe)

**Comment by thyttan** [comment]
Thank you! Sorry for the noise.
