### ISSUE TITLE
BUG with actual gnome version

### ISSUE THREAD

**Issue by yuritoledo** [hardpixel/unite-shell#39]
Hello again.

When I was using the Pop_OS! 17.10, and after, Ubuntu 18.04, I have the same issue: After get back from suspend / lock mode, unite get error in gnome-tweak  and in gnome extension site.

I guess that is about gnome version, but, with antergos gnome, I guess that this problem doesn't work

**Comment by jonian** [comment]
Hi, can you provide the output of `journalctl -r /usr/bin/gnome-shell | grep unite`?

**Comment by jonian** [comment]
I'm closing this, since you sais it is back to normal and the log does not show any errors.
