### ISSUE TITLE
[Feature Request] Persistent panel items location (reordering)

### ISSUE THREAD

**Issue by eaerth** [hardpixel/unite-shell#41]
Hey there.
I've been tinkering around with the extension in my free time to try to figure out how to add this myself as there are a few other extensions that steal priority over this I believe. I'm also using Extend Panel Menu, which seems to offer an offset option but it doesn't always work on account of when I restart the shell from time to time, Unite will move back to the center of the panel icons. I've googled this a bit, found a solution on askubuntu.com but a lot of the tags and values (forgive me if I'm using the wrong jargon, I'm only really experienced with webdesign coding, not so much actual programming! haha) they are for items not in your code and I'm not sure if it was left out as they report that if left out, it will be placed to the right by default. However, I'm thinking that other extensions do have this and are possibly stealing priority over panel placement.

So... TL;D(wt)R ;
If you were to implement this functionality, how might you go about doing it if you're not feeling it is necessary to the integrity of the code? I would very much like to add it myself but I'm kind of at a loss. The only location I feel like it would make sense to make adjustments is here* but the code they are saying to search for doesn't match any of your code. This is probably the closest but then again, I could be in the wrong .js file all together. I'm looking in the WindowButtons.js module.
Ideally the functionality I am looking for is that it gains priority to immediate right placement at all times. Of course if you wanted, you could add an option to change the offset in your uisettings from the extension panel but I wanted to spare you guys the extensive coding if I could, I'm sure you're fairly busy and if it isn't "broke"-broke, why fix it kind of a thing?

*
```
if (this._position == 'left') {
        let appmenu = Main.panel.statusArea.appMenu.actor.get_parent();
        Panel._leftBox.insert_child_below(this._buttonsActor, appmenu);
      }

      if (this._position == 'right') {
        Panel._rightBox.add_child(this._buttonsActor);
}
```
And here is the url to what they are suggesting ; https://askubuntu.com/questions/453969/how-can-i-order-gnome3-shell-extensions-at-the-top

Anyway, I really appreciate your time for taking a look at my proposed idea, would very much love it if you added this functionality as I have always liked having window buttons in the panel without window titlebar decorations and your extension is a hell of a lot better than what I remember Maximus being back in the day. Thank you for the work you have already contributed and I wish you all the best.

Cheers!

Joshua

**Comment by jonian** [comment]
Hi @eaerth. Thank you for your detailed report and apologies for the late response.

```
if (this._position == 'left') {
        let appmenu = Main.panel.statusArea.appMenu.actor.get_parent();
        Panel._leftBox.insert_child_below(this._buttonsActor, appmenu);
}
```
When the buttons are on the left side, they are placed before the appMenu. If you want to place them in a specific position, you can use:
```
if (this._position == 'left') {
        Panel._leftBox.insert_child_at_index(0);
}
```
When the buttons are on the right side, they are placed as the last item on the right.

> I'm thinking that other extensions do have this and are possibly stealing priority over panel placement.

This is correct. If there are other extensions that use `add_child` to add items on the right side of the panel. In this case the extension loaded last will steal priority. The same applies if you use `insert_child_at_index`, to add a widget at a specific position.

So adding persistent location to panel widgets is not possible, since you can't control when each extension gets loaded.

I'm leaving this issue open and if I find a way to implement it, I will.

**Comment by jonian** [comment]
Closing this as it is not possible to implement. This has also been discussed upstream and no solution was given.
