### ISSUE TITLE
[Bug] The extension doesn't support gnome-shell themes

### ISSUE THREAD

**Issue by ceyhunnabiyev** [hardpixel/unite-shell#44]
For example, It doesn't support famous Adapta gtk theme. Icons get messy. Screenshot:

![screenshot from 2018-04-16 21-26-23](https://user-images.githubusercontent.com/5506156/38825220-d4baea34-41bc-11e8-8cfa-3e5d655edab9.png)

**Comment by ceyhunnabiyev** [comment]
Also doesn't support Adapta window control buttons. I changed theme to Materia Dark from Unite Settings. You can see this from above screenshot.

--
By the way, many thanks for the great extension...

**Comment by jonian** [comment]
Hi, thank you for the report. Could you please explain what is the problem in the screenshot above?

I think that Adapta is a fork of Materia and they both use the same window buttons, so I included only the meteria buttons.

**Comment by ceyhunnabiyev** [comment]
> I think that Adapta is a fork of Materia and they both use the same window buttons, so I included only the Materia buttons.

Not only Adapta. I think it would nice to be there default option in settings to grab system window control button theme.

**Comment by tristan-k** [comment]
I'm using the [arc-flatabulous-theme](https://github.com/andreisergiu98/arc-flatabulous-theme) but the buttons are not picked up. Anyway to fix this?

![bildschirmfoto vom 2018-10-31 21-35-20_cropped](https://user-images.githubusercontent.com/732025/47817412-d462bf00-dd55-11e8-9d18-673b5574d75b.png)

**Comment by jonian** [comment]
@tristan-k Theme extension does not "pick up" any theme. It has settings to select a theme from a theme [list](https://github.com/hardpixel/unite-shell/tree/master/unite%40hardpixel.eu/themes). The matching theme for flatabulous is `OSX Arc`.

**Comment by tristan-k** [comment]
I'm sorry I missed that one. Thanks for pointing me to the right direction.

**Comment by jonian** [comment]
No problem. Happy to help.
