### ISSUE TITLE
Google Chrome window control buttons gets double when maximized

### ISSUE THREAD

**Issue by ceyhunnabiyev** [hardpixel/unite-shell#45]
Screenshot:
![screenshot from 2018-04-16 21-55-15](https://user-images.githubusercontent.com/5506156/38826435-dcbf40a0-41c0-11e8-8188-91226a231741.png)

**Comment by jonian** [comment]
You can enable "System title bars and borders":
![screenshot from 2018-04-16 21-10-22](https://user-images.githubusercontent.com/4119508/38828781-c6335048-41bf-11e8-85a7-7f41a8f00ab0.png)

And it will work:
![screenshot from 2018-04-16 21-10-34](https://user-images.githubusercontent.com/4119508/38828799-db6807a6-41bf-11e8-8c71-a3c650782742.png)

**Comment by ceyhunnabiyev** [comment]
Thank you..
