### ISSUE TITLE
[Feature Request] Ability to close, maximize, minimize  unfocused windows

### ISSUE THREAD

**Issue by ceyhunn** [hardpixel/unite-shell#46]
For example, I have two windows, one is maximized, but the other is focused, not maximized. I can't see maximized window contol buttons. Without this extension, for example, I can close the unfocused maximized window. It would be nice to add this feature that unfocused maximized window control buttons should be seen on panel for clicking.

Thanks for great extension..

**Comment by ceyhunnabiyev** [comment]
Hi @jonian , for help
This feature (Ability to close, maximize, minimize, even focus unfocused windows) exists in [this extension](https://github.com/franglais125/no-title-bar).
