### ISSUE TITLE
Double icons

### ISSUE THREAD

**Issue by fcuencamargalef** [hardpixel/unite-shell#47]
After resume Ubuntu after been suspended. The icons are doubled.

Ubuntu 18.04

![image](https://user-images.githubusercontent.com/4992908/39766496-b8c86bd8-52e4-11e8-8314-ece799734566.png)

**Comment by jonian** [comment]
Hi @fcuencamargalef. Can you provide the output of `journalctl -r /usr/bin/gnome-shell | grep unite`?
