### ISSUE TITLE
Hover issue/visual glitch over window title in the app menu

### ISSUE THREAD

**Issue by Andihawke** [hardpixel/unite-shell#5]
I installed it manually from github on gnome 3.26 - ubuntu 17.10 and it works without problems here :-)
But if i hover over the window title a little visual glitch appears. 

![screenshot](https://user-images.githubusercontent.com/17460997/30683126-712c88dc-9eac-11e7-9709-807f28500442.png)

**Comment by jonian** [comment]
@Andihawke thanks for the report. It looks like it is a shadow in app-menu-icon, which is hidden by Unite.

**Comment by jonian** [comment]
@Andihawke can you try replacing the extension `stylesheet.css` with the latest version https://raw.githubusercontent.com/hardpixel/unite-shell/master/dist/unite%40hardpixel.eu/stylesheet.css and see if it fixes this issue.

**Comment by Andihawke** [comment]
@jonian ok i tried but it doesn't work.

**Comment by jonian** [comment]
@Andihawke yes I set the box shadow to none. I will set up ubuntu 17.10 in a VM and do more testing.

**Comment by Andihawke** [comment]
@jonian ok sounds good :-) 
as workaround i set the width and height for the icon to make it visible again. 
even so it looks pretty good to me.

**Comment by Andihawke** [comment]
@jonian i tried a little bit and this fixed it for me - maybe it helps:
#panel .panel-button:hover .app-menu-icon > StIcon {
      icon-shadow: none; 
    }

**Comment by jonian** [comment]
@Andihawke it helps, thank you. Do you want to make a pull request? If not, I will add it later.

**Comment by Andihawke** [comment]
@jonian i just made the changes directly in the css files. so its better you add it later.
