### ISSUE TITLE
GNOME Shell 3.28.1 version not found on download page

### ISSUE THREAD

**Issue by rkg0612** [hardpixel/unite-shell#51]
Hi,

I'm just wondering if I can use the unite-shell on a lower version than my current GNOME Shell? Thanks!

**Comment by jonian** [comment]
Hi, it is better tou use the latest version from https://github.com/hardpixel/unite-shell/releases. Gnome shell extensions website is very slow on reviewing extensions.

Unite latest version: 17
Gnome shell extensions website version: 11
