### ISSUE TITLE
[Feature Request] Reorder elements on the menubar

### ISSUE THREAD

**Issue by arooni** [hardpixel/unite-shell#52]
Love this, it's the only thing that makes using ubuntu 18.04 feel 'right'.  Thank you.

I'm wondering if there could be a way to reorder elements on the menubar.  would be really nice.  I tried to use https://extensions.gnome.org/extension/1201/extend-panel-menu/ but it breaks your extension.

**Comment by jonian** [comment]
Duplicate of #41
