### ISSUE TITLE
60+% cpu usage when extension is activated [ubuntu 18.04] lenovo t420

### ISSUE THREAD

**Issue by arooni** [hardpixel/unite-shell#53]
with:

```
  Avg[||||||||||||||||||||||||||||                                                                           25.2%]   Tasks: 303, 1174 thr, 128 kthr; 1 running
  Mem[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||5.20G/7.55G]   Load average: 1.61 1.05 1.15
  Swp[|||                                                                                               234M/9.41G]   Uptime: 17:29:53

  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
 8910 david      20   0 3712M  279M 89988 S 63.0  3.6 10:06.73 /usr/bin/gnome-shell
22789 david      20   0  499M 82328 60112 S  5.3  1.0 10:39.79 /usr/lib/xorg/Xorg vt2 -displayfd 3 -auth /run/user/1000/gdm/Xauthority -background none -noreset -keeptty -verbose 3


without:


  Avg[||||||||||||||||||||||||||||                                                                           25.2%]   Tasks: 303, 1174 thr, 128 kthr; 1 running
  Mem[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||5.20G/7.55G]   Load average: 1.61 1.05 1.15
  Swp[|||                                                                                               234M/9.41G]   Uptime: 17:29:53

  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
 8910 david      20   0 3712M  279M 89988 S 63.0  3.6 10:06.73 /usr/bin/gnome-shell
22789 david      20   0  499M 82328 60112 S  5.3  1.0 10:39.79 /usr/lib/xorg/Xorg vt2 -displayfd 3 -auth /run/user/1000/gdm/Xauthority -background none -noreset -keeptty -verbose 3
```
I'm hoping you can fix because this extension is the only thing that makes using ubuntu 18.04 bearable.

**Comment by arooni** [comment]
i'm going to close this out because i think it was due to constantly updating app indicators from a separate extension that i think increased cpu too much

**Comment by arooni** [comment]
i'd like to re-open this issue... still running into this issue.. and i disabled all extensions minus this one and it was the only one that spiked cpu usage

**Comment by jonian** [comment]
Hi @arooni, sorry for the late response. I can't reproduce this behaviour. Does this still happen with the latest version [22](https://github.com/hardpixel/unite-shell/releases/tag/v22)?

**Comment by arooni** [comment]
sorry to bother you on this -- i think actually it's an error in my argos extension.  i'm closing this until i can reproduce solidly again

**Comment by jonian** [comment]
@arooni Thank you for the update!

**Comment by epsilontheta** [comment]
I can consistently reproduce this with the newest version from master (5c04151), gnome 3.32.0 and wayland.
The gnome-shell process is using 0-1% when the extension is disabled and around 9% when enabled.
I also noticed that the memory usage increases and sometimes drops by 0.5 to 1 MiB (maybe related to the garbage collector?). When disabled it is relatively stable.

**Comment by mind-blowing** [comment]
I have the same problem, using `gnome 3.32.0` and `xorg`.
During investigation I found that if I'm disabling `tray icons` feature, then problem is gone, also I want to notice that I saw similar cpu usage problem also when I used another extension `top icons plus`.

**Comment by jonian** [comment]
@mind-blowing that is a known bug in gnome shell:
https://gitlab.gnome.org/GNOME/gnome-shell/issues/1054

A solution is to use the app-indicators extension and keep `tray icons` disabled:
https://github.com/ubuntu/gnome-shell-extension-appindicator

**Comment by arooni** [comment]
@jonian I tried installing that extension but I got an ERROR message.

**Comment by jonian** [comment]
@arooni sorry, can't help you. I do not use that extension. Have you tried to ask on their issue tracker?

**Comment by jonian** [comment]
@arooni I just installed it on arch linux and it works without problems. Maybe you are missing dependencies like libappindicator-gtk3 and libappindicator-gtk2.

I installed it from master branch not gnome shell extensions website.

**Comment by arooni** [comment]
Looks like gnome-shell-extension-appindicator got updated and I could install it @jonian ; but when you say keep ```tray icons``` disabled; I don't see an option in that extension (or unite for that matter) to do this.  am i missing something?

thanks!

**Comment by jonian** [comment]
@arooni Unite has a setting "Show system tray in top bar", that you can use to disable the tray icons module.

![settings](https://user-images.githubusercontent.com/4119508/57181481-0982d200-6e9d-11e9-9d59-7fb053652569.png)
