### ISSUE TITLE
Can't click on a tray icons since last update

### ISSUE THREAD

**Issue by Aceler** [hardpixel/unite-shell#55]
Since last update (can't determine the extension's version - how can I do that?) I can't click on a tray icons and App's name on a panel. Clicking on a tray does nothing, while clicking on an App's name start dragging instead of menu.

**Comment by andrebrait** [comment]
I can confirm this.
In my case, the icons don't even appear.

**Comment by andrebrait** [comment]
I found that going to the settings and disabling/re-enabling "Show system tray in top bar" kinda fixes it.
Give it a try.

**Comment by Aceler** [comment]
It fixes for one click only :-)

**Comment by Aceler** [comment]
I disabled them all except for unite. Still got the issue.

**Comment by jonian** [comment]
Hi, can you give more info? I can't reproduce this.

- Distro version
- Extension version (find metadata.json in extension files)
- Apps with tray-icons that you have tested

Also you can disable "Show system tray in top bar" and use [Appindicator Extension](https://github.com/ubuntu/gnome-shell-extension-appindicator) that is preinstalled on Ubuntu.

Tray icons will be removed in later versions, so spending time on fixing it is not a priority.

**Comment by Aceler** [comment]
Hi! 
1. Distro Pop!_OS 18.04, based on Ubuntu 18.04.
2. Unite version 18.
3. Apps that does not show their icon: Riot-web, Megasync, Tomboy, Variety.
Apps that do show their icon, but the icon is unclickable: vk 

Appindicator Extension successfully shown all the icons except for vk, thank you.

**Comment by jonian** [comment]
@Aceler can you test with the latest code from master branch? Thanks!

**Comment by jonian** [comment]
@Aceler I tested in a VM with Pop!_OS 18.04 and I can't reproduce the issue. Did you test the latest master branch?

**Comment by Aceler** [comment]
Yes, the latest master branch resolved the issue.

**Comment by jonian** [comment]
@Aceler Thanks!
