### ISSUE TITLE
Duplicate window buttons with some Gnome-Apps

### ISSUE THREAD

**Issue by yesmanny** [hardpixel/unite-shell#56]
There are duplicate window buttons with some Gnome Apps when maximized, for example Gnome System Monitor or Gnome Logs.

![sysmon](https://user-images.githubusercontent.com/42352747/44045822-0cb85ab4-9f2a-11e8-978b-3d1deadaa86b.png)

**Comment by jonian** [comment]
When you first enable the extension all apps that are already opened display duplicate window buttons.
This happens because the extension uses css to hide the buttons from header-bars.

**Comment by yesmanny** [comment]
Now I've localized the problem. It's caused by the Ubuntu snap apps. Deinstalling the snap apps and then installing the normal package based app's solved the problem.
