### ISSUE TITLE
Hide window titlebars for tiled windows

### ISSUE THREAD

**Issue by ltrottier** [hardpixel/unite-shell#58]
Hi!

First, thanks for this great extension!

I would like to hide to titlebar of my tiled windows as well. I looked at the configuration and I tried to set "Hide window titlebars" to "Both", but nothing happened. Can you help me with that ?

**Comment by jonian** [comment]
Hi, when you say tiled you mean half screen or smaller tiles? If it is smaller tiles, then it will not work because `xprop` removes decorations for windows that are maximized horizontaly, verticaly and fully maximized.

**Comment by jonian** [comment]
If this was an issue in wayland, it is now fixed in master. I am closing this since no feedback is provided and I could not find any other issues.

If the issue persists, feel free to open a new issue providing more details.
