### ISSUE TITLE
Hide window titlebar as maximized is buggy 

### ISSUE THREAD

**Issue by hurrycaner** [hardpixel/unite-shell#59]
When moving a window from maximized to tiled using "<super> left" or "<super> right" with Hide window titlebar set as maximized... cause window to be tiled without visible titlebar.

**Comment by jonian** [comment]
This is fixed for gnome shell 3.30.1 and later using _MOTIF_WM_HINTS.

Can't apply the fix in earlier versions due to this bug:
https://gitlab.gnome.org/GNOME/mutter/issues/273
