### ISSUE TITLE
No buttons in panel for windows in secondary monitor

### ISSUE THREAD

**Issue by jianqiao-ms** [hardpixel/unite-shell#61]
Not a citical bug but this is not perfect for me. There is not buttons on the panel when placing windows on the second monitor.

**Comment by jonian** [comment]
An option can be added to show buttons from all screens. Currently shows buttons only from windows on primary screen.

**Comment by vltr** [comment]
Well, I made a quick change by hand on the extension to avoid checking for `primaryScreen` on https://github.com/hardpixel/unite-shell/blob/3edcf6cd6027749be3c062a5a480c75351199e8f/unite%40hardpixel.eu/helpers.js#L118-L120 If needed, I can make a PR with that with an option to enable / disable checking if the window is in the primary screen.

**Comment by jonian** [comment]
@vltr That would be great! If you need help on how to add the option controls, let me know.

**Comment by vltr** [comment]
@jonian great! It's a simple change, I think I can do it in no time. Not to mention that, after the initial PR, you can also review and request changes if something is not the way it's supposed to be (ex: I'm terrible for creating the label's name, just sayin') :wink:

**Comment by vltr** [comment]
@jonian just one question: should I make the option to extend behavior to secondary monitors a bool, like "extend for tiled and maximized" or a `enum`, like "extend for tiled if extend to second monitors tiled selected, extend for maximized if extend to second monitors maximized selected" and so on?

**Comment by jonian** [comment]
A bool is better in the form of: 

**label**: Show buttons only for primary screen windows
**default**: true

I'm terrible at labels too, so feel free to change the text :wink:.
In the future we can add the same bool controls for decorations and window title.

**Comment by vltr** [comment]
Great. I'm mostly interested in making it work this way so I can have the "hide decorations" behavior in windows that are not in my primary screen, so do you think I can tackle on that as well?

I created the label as "Restrict functionalities to the primary screen", default to `true`.

**Comment by jonian** [comment]
That would be great. Will make the feature complete.

**Comment by vltr** [comment]
@jonian great. I just created the PR, #109. It does not address the problem related to _this particular issue_ (#61), but it's a start. Please, review and point me to the right direction if anything looks wrong :wink:

**Comment by jonian** [comment]
@vltr thank you. I have reviewed the PR #109 and I added a comment. Issue #61 is out of the scope of the PR and is not very clear how it can be solved.

**Comment by jonian** [comment]
@vltr fixed this in PR #109.

**Comment by Misteur-Z** [comment]
What happens if I want the window buttons placement to be dynamic, following the window's current monitor ? I can't manage to find the combination of settings to do that between `unite` and `ulti-monitors`.

I don't want to have a static `uniteWindowControls` for example (set to 0 or 1).
