### ISSUE TITLE
Convert Tray Icons to greyscale fails to change some app Icons

### ISSUE THREAD

**Issue by leoandreotti** [hardpixel/unite-shell#62]
Hello.

I am having issues with the "Convert Tray Icons to greyscale". I am not been able to use this feature. For some reason, I had 1-time success using it but it is not working here.

Any consideration during the install especially for this feature? Applications that I am having issues: skypeforlinux, Tusk, and Slack. The only snap is Tusk.

![image](https://user-images.githubusercontent.com/34519982/46538869-742e4980-c88b-11e8-88fb-c077385076aa.png)

![image](https://user-images.githubusercontent.com/34519982/46538944-a50e7e80-c88b-11e8-89ca-0506645d5201.png)

PS: I am using ubuntu-mono-dark icons pack.

**Comment by jonian** [comment]
Hi @leoandreotti, sorry for the late response. Ubuntu uses [AppIndicators](https://github.com/ubuntu/gnome-shell-extension-appindicator) for the tray icons and Unite is not handling those icons.

You can disable AppIndicators and use Unite System Tray implementation or open a feature request issue [here](https://github.com/ubuntu/gnome-shell-extension-appindicator/issues).
