### ISSUE TITLE
[Bug] super + l (screenlock) doesn't work properly in gnome-shell 3.30 

### ISSUE THREAD

**Issue by ceyhunn** [hardpixel/unite-shell#63]
After disabling this extension screenlock works. Seems like destroy function for this extension doesn't work properly with gnome-shell 3.30.

**Comment by ceyhunnabiyev** [comment]
Logs:

`17:26:52 gnome-shell: Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of the array as a string, but that is nonstandard. In the future this will return the bytes as comma-separated digits. For the time being, the old behavior has been preserved, but please fix your code anyway to explicitly call ByteArray.toString(array).
(Note that array.toString() may have been called implicitly.)
0 _updateUserStyles() ["/usr/share/gnome-shell/extensions/unite@hardpixel.eu/modules/windowDecoration.js":131]
1 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
2 _addUserStyles() ["/usr/share/gnome-shell/extensions/unite@hardpixel.eu/modules/windowDecoration.js":143]
3 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
4 _activate() ["/usr/share/gnome-shell/extensions/unite@hardpixel.eu/modules/windowDecoration.js":198]
5 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
6 _init() ["/usr/share/gnome-shell/extensions/unite@hardpixel.eu/modules/windowDecoration.js":20]
7 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
8 _Base.prototype._construct() ["resource:///org/gnome/gjs/modules/_legacy.js":18]
9 newClass() ["resource:///org/gnome/gjs/modules/_legacy.js":114]
10 _init() ["/usr/share/gnome-shell/extensions/unite@hardpixel.eu/extension.js":26]
11 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
12 _Base.prototype._construct() ["resource:///org/gnome/gjs/modules/_legacy.js":18]
13 newClass() ["resource:///org/gnome/gjs/modules/_legacy.js":114]
14 enable() ["/usr/share/gnome-shell/extensions/unite@hardpixel.eu/extension.js":50]
15 enableExtension() ["resource:///org/gnome/shell/ui/extensionSystem.js":135]
16 loadExtension() ["resource:///org/gnome/shell/ui/extensionSystem.js":181]
17 _loadExtensions/<() ["resource:///org/gnome/shell/ui/extensionSystem.js":328]
18 _emit() ["resource:///org/gnome/gjs/modules/signals.js":128]
19 _loadExtension() ["resource:///org/gnome/shell/misc/extensionUtils.js":186]
20 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
21 scanExtensions/<() ["resource:///org/gnome/shell/misc/extensionUtils.js":192]
22 collectFromDatadirs() ["resource:///org/gnome/shell/misc/fileUtils.js":28]
23 scanExtensions() ["resource:///org/gnome/shell/misc/extensionUtils.js":191]
24 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]
25 _loadExtensions() ["resource:///org/gnome/shell/ui/extensionSystem.js":330]
26 enableAllExtensions() ["resource:///org/gnome/shell/ui/extensionSystem.js":338]
27 _sessionUpdated() ["resource:///org/gnome/shell/ui/extensionSystem.js":369]
28 init() ["resource:///org/gnome/shell/ui/extensionSystem.js":377]
29 _initializeUI() ["resource:///org/gnome/shell/ui/main.js":229]
30 start() ["resource:///org/gnome/shell/ui/main.js":133]
31 <TOP LEVEL> ["<main>":1]`

**Comment by jonian** [comment]
Released new version (21) and is on review https://extensions.gnome.org/review/8523.
