### ISSUE TITLE
double window button on google chrome or chromium-browser

### ISSUE THREAD

**Issue by wijaksanapanji** [hardpixel/unite-shell#65]
![image](https://user-images.githubusercontent.com/18242489/47915498-0868ec00-dede-11e8-9866-8fd762df0e29.png)

i got double window button when using unite and crhome

**Comment by wijaksanapanji** [comment]
im sorry, i just found the solution, just enable system title on chrome
![image](https://user-images.githubusercontent.com/18242489/47915785-ea4fbb80-dede-11e8-97b0-ff23d852010b.png)

**Comment by jonian** [comment]
@wijaksanapanji No problem. This was reported also on #45. I'm adding it here for reference.
