### ISSUE TITLE
Duplicate window buttons for chromium browser

### ISSUE THREAD

**Issue by navtojchahal** [hardpixel/unite-shell#72]
![chrome-maximized](https://user-images.githubusercontent.com/37762455/49063609-c1180780-f1cc-11e8-8004-38a4d421b908.png)

The window buttons appear on both the top bar and the application border for chromium. I tried [this](https://github.com/hardpixel/unite-shell/issues/45) and [this](https://github.com/hardpixel/unite-shell/issues/56), but, it still didn't work. Is there any way to fix this?

Settings: ![unite-settings](https://user-images.githubusercontent.com/37762455/49063297-c1fc6980-f1cb-11e8-96d5-481c20e5c9ad.png)

Chrome not Maximized: 
![chrome-not-maximized](https://user-images.githubusercontent.com/37762455/49063653-de4cd600-f1cc-11e8-81b2-546ece69b898.png)

Chrome --not maximized -- with System Titlebars: 
![chrome-not maximized-with system titlebars](https://user-images.githubusercontent.com/37762455/49063822-7945b000-f1cd-11e8-8656-7c3d5837f212.png)

**Comment by jonian** [comment]
Hi @navtojchahal, the extension shows duplicate buttons on Chrome/Chromium when `Use system title bars and borders` is **disabled**. This is a known behavior and there is no way to change it. 

The same with Firefox when client side decorations are enabled, but in Firefox it can be changed with an extension or `userChrome.css`.

**Comment by jonian** [comment]
Yes that could be done. Please open a new issue for that feature request.
