### ISSUE TITLE
Cannot open the extension's settings after the last update

### ISSUE THREAD

**Issue by lekseven** [hardpixel/unite-shell#75]
Just as said in the title - nothing happens when clicking on the extension's settings button. Tried it in Gnome Tweak, Software Center and here https://extensions.gnome.org/local/

**Comment by flortsch** [comment]
Did you restart your shell after updating?
I installed the latest version from AUR and everything works fine here.

**Comment by lekseven** [comment]
When I restarted GNOME shell it accidentally got me to the login screen. After that I couldn't log in until I deleted the extension directory from ~/.local/share/gnome-shell/extensions/. And when I finally managed to enter the system I tried to install the extension again and ended up the same result - the GDM login screen.

**Comment by jonian** [comment]
Hi @lekseven, please provide version info (Gnome Shell, Distro). Also provide the output of `jouranlctl /usr/bin/gnome-shell | grep unite`.

**Comment by lekseven** [comment]
Ubuntu 18.04.1
GNOME 3.28.2

[unite.log](https://github.com/hardpixel/unite-shell/files/2634469/unite.log)

**Comment by jonian** [comment]
Please test the master branch and confirm if the issue is fixed.
On my tests in gnome-boxes - Ubuntu 18.04, everything is working fine.

**Comment by lekseven** [comment]
@jonian Yes, It's working now! Thanks.
