### ISSUE TITLE
Gnome Shell Crash

### ISSUE THREAD

**Issue by Torbe** [hardpixel/unite-shell#76]
GNOME Shell 3.28.3

Updated the extension today and it first made my desktop freeze. I reloaded Gnome Shell with the result of a total crash. Restart through Login Manager failed until i "manually" deleted the extension.

**Comment by ldreux** [comment]
Same result here with Ubuntu 18.04

**Comment by TROMsite** [comment]
I want to say it works fine with gnome-shell  1:3.30.1-1

**Comment by Nicolab** [comment]
Same here, crash since the last update (today for me).
gnome-shell 3.28.3-0ubuntu0.18.04.3

**Comment by loczaj** [comment]
V23 is crashing on Ubuntu 18.04 (Gnome Shell 3.28.3)

**Comment by loczaj** [comment]
I have downgraded to v22, otherwise I could not use my desktop.
@jonian  , you have misspelled the command 'journalctl'
Output of 'journalctl /usr/bin/gnome-shell | grep unite': [unite.txt]
[unite.txt](https://github.com/hardpixel/unite-shell/files/2634378/unite.txt)

**Comment by jonian** [comment]
Please test the master branch and confirm if the issue is fixed? 
On my tests in gnome-boxes - Ubuntu 18.04, everything is working fine.

**Comment by leoandreotti** [comment]
It worked here now. Manually updated and it worked. Thank you!

**Comment by jonian** [comment]
The fix also confirmed on #75. Closing.

**Comment by SPYFF** [comment]
Is it possible to configure Gnome Shell to stop loading incompatible plugins to avoid crashes like this in the future? Or maybe an unload/safemode mechanism in the plugin?

**Comment by mauron85** [comment]
I'm also affected by this on Ubuntu 18.04

Deleted extension and I can log into gnome-shell. But reinstalling extension from
https://extensions.gnome.org/extension/1287/unite/ installs version that still crashes.

How can I install v24 or downgrade to v22?

**Comment by Nicolab** [comment]
@mauron85 I did the same.

**Comment by jonian** [comment]
@SPYFF Gnome shell is supposed to disable the extensions that have errors by default. Also an  unload/safemode mechanism would not have prevented the issue, since this was a gjs error (https://github.com/hardpixel/unite-shell/commit/38fe08445468bc5d609f506e34a8875de0589b70).
