### ISSUE TITLE
Ubuntu 18.04 session no longer opens with Unite

### ISSUE THREAD

**Issue by svtcalvin** [hardpixel/unite-shell#79]
Hello
Since the last update of the Unite, Unite prevents logon. Under ubuntu 18.04 with Unite  the session opens and closes instantly. I had to uninstall Unite to be able to open my session. there may be an incompatibility with other Gnome extensions.
I have attached the list of extensions I own
[liste des extensions.pdf](https://github.com/hardpixel/unite-shell/files/2636061/liste.des.extensions.pdf)

**Comment by jonian** [comment]
Duplicate of #76 #75 #77
