### ISSUE TITLE
Some top indicator icons disappear

### ISSUE THREAD

**Issue by tiotrom** [hardpixel/unite-shell#84]
One thing I noticed is that for certain applications like Transmission torrent the top indicator icon is not showing, same happens for Private Internet Access. A Shell restart fixes the issue. To reproduce can be a bit tricky as it does not always happen. For instance if I have my Transmission open for many hours, then close it and open it again, it shows a blank (empty) space where its icon should be. It also seems to happen if you Lock your system, then unlock it, then close such an application like Transmission and open it again. For me, that always results in an empty space where the Transmission icon should be. As mentioned, it also happens for Private Internet Access. Thanks for your work!

**Comment by jonian** [comment]
Hi @tiotrom, please provide more info about your system.

If you use Ubuntu, top icons are handled by [AppIndicator](https://github.com/ubuntu/gnome-shell-extension-appindicator), so you should report the issue there.

**Comment by jonian** [comment]
@tiotrom yes the extension has a top icons module. Thank you for the extra info.

**Comment by tcye** [comment]
I the same problem, ubuntu 18.04 with only unite extension installed, and configure "show system tray in top bar" with ON. Wait for a fix, thank you!

**Comment by zeten30** [comment]
Hi, same issue. Icons disappear after screen lock. I was using https://extensions.gnome.org/extension/495/topicons/ before and it was working fine.

**Comment by zeten30** [comment]
This looks interesting - https://github.com/zhangkaizhao/gnome-shell-extension-tray-icons/commit/95916cab86ef7ae42809ff92386548129617038b

**Comment by jonian** [comment]
@zeten30 Thanks, I will check it out!

**Comment by huyndnse63331** [comment]
Hi guys, im using Ubuntu 18 and having the same problem, how can i manage to fix this? Thanks
