### ISSUE TITLE
Notification icons no longer displaying

### ISSUE THREAD

**Issue by jesseonslow** [hardpixel/unite-shell#85]
I've been using Unite for a couple of weeks without any issues, but today when I logged into my session none of the notification icons appeared. I can see the applications that should have notifications icons (Variety, ownCloud, Steam) are running, but the icons are not being shown.

**Comment by jonian** [comment]
Duplicate #84

**Comment by jonian** [comment]
@deckoff  On Ubuntu top icons are handled by [AppIndicator](https://github.com/ubuntu/gnome-shell-extension-appindicator), so you should report the issue there.
