### ISSUE TITLE
"About this computer" does nothing

### ISSUE THREAD

**Issue by tiotrom** [hardpixel/unite-shell#87]
When I click "about this computer" it does not open anything. Using Manjaro Gnome with the latest updates.

**Comment by jonian** [comment]
What do you mean? Where is "about this computer" and how it relates to this extension?

Please provide a screenshot.

**Comment by tiotrom** [comment]
Reported it to the wrong extension. Damn, I need to pay more attention to no bother people with such things. I apologize you can close this.

**Comment by jonian** [comment]
No problem. Thanks.
