### ISSUE TITLE
Double click on maximized title bar should restore window size

### ISSUE THREAD

**Issue by dandv** [hardpixel/unite-shell#89]
When I double click on the title bar of a window, it gets maximized. But when double clicking on the top/title bar of the window in maximized state, the window dimensions are not restored (the double click does nothing). Is this something that Unite could help fix?

**Comment by Leleat** [comment]
This already works for me (it is set with the option in GNOME tweaks). Maybe this is outdated?

**Comment by babyadoresorange** [comment]
@Leleat what Gnome version are you using ? It doesn't work for me either

**Comment by Leleat** [comment]
3.38.3 (from Fedora). Just to make sure, we are talking about the window's title bar, right? Not GNOME's top panel. Here is the gif:

![output](https://user-images.githubusercontent.com/53054301/106381858-97158d80-63b3-11eb-8c75-980accd4f264.gif)

**Comment by babyadoresorange** [comment]
Yes the title bar works, as it is already on gnome. But I thought the same behavior on top bar would be more logical.
