### ISSUE TITLE
Unite doesnt start on ubuntu 19.04 with Error: No signal 'allocate' on object 'Gjs_Panel'

### ISSUE THREAD

**Issue by k1l** [hardpixel/unite-shell#91]
Using ubuntu testing 19.04 with > gnome-shell --version GNOME Shell 3.31.92. The Extensions fails to start, in the logs i see only this error for unite: 
Extension "unite@hardpixel.eu" had error: Error: No signal 'allocate' on object 'Gjs_Panel'

**Comment by darthoctopus** [comment]
I am still seeing this error on gnome-shell 3.32.0 on Arch.

**Comment by jonian** [comment]
@darthoctopus download the latest version from https://github.com/hardpixel/unite-shell/releases or install it from AUR.

I'm on Arch and the issue is fixed.

**Comment by pascalduez** [comment]
I had the same error installing from the extensions website, even uninstalling, re installing. There must be some sticky cache because a reboot/log-out and it's working.
