### ISSUE TITLE
Some tray icons do not show sometimes

### ISSUE THREAD

**Issue by tiotrom** [hardpixel/unite-shell#92]
For example KeePassXC tray icon disappears after a while on Manjaro Gnome. To replicate install Unite + KeePassXC and minimize KeePassXC. Then lock the computer and unlock it. It disappears. Restarting Gnome Shell cannot restore it. Only reboot. Same happens with other applications like CopyQ.

**Comment by jonian** [comment]
duplicate #84

**Comment by jonian** [comment]
Please do not open duplicate issues. Add a comment to the existing issue.

**Comment by tiotrom** [comment]
Oh I apologize. I forgot I reported that 3 months ago. I am testing many open source projects and report errors I find to improve them and this was an error. Again, I'm sorry.

**Comment by jonian** [comment]
@tiotrom No problem.
