### ISSUE TITLE
High CPU usage when "Show system tray in top bar" is active

### ISSUE THREAD

**Issue by prurigro** [hardpixel/unite-shell#96]
The `gnome-shell` process consistently uses about 40-60% CPU when `Show system tray in top bar` is enabled, and drops down to ~4% when disabled.

This is with v27 and gnome 3.32.

Cheers!

**Comment by jonian** [comment]
As mentioned in issue #53:

This is a known bug in gnome shell:
https://gitlab.gnome.org/GNOME/gnome-shell/issues/1054

A solution is to use the app-indicators extension and keep `tray icons` disabled:
https://github.com/ubuntu/gnome-shell-extension-appindicator

**Comment by jonian** [comment]
Closing, since this is not an bug caused by this extension.

**Comment by arooni** [comment]
> A solution is to use the app-indicators extension and keep `tray icons` disabled:
> https://github.com/ubuntu/gnome-shell-extension-appindicator

So I tried to install this extension today on 18.04 but just got an error message.

**Comment by Nicolab** [comment]
May be from https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by jeroenpraat** [comment]
Maybe an idea to temporary disable the systray support, until the upstream bug is solved.
