### ISSUE TITLE
No arrows in some themes (i.e. Plata) with Unite, leaving and empty space

### ISSUE THREAD

**Issue by goodwillcoding** [hardpixel/unite-shell#98]
This is a follow up from: https://gitlab.com/tista500/plata-theme/issues/35

Some themes, like Plata, do not have drop down arrows. Unite reserves empty space for the arrows which looks odd with such themes. Does that need to happen?
```
#panel .panel-button .panel-status-indicators-box .popup-menu-arrow {
  width: 12px;
  height: 12px;
}
```

![image](https://user-images.githubusercontent.com/582074/54872418-c8b57a80-4d80-11e9-8981-45fecb254341.png)

**Comment by jonian** [comment]
Hi @goodwillcoding, thanks for the report. I am closing this as duplicate, since it can be solved with a setting to disable panel custom css as requested in issue #43.

**Comment by jonian** [comment]
Fixed in master branch that has better handling of arrow hiding and avoids breaking custom shell themes.
