### ISSUE TITLE
Unite extension causes Gnome Terminal to hang when maximized

### ISSUE THREAD

**Issue by ahnafalrafi** [hardpixel/unite-shell#99]
For some reason, the extension causes Gnome Terminal to hang when maximized. The text cursor stops flashing and text typed after maximizing does not show on the screen but can be seen when the window is restored to its default size. Also, when maximized, roughly two lines of space at the bottom is transparent (the default terminal color for my machine is purple [default Ubuntu 18.10]).
![Screenshot from 2019-03-23 19-06-48](https://user-images.githubusercontent.com/20092027/54873175-0de8a500-4d9f-11e9-8193-b4a78c20b219.png)
![Screenshot from 2019-03-23 19-07-07](https://user-images.githubusercontent.com/20092027/54873176-0e813b80-4d9f-11e9-86d2-baf126b83f9d.png)
![Screenshot from 2019-03-23 19-07-44](https://user-images.githubusercontent.com/20092027/54873177-0e813b80-4d9f-11e9-99e6-cb25116cf5ba.png)

The first one is before typing the alpha beta gamma, the third one is how it is even after typing alpha after Hello World and the second one is after typing all of them and then restoring the window (all done in the same window).

Just to be sure that the issue is caused by the extension, I tried uninstalling the extension first. This immediately resolved the issue. Upon reinstalling, the issue was back.

**Comment by ahnafalrafi** [comment]
The first one is before typing the alpha beta gamma, the third one is how it is even after typing alpha after Hello World and the second one is after typing all of them and then restoring the window

**Comment by falkowich** [comment]
Same here with terminator.

**Comment by jonian** [comment]
@ahnafalrafi Shell version?
@falkowich Distro? Shell version?

Can't reproduce on Arch Linux with Gnome Shell 3.32

**Comment by ahnafalrafi** [comment]
GNOME Shell 3.30.2

**Comment by falkowich** [comment]
My "fix":
_warning your mileage may vary. Take care when removing stuff from your disk.._
```
mkdir ~/backup
mv ~/.local/share/gnome-shell/extensions/unite@hardpixel.eu ~/backup/
``` 
Then reinstall and do an old off/on of the extension.

**Comment by jonian** [comment]
@ahnafalrafi if the fix suggested by @falkowich does not work, try replacing in file `/modules/windowDecoration.js` [Line: 23](https://github.com/hardpixel/unite-shell/blob/master/unite%40hardpixel.eu/modules/windowDecoration.js#L23)

```js
// From this
this._useMotifHints = versionCheck('> 3.30.0');

// To this
this._useMotifHints = versionCheck('> 3.30.2');
```

**Comment by ahnafalrafi** [comment]
Okay, the fix from @falkowich did not seem to work, though I might be misinterpreting how you did the reinstall. However, the fix suggested by @jonian does work.

**Comment by falkowich** [comment]
Humm, after a lock/unlock things got back?
But with the suggestion @jonian gave, it seems that it works now.

Sry for the confusion :)

**Comment by jonian** [comment]
Thanks for the help @ahnafalrafi and @falkowich.

**Comment by develop7** [comment]
@jonian Did the fix make it to extensions.gnome.org yet?

**Comment by jonian** [comment]
@develop7 not yet. I haven't released a new version. I want to fix some minor issues and I will submit a new version soon.

**Comment by develop7** [comment]
The fix above also addresses the issue when Google Chrome windows with custom decorations also get system decorations after unlocking session. I'm using Unite from master branch already, but proper release would be appreciated for sure.

**Comment by behollder** [comment]
> @develop7 not yet. I haven't released a new version. I want to fix some minor issues and I will submit a new version soon.

I waiting too. Ubuntu 19.04, GNOME 3.32.0. my Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.18.9) hang too when it's maximized

**Comment by jonian** [comment]
@behollder The window does not hang, it looses focus, clicking on the window it will regain focus.
That is a Gnome 3.32 issue and not an issue with unite.

https://gitlab.gnome.org/GNOME/gnome-shell/issues/1116
https://gitlab.gnome.org/GNOME/gtk/issues/1749
https://gitlab.gnome.org/GNOME/mutter/issues/505
